### ISSUE TITLE
Saitam's Spinning Pole damage

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1001]
It says 48/92/135 damage.
but in effect, it is 
16 *2 attacks = 32
23 *3 attacks = 69
27 *4 attacks = 108

so, it is missing an attack.

**Comment by cigumo** [comment]
it's also doing 2,3 and 4 attacks in cocos, so the description is wrong. 
Updated description in kr2-desktop-3.2.12 to 32/26/108
