### ISSUE TITLE
Immortal, Poukai Rider - sfx on death

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1002]
Immortals should not make a human death sound on death.

on flash, Sound_EnemyPuffDead.ogg is heard on their death.

Poukai Riders' death has no sfx.
in cocos, Sound_EnemyPuffDead.ogg is heard when the rider dies. and there's no sound when the bird dies.
How about using human death sound for the rider's death?

**Comment by cigumo** [comment]
fixed both in kr2-desktop-3.2.12
