### ISSUE TITLE
The crown is missing in Temple of Saqra Heroric/Iron

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1003]
![2019_11_24_12_28_42_738](https://user-images.githubusercontent.com/43391939/69489095-f7a76180-0eb6-11ea-9290-a7e5bb0d4000.jpg)
![warlord king](https://user-images.githubusercontent.com/43391939/69489096-f8d88e80-0eb6-11ea-9560-88e210c2e38f.png)

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.12
