### ISSUE TITLE
Mercenary / SCUMM Bar - info bar

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1004]
![2019_11_24_13_17_45_278](https://user-images.githubusercontent.com/43391939/69489542-ec573480-0ebc-11ea-9a0a-617b097667f7.png)
![2019_11_24_13_18_15_705](https://user-images.githubusercontent.com/43391939/69489543-ef522500-0ebc-11ea-9304-11e98e9d0b47.png)

these towers' info bars show irrelevant stats in love. (same in cocos.)
Can u change them to like this?
![2019_11_24_13_43_52_851](https://user-images.githubusercontent.com/43391939/69489740-a00df380-0ec0-11ea-955f-51730d5ec1e1.png)

on the flash version:
![mercenary](https://user-images.githubusercontent.com/43391939/69489557-448e3680-0ebd-11ea-89b0-9d2d36243834.jpg)
![scumm](https://user-images.githubusercontent.com/43391939/69489559-45bf6380-0ebd-11ea-9ea5-dd479b903135.jpg)

Mercenary Camp: Here the desert's most fierce dwellers await a contract. 
SCUMM Bar: A safe haven for reckless pirates looking for gold.

mmm, probably not possible because localizing is needed.

**Comment by cigumo** [comment]
we don't have the localized texts. 
let's see what I can do.

**Comment by cigumo** [comment]
## Mercenary Camp
language | name | description
----------|------|-----
en | | The desert's most fierce dwellers await a contract.
es | | Los habitantes más feroces del desierto esperan un contrato.
de | | Die wildesten Bewohner der Wüste warten auf einen Vertrag. 
ru | Лагерь Наемников | Самые яростные обитатели пустынь ждущих контракта.
fr | | Les habitants les plus féroces du désert attendent un contrat.
pt | | Os habitantes mais ferozes do deserto esperam por um contrato.
ja | | 
ko | 용병 캠프 | 사막에서 가장 맹렬한 거주자들이 계약을 기다리고 있습니다.
zh-Hans | | 沙漠里最强大的居住者等待着一个契约。
zh-Hant | | 沙漠裡最強大的居住者等待著一個契約。

## SCUMM Bar
language | name | description
----------|------|-----
en | | A safe haven for reckless pirates looking for gold.
es | | Un puerto seguro para piratas imprudentes que buscan oro.
de | | Ein sicherer Hafen für rücksichtslose Piraten auf der Suche nach Gold.
ru | СКАММ Бар | Притон безбашенных пиратов ищущих золота.
fr | | Un abri pour des pirates téméraires cherchant de l'or.
pt | | Um porto seguro para piratas imprudentes que procuram por ouro.
ja | |
ko | SCUMM 바 | 금을 찾는 무모한 해적들의 안식처.
zh-Hans | | 一个给正在找金子的野蛮海盗的避风港。
zh-Hant | | 一個給正在找金子的野蠻海盜的避風港。

**Comment by cigumo** [comment]
fixed in kr2-x-3.2.16
