### ISSUE TITLE
Necropolis achievement counts skeletons incorrectly

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1009]
![2019_11_24_17_54_17_575](https://user-images.githubusercontent.com/43391939/69492468-8bdced00-0ee6-11ea-8838-8e6bac246828.png)
![2019_11_24_18_01_49_281_new - 3186](https://user-images.githubusercontent.com/43391939/69492536-6bf9f900-0ee7-11ea-87d5-839468a7fc2f.jpg)
![Screenshot_2019-11-25_005758](https://user-images.githubusercontent.com/43391939/69497296-b5b20600-0f1e-11ea-82f6-b943b23dfbe8.jpg)

Even though the Necropolis achievement requires 20 active skeletons, I got this with just 2 necromancer towers.
only 16 skeleton minions can be active at the same time with 2 necromancers. 

but it seems that the the dead skeletons that are already fallen several seconds ago are also counted. (their bones are not yet vanished)

**Comment by cigumo** [comment]
not easy to fix.

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.12
