### ISSUE TITLE
Hawkeye achievement 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1010]
Love
![Screenshot_2019-11-25_095414](https://user-images.githubusercontent.com/43391939/69504863-a906cf80-0f69-11ea-97d2-6344236f261c.jpg)

In love, it also counts the very Crossbow tower that gives bonus range to nearby towers. So, the crossbow only has to buff 3 other towers for this achievement.

Is the crossbow tower included in 4 towers that are given bonus range?
![Screenshot_2019-11-25_002746](https://user-images.githubusercontent.com/43391939/69496898-7aadd380-0f1a-11ea-980d-ba3d1318c08a.jpg)

Flash:
![hawkeye-](https://user-images.githubusercontent.com/43391939/69504401-aa35fd80-0f65-11ea-94d6-916564ba1a7d.jpg)
![hawkeye](https://user-images.githubusercontent.com/43391939/69504378-7ce94f80-0f65-11ea-8b4b-82955ede6d47.jpg)

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.11
