### ISSUE TITLE
blocked holder missing in Beresad's Lair Campaign 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1011]
Love
![Screenshot_2019-11-25_033705](https://user-images.githubusercontent.com/43391939/69499448-9a062a00-0f35-11ea-9ce8-e808fa72d682.jpg)

Cocos
![Screenshot_2019-11-25_033813](https://user-images.githubusercontent.com/43391939/69499456-a8ecdc80-0f35-11ea-9275-d8e3bf5b6611.jpg)

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.11
