### ISSUE TITLE
Bonus Militia missing in Storm Atoll Iron

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1012]
Love
![Screenshot_2019-11-25_041615](https://user-images.githubusercontent.com/43391939/69499972-97f29a00-0f3a-11ea-98d3-7da4a0e1f489.jpg)

Cocos
![Screenshot_2019-11-25_041713](https://user-images.githubusercontent.com/43391939/69499982-a3de5c00-0f3a-11ea-9cb1-d4722e2528c1.jpg)

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.11
