### ISSUE TITLE
A palm tree missing in all 3 maps of Storm Atoll

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1013]
Love
![Screenshot_2019-11-25_041615](https://user-images.githubusercontent.com/43391939/69500148-e5bbd200-0f3b-11ea-8d5f-f88b658ca9c2.jpg)

Cocos
![image0](https://user-images.githubusercontent.com/43391939/69500155-f10efd80-0f3b-11ea-87a8-c38124eb2b3a.png)

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.11
