### ISSUE TITLE
Change Kutsao's Crane Style to be cancelled on move command

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1018]
His Crane Style takes a while (approx. 0.9 second) to finish when compared to Eridan or Assassins. and if you try to move him away after his dodging has started, he will move after the counter-attack.

This and his lack of armor make him vulnerable to high-damaging opponents and can be annoying to players as Kutsao does dodge very often and they lose control of him.

![캡처1](https://user-images.githubusercontent.com/43391939/69652171-92b95a80-10b4-11ea-9356-ca88388043d9.JPG)
![캡처2](https://user-images.githubusercontent.com/43391939/69652347-dc09aa00-10b4-11ea-853e-855d10e2d038.JPG)
![캡처](https://user-images.githubusercontent.com/43391939/69652176-94831e00-10b4-11ea-9b6b-40d2cec1ac56.JPG)
![캡처4](https://user-images.githubusercontent.com/43391939/69653241-3c4d1b80-10b6-11ea-9e31-a511dc48b616.JPG)

**Comment by sunnydaler** [comment]
https://streamable.com/lcpnw
https://streamable.com/jpkij
Kutsao CraneStyles dead enemies. Is it because dodging cannot be cancelled?

**Comment by cigumo** [comment]
fixed in kr2-x-3.2.16
allows interruption while performing the attack (rally change, stun, etc.)
also prevents starting a new attack when the enemy is dead, but will continue if the enemy dies while attacking
