### ISSUE TITLE
Sha'tra's drone damage is different from the description.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1020]
[[Level 2]] 
love Steam: deals 160 (80+80) damage when used on a single target, or 144 (80+64) damage when distributed to multiple enemies
love mobile: deals 144 (80+64) damage on all occasion.

[[Level 3]] is the same on both platforms. 
It deals 224 (80+80+64) damage when used on a single target, or 192 (80+80+32) damage when distributed to multiple enemies.

**Comment by cigumo** [comment]
I can't reproduce it 
added an epsilon to the attack duration to see if it is just a rounding error
kr2-desktop-3.2.12
