### ISSUE TITLE
Review HP limits of Abduction and Disintegration.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1021]
Sha'tra's Abduction description says the HP limits are 250 / 600 / 1000(for a group) respectively.
Nivus's Disintegration, 170 / 330 / 480. 

but it seems that they can use the skills only when the total hp is less than that.

So, it is not "or less" but "under".

I checked the HP limits of kr3 heroes instakill (Bravbark's Branchball and Vez'nan's Soul Burn)
and their instakills work fine.

**Comment by cigumo** [comment]
fixed in kr2-x-3.2.16
