### ISSUE TITLE
Review spawns in Desecrated Grove wave 13.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1024]
![20191128132917_1](https://user-images.githubusercontent.com/43391939/69777461-bdee9780-11e3-11ea-99f4-7e1ba1ec8527.jpg)

 in wave 13,
love enemy spawns from these 5 points are different from cocos.
(I notated the cocos enemy spawns in the picture.)

**Comment by cigumo** [comment]
I think they are the same amounts
- 2 ghouls from each
- 10 zombies from each
- 5 ghouls from top three spawn points

**Comment by sunnydaler** [comment]
correct.
