### ISSUE TITLE
levelup *ding* sound (at intro and level-up) goes missing sometimes.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1026]
![sound_missing](https://user-images.githubusercontent.com/43391939/69892568-18096d00-134a-11ea-9132-008742a9e274.jpg)

**Comment by cigumo** [comment]
I could use more information about when it happens
- long play sessions?
- specific levels? 
- specific heroes?

**Comment by sunnydaler** [comment]
Level specific? No.
Long play session? Yes.
Hero specific? Not sure.

**Comment by sunnydaler** [comment]
It happened again after playing for a long time (1 hour?).
Only Saitam was ok, and the other heroes were missing the sfx.

**Comment by cigumo** [comment]
fixed in kr2-3.2.21
