### ISSUE TITLE
Sha'tra abducts Deviltide in water.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1027]
![mobizen_20191130_143909_new - 225](https://user-images.githubusercontent.com/43391939/69896318-5f5f2000-1381-11ea-9d8f-d187819ced2b.jpg)
https://i.imgur.com/hIDGJlM.mp4

Sprite is cut below water surface.
does he abduct any other swimming enemy? I haven't seen one.

**Comment by cigumo** [comment]
Sha'tra should not abduct any enemies in the water. 
fixed in kr2-x-3.2.16
