### ISSUE TITLE
BajNimen's attacks and sound effect

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1028]
Love: https://streamable.com/ui6ma

- [ ] 1.  the cds of boss's ranged attack (not the storm attack) and tail attack are different from cocos. It seems that love BajNimen's attack cds are counted differently.
- [ ] 2. The sfx for bolt hit is heard later than the hit. 
- [ ] 3. In Cocos, the tail attack has the sound of a whiplash. 
In love, it has no sound. and there's more to this.
  Even if cigumo adds the sound, it will be overlapped with the bolt hit sound unless no. 1 and 2 issues are fixed. It is because love BajNimen often starts tail attack even before the bolt hits his target. (as shown in the pic below)
![2019_12_01_03_28_56_923_new - 334](https://user-images.githubusercontent.com/43391939/69905122-21024900-13f3-11ea-873c-1f2e1a9e4ea1.jpg)

**Comment by cigumo** [comment]
added the missing tail attack hit sound in 4.2.10

left the other values as is because we reviewed them when we were making the impossible mode already.
