### ISSUE TITLE
Hand Of Midas - Banshee displays 0 gold when cursing a tower.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1029]
https://streamable.com/gouys
If banshees get to curse towers while Hand of Midas is in effect, 0 gold is displayed around them and a gold sound effect is heard upon the event.
![Screenshot_2019-11-30_232850](https://user-images.githubusercontent.com/43391939/69901809-cbfe0d00-13c9-11ea-9a1c-82024393f19b.jpg)
![Screenshot_2019-11-30_232903](https://user-images.githubusercontent.com/43391939/69901812-d3251b00-13c9-11ea-896e-389b493678b3.jpg)

**Comment by cigumo** [comment]
fixed in 4.2.10
