### ISSUE TITLE
Korean localization

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1033]
- [x] Tip 04
![20191026_030354](https://user-images.githubusercontent.com/43391939/69904160-b21ef300-13e6-11ea-9c53-bf4e4a1a02a9.jpg)
![20191201025807_1](https://user-images.githubusercontent.com/43391939/69904163-b6e3a700-13e6-11ea-9aba-b53693ff9bd4.jpg)

"Lightning bolts deal area damage, so they are best used against large concentrations of enemies."
번개 화살은 --> 번개는

- [x] High Elven Mage description
![65702743-8027a280-e0be-11e9-839b-7bfcb9347e12](https://user-images.githubusercontent.com/43391939/75518677-d79eb580-5a44-11ea-872b-90db4539b589.jpg)
에너지 화살 (energy arrow) --> 마법탄 (magic bullet).

- [x] "Call Reinforcements" power name
![69904031-cd88fe80-13e4-11ea-806f-e48e7275aa23](https://user-images.githubusercontent.com/43391939/75518858-44b24b00-5a45-11ea-9d17-af9d6e9e6fea.jpg)

지원군 (Reinforcements) --> 지원군 호출 (Call Reinforcements)

- [x] Perfect Parry description
![69904006-8ac72680-13e4-11ea-911f-88908369c6c2](https://user-images.githubusercontent.com/43391939/75518952-79be9d80-5a45-11ea-925e-2ea5ce132216.jpg)
행태 없는 --> 형태 없는
Note: 행태 means behavior, 형태 is shape.

- [x] Xin's Inspire description
"Xin's furious roar inspires nearby allies to deal double damage for 3/5/7 seconds."
translation is bad. Grammatically incorrect. Change it to the following:
신의 분노에 찬 포효가 주변의 아군을 고취하여, 3/5/7초 동안 공격력을 2배로 높입니다.

- [x] Sylvan Curse name
실바의 저주 --> 숲의 저주

- [x] Catha hero name
카사 --> 캐사

- [x] Lilith hero name
리리스 --> 릴리스

- [x] Lilith hero Resurrection description
"Lilith has a 10%/20%/30% chance of reviving instantly after being slain."
리리스가 죽으면 10/20/30% 확률로 즉시 부활합니다. -->
릴리스가 죽으면 10/20/30% 확률로 즉시 부활합니다.

- [x] Webspitter Spider enemy name
Webspitter Spider: 그물술사 거미 --> 그물거미
Websipitter: 그물술사 --> 그물거미 
Note: 술사 is only used on a person

**Comment by cigumo** [comment]
added in 4.2.10
