### ISSUE TITLE
BajNimen's bolt and Veznan demon's fireball - wrong hitbox

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1034]
cocos: https://i.imgur.com/RF8m9eo.mp4
love: https://i.imgur.com/DJ9fkdK.mp4
![cocos](https://user-images.githubusercontent.com/43391939/69904886-fa8ede80-13ef-11ea-9c4c-eae7f4d327d0.gif) ![love](https://user-images.githubusercontent.com/43391939/69904851-6cb2f380-13ef-11ea-82fe-12cfb6f8f1c0.gif)

- [ ] demon's fire decal is placed behind BajNimen's body.

- [ ] BajNimen's bolt hit box is too high.

**Comment by cigumo** [comment]
fixed the mod offset but still shooting at the head.
4.2.10
