### ISSUE TITLE
dashed line missing on the worldmap / DancheZI

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1038]
Love
![Screenshot_2018-12-05-21-12-22](https://user-images.githubusercontent.com/43391939/69921691-deff0300-14d7-11ea-9963-7bab99b342b1.png)

cocos
![cocos](https://user-images.githubusercontent.com/43391939/69921680-aceda100-14d7-11ea-95e8-727f6fd42d8e.png)

**Comment by cigumo** [comment]
fixed in kr2-phone-3.2.14
