### ISSUE TITLE
Karkinos "Iron Pincer" description

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1041]
descriptions are
level 1: Improves base attack damage by 5 points.
level 2: --------- by an additional 10 points.
level 3: --------- by an additional 20 points.

actually  additional damage increments are 5/5/10.

two ways i can think of are
1. to remove the "an additional" part from the sentences
or 
2. to replace the numbers with actual numbers; 5/5/10.

-------------------------
Alric, Nivus, Blackthorne, Sha'tra also have damage stat boost skill.
and their descriptions match the actual damage increments.

**Comment by cigumo** [comment]
changed to 5/5/10 in kr2-phone-3.2.16. desktop was OK AFAIK
