### ISSUE TITLE
Faustus casts Dragon Lance on flying enemies 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1042]
![Screenshot_2019-12-04_141232](https://user-images.githubusercontent.com/43391939/70114749-e02f5c00-16a0-11ea-9e44-1cacc12f35e8.jpg)
![Screenshot_2019-12-04_141617](https://user-images.githubusercontent.com/43391939/70114753-e45b7980-16a0-11ea-99db-0bba9b293575.jpg)
explosion decal is on the ground. Maybe this attack is not meant to be used on flying enemies?
![2019_12_04_16_34_17_656_new - 155](https://user-images.githubusercontent.com/43391939/70122555-34900700-16b4-11ea-92c4-6e114b283c64.jpg)

**Comment by cigumo** [comment]
cocos is the same. 
doesn't look good but I'm not sure it's better to disable it for flying enemies.
