### ISSUE TITLE
Bonehart height

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1048]
Love mobile Bonehart flies lower than in cocos and love desktop.
The gap between the hp bar and its body is bigger in love mobile.
![desktop](https://user-images.githubusercontent.com/43391939/70223384-016e7600-178f-11ea-86fd-417240c93d1e.jpg)
![mobile](https://user-images.githubusercontent.com/43391939/70223387-02070c80-178f-11ea-871e-7380c109eb52.jpg)

 its elevated hit box (as shown in love phone pic) has something to do with this?

Ashbite is fine.

**Comment by cigumo** [comment]
regenerated all textures for Bonehart in the phone version
kr2-phone-3.2.18
