### ISSUE TITLE
Mirage and Redspine - missed shots are shown as arrows.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1050]
https://i.imgur.com/wOZl0uY.mp4
![2019_12_05_22_19_22_309_new - 580](https://user-images.githubusercontent.com/43391939/70239192-34743200-17ae-11ea-8f43-63c39ed44577.jpg)

![redspine](https://user-images.githubusercontent.com/43391939/70434382-685d9900-1ac7-11ea-9f04-69f07ca84866.gif)

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.14
