### ISSUE TITLE
gunshot hit has no blood effect

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1051]
![20191205235202_1](https://user-images.githubusercontent.com/43391939/70247222-6096af80-17bc-11ea-99a5-ffb2c5cd0c22.jpg)
gunshots from Dante, Pirate Hero, Pirate Watchtower need this blood mark on hit.

cocos also seems to be missing this effect.

**Comment by cigumo** [comment]
they had a typo in the description so the blood fx was not showing
🤦‍♂ 
fixed in kr2-x-3.2.16
- hero pirate shotgun
- dante shotgun
- tusken shotgun 
- tower dwarf shotgun
