### ISSUE TITLE
Pirate Watchtower's gunshot missing water effect on a missed shot.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1052]
![2019_12_06_00_18_46_589_new - 1671](https://user-images.githubusercontent.com/43391939/70248633-86bd4f00-17be-11ea-8aa7-25eb39361d4e.jpg)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43391939/70248890-f3d0e480-17be-11ea-97ff-224403c8fa49.gif)

and probably the pirate hero Blackthorne's gunshot, too.

**Comment by cigumo** [comment]
fixed in kr2-x-3.2.16
