### ISSUE TITLE
Maq'wa Urqu Volcano fireball damage

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1054]
- [ ] the fireball damage is odd. when i checked the damage in iron challenge on love,
     it repeated this pattern: [138 - 142 - 158 - 138]. So it goes like this  - [138 - 142 - 158 - 138] - [138 - 142 - 158 - 138] - ...
The same damage pattern is observed when u fail to save the princess during the campaign on love.

- [ ] the damage type should be changed to be the same as in cocos. it is because 3-digit explosive damage every 8 seconds has huge impact in the iron challenge.

**Comment by cigumo** [comment]
in kr2-desktop-3.2.14:
- changed fireball damage type to physical 
- the damage pattern is due to the volcano bombs launching from 3 different points
