### ISSUE TITLE
Maq'wa Urqu volcano shoots at moving units.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1058]
v  3.2.15

there is no point for the volcano to target moving units because
1. it doesn't look pretty; fireball falls off the paths. it misses target 100% cuz fireball travels a long way to hit.
2. for consistency's sake. kr2 cocos, kr2 flash, kr3 tainted pit, all ranged enemies in kr series

**Comment by cigumo** [comment]
fixed in kr2-x-3.2.16
