### ISSUE TITLE
Freezing should stop enemy's regeneration.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1059]
Freeze items and attack do stop enemy's regen in kr1 cocos. 
And Arivan's freeze attacks stop it in kr2 love and cocos. #532 

So, it must be the same for freeze items in kr2 mobile

**Comment by cigumo** [comment]
in kr2-x-3.2.18: 
- freeze (but not stun) will stop regen for 
  - enemy_werewolf
  - enemy_werewolf_lycan
