### ISSUE TITLE
Blessing of Elynie doesn't apply t level 4 barracks 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1061]
I tested it on debug build.
it proced on low level barracks and Renegades but not on lvl 4 barracks.
![lvl3](https://user-images.githubusercontent.com/43391939/70855001-fd68f380-1f06-11ea-9d49-0a185f742e36.gif)
![lvl1](https://user-images.githubusercontent.com/43391939/70855005-00fc7a80-1f07-11ea-93ee-c80fd60c1bd7.gif)

![2019_12_15_06_24_51_713_new - 23635](https://user-images.githubusercontent.com/43391939/70854985-ba0e8500-1f06-11ea-9b39-7fd3ae10e092.jpg)

test was done with Heretic. 50 times on each lvl 4 barracks. None of those 100 soldiers revived.

**Comment by cigumo** [comment]
fixed in 4.2.10
