### ISSUE TITLE
God King and Reaper Queen - sfx missing

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1063]
- [x] sfx for god king's spells
krf_sfx_endless_invisibility_consitar.ogg
krf_sfx_endless_obelisk_v3.ogg
krf_sfx_endless_sandhole.ogg

- [x] sfx for reaper queen's poison attack and laying Reapers.

**Comment by cigumo** [comment]
5.6.14: 
- god king's sounds are OK
- reaper queen sounds are OK
