### ISSUE TITLE
Enemies invulnerable under the cloaking spell of God King

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1064]
![Screenshot_2019-12-14_180659](https://user-images.githubusercontent.com/43391939/70931262-63c25300-207a-11ea-9c25-1fed324fc271.jpg)

1. They don't take damage from dwaarp and plague carriers. 
other area attacks could probably have no effect on them either.
2. the affected enemies cannot be blocked. (probably designed to be so. but isn't the effect missing any limit in duration?)
3. The spell is not silence-able with totem of spirit
4. The spell has no safe nodes to exits.

**Comment by cigumo** [comment]
fixed 1, 3 and 4.  Left 2 as it's on purpose.
