### ISSUE TITLE
Gnoll endless level - sfx missing

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1065]
- [x] When the gnoll on the throne calls catapult, the gnoll should makes this sound kro_sfx_heehaw_call[op2].ogg

- [x] when the warleader attacks, it is missing its unique sfx. Is it kro_sfx_creep_doublesword[op1].ogg?
 and does the miniboss have death cry? kro_sfx_creep_death[op1].ogg?

- [x] catapult is missing the sfx for shooting.

**Comment by cigumo** [comment]
fixed in 4.2.10
