### ISSUE TITLE
Timelapsed enemies still interact with nearby enemies

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1066]
Ogre Magi's lifelink is active while the ogre is phased out.
https://i.imgur.com/nZpkWIX.mp4

Timelapsed Gnawer gets bonus damage when 3 or more allies are nearby. And a group of Gnawers get bonus damage when they get close to the phased-out Gnawer.
https://i.imgur.com/CyJ1d7Z.mp4

Question 1; can scourger buff dmg of the phased-out enemies?
Question 2; does Bruce's ulti Lions have similar effect like timelapse? I mean isolating targets from the environment.

**Comment by cigumo** [comment]
changes in 4.2.10:
- ogre magi: will not break existing links but it will prevent creating new ones when phased out or vis.bans F_RANGED
- gnawer aura: will check vis.bans F_RANGED
