### ISSUE TITLE
Wrong fx for evoker's disabling

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1067]
![Screenshot_2019-12-17_135229](https://user-images.githubusercontent.com/43391939/70965894-9a2cbc00-20d4-11ea-97ff-9ddbbe36477a.jpg)
![Screenshot_2019-12-17_135159](https://user-images.githubusercontent.com/43391939/70965902-a31d8d80-20d4-11ea-8ac0-f4915832a137.jpg)

**Comment by cigumo** [comment]
fixed in kr3-phone-4.2.10
