### ISSUE TITLE
Ranged barracks, reinforcements, and Awoks almost never hit hyenas with their ranged attacks. / kevin32

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#107]

**Comment by sunnydaler** [comment]
I played Redwood Stand Iron on mobile and Steam with the same setup and in veteran mode. 
And it is apparent that units on Steam version have difficulty targeting hyenas.
https://youtu.be/BcpSAotIi3E

**Comment by cigumo** [comment]
On a first pass I could not find anything wrong. 
Reduced prio.

**Comment by cigumo** [comment]
vids from sunnydaler
https://streamable.com/lnaze
https://streamable.com/gvv9d

**Comment by cigumo** [comment]
I fixed it by resetting the arrow predicted position on insert. 
I'm worried it's too precise now. Needs testing. 

fixed for: 
- barracks 
- reinforcements
- stage 4 awoks
- stage 6 gryphon soldiers 
- stage 16 camp archers
