### ISSUE TITLE
Spear Maiden Hut info bar

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1074]
It wasn't like this before.
![20191230072844_1](https://user-images.githubusercontent.com/43391939/71563618-0f858d00-2ad6-11ea-8e3d-8c7d40cfed41.jpg)

Previously 
![Screenshot_2019-12-30_072603](https://user-images.githubusercontent.com/43391939/71563607-cf260f00-2ad5-11ea-8303-eb42c84b688d.jpg)

**Comment by cigumo** [comment]
This is flash: 
![Screen Shot 2020-01-06 at 3 29 07 PM](https://user-images.githubusercontent.com/934821/71839275-8d7b0280-3099-11ea-8153-f26a9d1491ab.jpg)

**Comment by cigumo** [comment]
## Spear Maiden Hut
language | name | description
----------|------|-----
en | Spear Maiden Hut | A tribe of proud warrior women ready for battle
es | Choza de las Amazonas | Una tribu de orgullosas guerreras listas para la batalla
de | Speermaiden-Hütte | Ein Stamm stolzer Kriegerfrauen, bereit für den Kampf
ru | Хижина копейщиц | Гордое племя женщин-воинов готово к битве
fr | Hutte de Demoiselle à la lance | Une tribu de guerrières fières, prêt au combat.
pt | Cabana da Lanceira | Uma tribo de orgulhosas guerreiras prontas para a batalha.
ja | 槍乙女の小屋 | 戦いの準備ができている誇り高い戦士の女性の部族
ko | 창전사 오두막 | 전투 준비가 된 자랑스러운 여전사 부족
zh-Hans | 长矛女战士小屋 |  一个骄傲的女战士部落已准备战斗
zh-Hant  |長矛女戰士小屋 | 一個驕傲的女戰士部落已準備戰鬥

**Comment by cigumo** [comment]
fixed in kr2-x-3.2.20
