### ISSUE TITLE
Armored enemy tip card is not localized in full.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1077]
![Screenshot_2019-09-26_202058](https://user-images.githubusercontent.com/43391939/71819485-67705500-30cf-11ea-83b5-c73c9f701693.jpg)
![Screenshot_2020-01-06_215504](https://user-images.githubusercontent.com/43391939/71819506-70f9bd00-30cf-11ea-85d2-e866136ecf80.jpg)

**Comment by cigumo** [comment]
already fixed by 4.2.09
