### ISSUE TITLE
Eldritch Doom - vfx and targeting

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1080]
- [x] ED's vortex-like fx doesn't follow the target while they still move - 
Love (below)
https://i.imgur.com/T0cXh9E.mp4
![2020_01_10_21_20_36_538_new - 175](https://user-images.githubusercontent.com/43391939/72206996-94f63d80-34d7-11ea-8864-d5250f37f2a6.jpg)

cocos (below) https://i.imgur.com/tNHFtK0.mp4
the vortex appears beforehand on the target and follows the target's movement. and then, the ray comes out and hits where the vortex is placed.
![image0](https://user-images.githubusercontent.com/43391939/72207009-bd7e3780-34d7-11ea-9461-89c2651404be.jpg)
![image1](https://user-images.githubusercontent.com/43391939/72207019-d25acb00-34d7-11ea-9661-620fc217c368.jpg)

- [x] does ED retarget in cocos? - cocos Death Ray (https://i.imgur.com/42zbTgm.mp4) and love Core Drill retarget another enemy if the original target gets lost during the preparation stage (i mean the time between the initiation and the execution).

**Comment by cigumo** [comment]
fixed in 4.2.10
