### ISSUE TITLE
kr2: Sha'tra Energy Glaive damage type

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1081]
True damage in cocos.
Physical damage in love.

Below is a screen capture of cocos shatra
![Screenshot_2020-01-14_131820](https://user-images.githubusercontent.com/43391939/72314052-ca19b000-36d0-11ea-8d6b-689718aaa5a3.jpg)
![20200114_132040](https://user-images.githubusercontent.com/43391939/72314065-da318f80-36d0-11ea-8d4f-4c791101a88d.jpg)

**Comment by cigumo** [comment]
fixed in 4.2.24
