### ISSUE TITLE
kr1 sounds quality

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#1094]
sox is 
- adding noises when adjusting gain (clicks, white noise)
- trimming unwanted parts (eg. beginning of Young-Mage-01d)

idea: 
- change all vo to 44kHz in desktop

**Comment by sunnydaler** [comment]
ver. 4.0.06

Gerald: death cry has white noise.
Alleria: "swift like the wind" and "calm and careful" are loud and noisy. there is a click at the end of Alleria's death cry.

**Comment by cigumo** [comment]
in kr1-4.0.07 fixed: 
- alleria swifth like the wind
- alleria calm and careful
- alleria death cry
- gerald death cry (improved just a bit)

**Comment by sunnydaler** [comment]
Magnus's "it's a kind of magic" has white noise
Hacksaw's "Cowabunga" has crackles
Gerald's "Prepare for glory" has white noise.

**Comment by cigumo** [comment]
in kr1-4.0.15
- converted all voice overs to 44.kHz (500 kB increase total)

Not fixed: 
- Gerald's prepare for glory has white noice in source file
- Hacksaw's "Cowabunga" has crackles in source wav
- Magnus's "it's a kind of magic" has white noise in source
