### ISSUE TITLE
sapper and orc champion pictures are swapped in encyclopedia

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1097]
![20200201154002_1](https://user-images.githubusercontent.com/43391939/73589088-004e9080-4515-11ea-84fc-17796c896ca4.jpg)
![20200201170902_1](https://user-images.githubusercontent.com/43391939/73589166-0a24c380-4516-11ea-8e23-be7c86fabfb1.jpg)
![20200201171216_1](https://user-images.githubusercontent.com/43391939/73589167-0a24c380-4516-11ea-9ea0-72e3d535d60d.jpg)
portraits of info bar and new enemy icon are ok.

**Comment by cigumo** [comment]
fixed in 4.0.04
