### ISSUE TITLE
Tesla ray should interrupt when no enemies in range

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1103]
cocos![cocos](https://user-images.githubusercontent.com/43391939/73594667-c9e43600-4553-11ea-96c8-8986d09928f1.gif)

love![love](https://user-images.githubusercontent.com/43391939/73594668-cb156300-4553-11ea-88d9-6d31768cd0e2.gif)

**Comment by cigumo** [comment]
fixed in 4.0.04
