### ISSUE TITLE
Death Ray and death animation

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1105]
The following enemies display normal death animation when killed by death ray.

Rocketeer
Gargoyle
Gulaemon (both in the air and on the ground)
Demon Imp
Black Hag

![1](https://user-images.githubusercontent.com/43391939/73603841-541bb100-45cb-11ea-8b3b-c189539aabe9.gif)
![2](https://user-images.githubusercontent.com/43391939/73603875-d3a98000-45cb-11ea-8290-f2d23f191e9e.gif)

**Comment by cigumo** [comment]
fixed in 4.0.04
