### ISSUE TITLE
Teleport fails

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1106]
video 1 (check 0:02, 0:42, and 0:51 marks). 
two types of failure here. 
one of them occurs  at 0:02. the portal was not even opened on the ground.
the other happens at  0:42 and 0:51. 
https://cdn.discordapp.com/attachments/567811170342535188/673395689157558281/2020_02_02_13_45_06_809_new.mp4

video 2 https://streamable.com/0ujo7

**Comment by cigumo** [comment]
fixed in 4.0.04
- 1: a redundant distance check was aborting the teleport because it was not compensating for node prediction
- 2: the teleport is triggered even if the enemy reached the max number of teleportations possible.
