### ISSUE TITLE
Death Ray is hindered by Teleport.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1107]
If both skills are off the cooldown, I think it is intuitive for the tower to use Death Ray first. You know, Death Ray cooldown is double that of Teleport.

However, love Arcane Wizard always uses Teleport first.
and if there is only 1 enemy, the enemy is sent back. sent back again and again until it fails (#1106)
https://streamable.com/kr06r

**Comment by cigumo** [comment]
fixed in 4.0.04
