### ISSUE TITLE
Sniper Shot and Crit

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1108]
1. rarely, "crit" sign is displayed for the headshot.
2. it seems that the sniping bullet is affected by "crit" chance upgrade in love, dealing 2*(20/40/60% of the victim's max HP + base damage).
![20200203061221_1](https://user-images.githubusercontent.com/43391939/73615595-920ce980-464c-11ea-8ef5-1d1c0e84451d.jpg)

3. and also rarely, "headshot" sign is not shown when the enemy is one-hit OKed by the bullet.

**Comment by cigumo** [comment]
In version 4.0.04
- 1: fixed
- 2: fixed 
- 3: when there is a sniping shot that is not an instakill there is no pop in cocos.
