### ISSUE TITLE
Blazefangs stop upon seeing cloacked assassins and shoot them inflicting no damage.

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#1110]
![kr2-love-blazefangs-and-cloacked-assassins-bug mov](https://user-images.githubusercontent.com/934821/73659587-520e2c80-4675-11ea-949c-ee50b10f1642.gif)

**Comment by victoriadelima** [comment]
http://support.ironhidegames.com/a/tickets/60665

**Comment by victoriadelima** [comment]
Windows 10 Home Version 1809 OS Build 17763.973
kr2-desktop-3.2.20

**Comment by cigumo** [comment]
http://support.ironhidegames.com/a/tickets/73832

**Comment by cigumo** [comment]
fixed in 5.1.00
