### ISSUE TITLE
Ranged soldiers don't fall back in formation after melee fight

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1114]
Sylvan Elves
Barbarians with Throwing Axe upgrade

it is different from cocos and hurts their survivability because there is higher chance for them to get poisoned or range-attacked as they are more densely packed when they are lumped together standing closer to enemies. 
when the formation breaks, soldiers look like metal clips attracted to a magnet pole. Not good visually.

**Comment by cigumo** [comment]
improved in kr1-4.0.07
