### ISSUE TITLE
Map blemishes

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1117]
Hakraj Plateau map
![20200205062619_1](https://user-images.githubusercontent.com/43391939/73790145-56585800-47e3-11ea-8519-92db9d86e577.jpg)

Sarelgaz's Lair map
![20200209015458_1](https://user-images.githubusercontent.com/43391939/74088982-8784a100-4adf-11ea-8fa4-058880fa53b1.jpg)

**Comment by cigumo** [comment]
fixed in kr1-4.0.07
