### ISSUE TITLE
soldier's health bar size varies in height (thickness)

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1123]
![20200206094422_1](https://user-images.githubusercontent.com/43391939/73896760-46b23f80-48c7-11ea-8d40-34e494967fc7.jpg)
![20200206093914_1](https://user-images.githubusercontent.com/43391939/73896768-4fa31100-48c7-11ea-9bd4-9d0652253ac0.jpg)

**Comment by cigumo** [comment]
yes. this varies with the resolution of the screen and the msaa settings

**Comment by cigumo** [comment]
<img width="239" alt="Screen Shot 2020-02-14 at 1 46 49 PM" src="https://user-images.githubusercontent.com/934821/74550652-81078680-4f30-11ea-9414-e03389836a2e.png">

this is msaa 4
