### ISSUE TITLE
Coldstep Mines Iron - bonus barracks rally point

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1124]
![20200206100310_1](https://user-images.githubusercontent.com/43391939/73897005-fab3ca80-48c7-11ea-96d1-cbb6441e0f79.jpg)
![Screenshot_2020-02-06_100247](https://user-images.githubusercontent.com/43391939/73897048-1a4af300-48c8-11ea-9d74-8f3bfd4a8d31.jpg)

the two barracks on the left, their initial rally points are tipped to the north relatively.

![fix](https://user-images.githubusercontent.com/43391939/73897058-26cf4b80-48c8-11ea-9f81-12a0e8dcff83.gif)

**Comment by cigumo** [comment]
fixed in kr1-4.0.07
