### ISSUE TITLE
Sasquatch 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1125]
- [x]  LIKE A HENDERSON achievement: It should be achieved not when the cave is opened by rain of fire, but when Sasquatch is hired.

like here in cocos. 
https://youtu.be/hhYqQlobpMI?t=825

- [x] gray out the sasquatch icon if the cave is frozen.
![Screenshot_2020-02-05_043649](https://user-images.githubusercontent.com/43391939/73978649-1d99b980-4970-11ea-9ded-28501a1a9d24.jpg)
![Screenshot_2020-02-05_043923](https://user-images.githubusercontent.com/43391939/73978677-2b4f3f00-4970-11ea-9bb7-e20f55e5013a.jpg)

**Comment by cigumo** [comment]
fixed in 4.0.07
