### ISSUE TITLE
Juggernaut's missile

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1126]
- [x] in cocos, its missile takes a turn before heading to targets.

- [ ] in cocos, Juggernaut's missile prioritizes imperial guards. There are 3 groups of Imperial Guards. if we name the 3 groups as A (middle left), B (middle right), C (top center).
the first target is A.
if target A is dead, next target is B 
if targets A & B are dead, the next target is C.
Hero is its next target.
In love, it seems to be not in this order.
Note: the boss doesnt shoot at the units that are in melee with itself.
here's a cocos test video 
https://streamable.com/luft7

**Comment by cigumo** [comment]
kr1-4.0.07
won't fix the priorities as it seems to be an artifact in cocos code
