### ISSUE TITLE
myconid and death spawn

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1128]
animation is different from cocos.
death spawn animation should start after the boss's death explosion animation.
Not before.

cocos (50% speed)
https://cdn.discordapp.com/attachments/567811170342535188/675059996978839553/cocos_myconid.mp4

love (50% speed)
https://cdn.discordapp.com/attachments/567811170342535188/675059997759111168/love_myconid.mp4

and
I asked toria about the missing sfx for death spawn. probably she will contact with an answer soon.

**Comment by cigumo** [comment]
fixed in kr1-4.0.07
