### ISSUE TITLE
J.T and mods

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1129]
poison mod and sorcerer mod
- [x] mod size is small for his giant body.

- [x] remove mods along with hp bar when he is dead.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43391939/73978004-c9420a00-496e-11ea-98b5-9e62b6fd6c46.gif)

**Comment by cigumo** [comment]
fixed in kr1-4.0.07
