### ISSUE TITLE
Enemy description

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1130]
- [x] Dark Slayer

![20200207051313_1](https://user-images.githubusercontent.com/43391939/73978064-e70f6f00-496e-11ea-9c3b-265e7365797d.jpg)
on the new enemy card and in encyclopedia
replace the semicolon with a comma.

- [x] Raider
![20200209012752_1](https://user-images.githubusercontent.com/43391939/74088860-40e27700-4ade-11ea-9c0a-b0fe560c2138.jpg)
remove the hyphen.
insert an asterisk.

**Comment by cigumo** [comment]
fixed in kr1-4.0.07
