### ISSUE TITLE
Magma Elemental - enemy card is missing.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1132]
it should pop up when it spawns from the volcano in Forsaken Valley campaign for the first time.

Here's a unity gameplay screenshot captured when the enemy spawned for the first time.
![when it spawns for the first time.-02-07_122000](https://user-images.githubusercontent.com/43391939/74004068-10082200-49b8-11ea-9c1e-48fea8054cdf.jpg)

**Comment by cigumo** [comment]
fixed in 4.0.07
