### ISSUE TITLE
Arcane Wizard should abort its ray instantly.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1133]
love
![love](https://user-images.githubusercontent.com/43391939/74012635-0f7a8600-49ce-11ea-824c-261cf2461cbe.gif)

cocos
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43391939/74026753-2b8c2080-49ea-11ea-8868-5c4faff12cf6.gif)

love arcane is relatively late when it comes to aborting the ray, a few frames of the ray animation still plays after the target is dead.

**Comment by cigumo** [comment]
fixed in kr1-4.0.07
