### ISSUE TITLE
Cerberus shouldn't be stunned, teleported or thorned.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1136]
![20200209021137_1](https://user-images.githubusercontent.com/43391939/74089156-9ec48e00-4ae1-11ea-82b4-02eee667ac7e.jpg)

![20200209115222_1](https://user-images.githubusercontent.com/43391939/74095368-d4459780-4b32-11ea-8300-4b4690d1d975.jpg)

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/43391939/74029749-ba03a080-49f0-11ea-94dc-e0972fc0d458.gif)

**Comment by cigumo** [comment]
in kr1-4.0.07 the Cerberus can't be : 
- stunned
- teleported
- polymorphed
- thorn
- disintegrated by the Arcane mage
- slowed down

I think it's everything :)
