### ISSUE TITLE
Damage type of bosses' area attacks

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1140]
I find this perfectly fine as it spices up the game without breaking any. let's wait and see if testers can deal with this.

- [ ] Juggernaut
missile's damage is 150 physical damage in cocos. but explosive in love.
melee damage is physical in cocos. And explosive in love.

- [ ] Greenmuck

- [ ] Ulguk-Hai

- [ ] Moloch

- [ ] Lord Blackburn
his basic attack damage type is physical in cocos, and explosive in love.

![20200210205905_1](https://user-images.githubusercontent.com/43391939/74148251-5bd0fa80-4c48-11ea-884b-4fa0aac8c624.jpg)
and this stunning attack deals 1-4 damage. (same in cocos?)

**Comment by cigumo** [comment]
- jug missile does physical damage in love
- blackburn stun damage is 1-5 true
