### ISSUE TITLE
Upgrading Death Ray and Polymorph resets the cd

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1142]
https://streamable.com/v7y2j
this is a gameplay run at 30fps.
in  this video, I bought Death Ray lvl 1 at frame 200
and upgraded it to lvl 2 and lvl 3 at frame 914 and 1386 respectively.

Arcane Wizard starts attacking from frame 1244 but 
Death Ray is activated at frame 1915. That's almost 1 min after the purchase of the skill.

**Comment by cigumo** [comment]
yes, that's how they work in cocos and in kr2/3 as well
when you upgrade a power the cooldown is reset.
the cooldown for death ray at level 3 is 16s, which matches the video: 0:45 upgrade, 1:01 shoots

so I guess this is ok.

**Comment by cigumo** [comment]
fixed in 4.0.07 for: 
- musketeer sniper shots
- arcane wizard disintegrate and teleport
- sorcerer polymorph
