### ISSUE TITLE
Denas barrage

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1150]
- [x] he sometimes looks at the other way and orders barrage
![20200214225726_1](https://user-images.githubusercontent.com/43391939/74540256-ceacdf00-4f82-11ea-9c40-d1072ed2111b.jpg)

- [ ] barrage's prediction is not ideal against fast-approaching enemies such as wulves.
![20200214230233_1](https://user-images.githubusercontent.com/43391939/74540350-f603ac00-4f82-11ea-9959-2e12855f6e8b.jpg)

![2020_02_14_23_31_34_416_new - 116](https://user-images.githubusercontent.com/43391939/74540614-6e6a6d00-4f83-11ea-8847-69c9cc36d9ba.jpg)

**Comment by cigumo** [comment]
kr1-4.0.07
the prediction seems to be ok, the problem seems to be that the catapult was triggered before the enemies are blocked by the soldiers, so the speed is considered.
fixed the direction denas looks when ordering the attack
