### ISSUE TITLE
Missing KR1 Sound effects

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1151]
- [x] Worg Rider: add wulf attack sound.

- [x] Ancestor: add the soldier attack sound.

- [x] SCRAT's MEAL (in Glacial Heights): add "Sound_HitIce" sound for clicking on the ice.

https://cdn.discordapp.com/attachments/567811170342535188/677901537116291072/Scrats_Meal_on_Flash.mp4

**Comment by cigumo** [comment]
fixed in kr1-4.0.07
