### ISSUE TITLE
Stage 18: map blemishes

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1152]
![74546962-b347d100-4f8e-11ea-854a-e234f209fd88](https://user-images.githubusercontent.com/43391939/74664914-fe0d5700-51e1-11ea-97cd-a9cd22782455.jpg)

1. The caves on the top right and bottom right - overlay covers not properly aligning with the background

the picture below is a cropped image of go_stage18_bg-1.png. I added it here as it shows how the cave looks without any blemish.
![ideal](https://user-images.githubusercontent.com/43391939/74547022-ca86be80-4f8e-11ea-877f-0eafe0e67227.jpg)

2. two Gonzarayas.

**Comment by cigumo** [comment]
these are all hard to fix because of how the covers were created.

**Comment by sunnydaler** [comment]
2 gonzarayas are not cave-related.
