### ISSUE TITLE
swamp thing and goblin sapper keep ranging even very near the exits.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1154]
![20200216080757_1](https://user-images.githubusercontent.com/43391939/74596815-a5ca3e00-5097-11ea-8360-2adebdb47c7c.jpg)
![20200216082053_1](https://user-images.githubusercontent.com/43391939/74596816-a7940180-5097-11ea-92de-9679461cab2e.jpg)

and sapper's bomb is not aimed at the ground. and explodes a little off the ground

**Comment by cigumo** [comment]
- they seem to keep firing in cocos, so I left it as is
- fixed sapper bomb's destination

kr1-4.0.07
