### ISSUE TITLE
low level Archer's sprites are krf's. / ExulantAmruth_2

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1155]
![Pedia_tower_Archer_Tower](https://user-images.githubusercontent.com/43391939/74598212-bd61f080-50b0-11ea-9740-2e22a69086cd.png)

![Pedia_tower_Marksmen_Tower](https://user-images.githubusercontent.com/43391939/74608524-0ce20400-5125-11ea-9971-681381e94b84.png)
![Pedia_tower_Sharpshooter_Tower](https://user-images.githubusercontent.com/43391939/74608526-11a6b800-5125-11ea-8d5a-5e41703fefdd.png)

![20200216113754_1](https://user-images.githubusercontent.com/43391939/74598221-f8642400-50b0-11ea-9c65-1dc14c4e4a13.jpg)

level 1~3 archers

**Comment by cigumo** [comment]
fixed in kr1-4.0.07
