### ISSUE TITLE
Gloomy - bounty and damage 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1160]
![Origins_2020-02-17-03-54-25](https://user-images.githubusercontent.com/43391939/74610842-29d50200-513a-11ea-9ad3-50ac848bc739.jpg)
![Origins_2020-02-17-04-00-51](https://user-images.githubusercontent.com/43391939/74610845-2fcae300-513a-11ea-894e-eb9615e0f13c.jpg)

![20200217040222_1](https://user-images.githubusercontent.com/43391939/74610869-5f79eb00-513a-11ea-835e-ce8174114059.jpg)

- [x] change its damage value to "None" on info bar.
It is "none" on Steam encyclopedia.

- [x] its copy gives gold in love.

**Comment by cigumo** [comment]
fixed in 4.2.10
