### ISSUE TITLE
Localization error rusian version

### ISSUE THREAD

**Issue by victoriadelima** [cigumo/krli#1162]
![image-16-02-20-02-06-1 (1)](https://user-images.githubusercontent.com/49003944/74655957-088d0980-516c-11ea-9e13-3fd6289e4594.jpeg)

should change world «стороны» on «стороне»

**Comment by cigumo** [comment]
this is the ipad ui... should check if we have not changed it already in love

**Comment by cigumo** [comment]
fixed for desktop version. phone is different.
