### ISSUE TITLE
Wrong enemy information

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1164]
- [x] Black Hag:  Encyclopedia writes "none" for its magic resistance. It should be "high".

![20200218000902_1](https://user-images.githubusercontent.com/43391939/74665726-935d1b00-51e3-11ea-87d0-1e804b79f6f3.jpg)

- [x] Black Hag: Change magic resistance to "high" on its enemy card.
![20200218000609_1](https://user-images.githubusercontent.com/43391939/74666140-53e2fe80-51e4-11ea-97d5-d4212beec752.jpg)

- [x] Black Hag: Replace "2 sec" with a life count on the info bar. Also, display High magic resistance.
![20200218000623_1](https://user-images.githubusercontent.com/43391939/74665739-96f0a200-51e3-11ea-8615-8a091d689e94.jpg)

- [x] Worg Rider: Change the magic resistance to "high" on its enemy card.
![20200218073325_1](https://user-images.githubusercontent.com/43391939/74690078-0638b700-5221-11ea-87cc-5c3db027c71a.jpg)

- [x] Noxious Creeper: Change the magic resistance to "medium" on its enemy card.
![20200217234557_1](https://user-images.githubusercontent.com/43391939/74663833-e634d380-51df-11ea-9f97-71bbe8e8fd2d.jpg)

- [x] Demon Spawn: Demon Lord's picture is used on its enemy card. Change the picture with the right one.
![74661964-580b1e00-51dc-11ea-916f-8d7d716c1b63](https://user-images.githubusercontent.com/43391939/74665474-277ab280-51e3-11ea-96f5-d8fcce0aa2bb.jpg)

- [x] Gargoyle: Change the damage value 0-0 to "None" on the info bar.
![74663037-60fcef00-51de-11ea-9947-d27a69e1e589](https://user-images.githubusercontent.com/43391939/74670238-16826f00-51ec-11ea-9ce8-899afd51048d.jpg)

**Comment by cigumo** [comment]
fixed in kr1-4.0.07
