### ISSUE TITLE
Enemy regeneration

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1167]
- [x] Forest Troll, Troll, Troll Axethrower, Troll Breaker, Troll Pathfinder stop regenerating when stunned (by Malik or Thor) in love.  (Werewolf and Lycan are fine in love.)

- [x] the regen of Forest Troll and Troll Breaker seems to have rounding errors. they sometimes heal 2 HP per 3 frames (not 2 frames) in love @30fps. 

![capture](https://user-images.githubusercontent.com/43391939/74693270-67b35280-522e-11ea-94b7-fe8694898eee.JPG)
the fix that was done for ogre magi might also fix the regen of Forest Troll and Troll Breaker.
currently it is set to 2 HP per 2 frames but 6 HP per 6 frames may work better in case fps drops.

-------------------------------------------------------------------------
other enemies' regen amounts are fine. the same on both platforms.
Troll: 1 HP per 6 frames
Troll Axethrower: 2 HP per 6 frames
Troll Chieftain: 4 HP per 6 frames

**Comment by cigumo** [comment]
changed it to 4HP every 4 frames and fixed the rounding errors. 
kr1-4.0.07
