### ISSUE TITLE
Arcane Wizard, Tesla and Thor modifier damage rounding

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1168]
- [x] Arcane Wizard
listed damage values: 76-140 (with dmg upgrade, 88-161)
on love, arcane goes 9 ticks. And sometimes 8 ticks. 
on cocos, it goes 10 ticks dealing (7 to 14) *10 damage in total.
on unity, it goes 11 ticks; (7 to 14) *11.

- [x] Tesla
listed damage values: 60-110 (with dmg upgrade, 66-121)
on love, tesla deals (9 to 15) *7  and (10 to 17) *7 with Concentrated Fire upgrade.

- [x] Thor

**Comment by cigumo** [comment]
fixed in kr1-4.0.07
