### ISSUE TITLE
Tesla doesn't predict incoming enemies.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1169]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43391939/74751722-084a5680-52b1-11ea-876b-d1c1b6c1c923.gif)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43391939/74751253-54e16200-52b0-11ea-86b7-ea98be062867.gif)
dwarf engineers don't start working until enemies get inside the range, unlike cocos.

**Comment by cigumo** [comment]
fixed in kr1-4.0.07
