### ISSUE TITLE
enemy HP bar size or height

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1170]
- [ ] Abomination. It is longer than in kr1 cocos and krf love.
![20200219010707_1](https://user-images.githubusercontent.com/43391939/74754357-d76c2080-52b4-11ea-870f-5aec832575c3.jpg)

- [x] Sarelgaz. low.
![20200219012543_1](https://user-images.githubusercontent.com/43391939/74755744-f075d100-52b6-11ea-9279-ac382038f832.jpg)

- [ ] Demon Vez'nan. small.
![20200219012932_1](https://user-images.githubusercontent.com/43391939/74756063-5cf0d000-52b7-11ea-806f-9b0d453cd0f3.jpg)

**Comment by cigumo** [comment]
changed in kr1-4.0.07:
- abomination: made it a little shorter but still bigger than cocos. 
- sarelgaz: higher
- veznan demon: hacked to enlarge it for the demon and moved it lower
