### ISSUE TITLE
missile explosion striking ground targets

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1171]
The same explosion for artillery bombs is used for missiles that hit ground targets. Thus, it looks like exploding behind the target with some offset to the y-axis.
The following explosion in the picture would look better for ground explosion of missiles (like Wilbur's).
![20200219021626_1](https://user-images.githubusercontent.com/43391939/74761194-f40d5600-52be-11ea-87f9-086b8788e341.jpg)

- [x] kr1 Dragonbreath missile
![20200219020444_1](https://user-images.githubusercontent.com/43391939/74759599-5dd83080-52bc-11ea-875b-edf31461bede.jpg)

- [x] kr1 Juggernaut missile

![20200219020848_1](https://user-images.githubusercontent.com/43391939/74759869-cfb07a00-52bc-11ea-9400-02c97a22e1c2.jpg)

- [x] kr2 wasp missile
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/43391939/74762658-9f1f0f00-52c1-11ea-84de-afe1175b442f.gif)

**Comment by cigumo** [comment]
changed all explosions to air ones and put them on the Z_EFFECTS layer
could make trouble with some object covers
kr1-4.0.07
