### ISSUE TITLE
Gul'Thak turns its back

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1172]
https://cdn.discordapp.com/attachments/567811170342535188/679369005148012573/GulThak.mp4
![2020_02_19_01_42_08_351_new - 3572](https://user-images.githubusercontent.com/43391939/74763411-20c36c80-52c3-11ea-8e0a-4c6f485c6e04.jpg)

**Comment by cigumo** [comment]
fixed in kr1-4.0.07
