### ISSUE TITLE
game end comics

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1173]
![end comic1](https://user-images.githubusercontent.com/43391939/74886007-5434f280-53ba-11ea-8ab2-80e27639e2d8.jpg)

- [ ]  font is too big and bold?

1. some phrases are touching speech bubbles.
2. "AAAAH" - line break - "!"

- [ ] Big Bad Bug: "Yajuuu" is a Spanish thing. In English it should be "Yahoo"

**Comment by cigumo** [comment]
fixed some bubbles but won't change YAJUU! :)
kr1-4.0.07
