### ISSUE TITLE
Wave icon

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1174]
- [x] In Ancient Necropolis campaign, the south spawn point is missing wave icons for wave 9, 12, 15.
Also, missing icons for heroic wave 2, 4, 5, 6. 
![9](https://user-images.githubusercontent.com/43391939/74893071-c6173700-53ce-11ea-9056-1b4df26f6753.jpg)
![12](https://user-images.githubusercontent.com/43391939/74893075-c8799100-53ce-11ea-99a8-c22be991e500.jpg)
![15](https://user-images.githubusercontent.com/43391939/74893076-c9aabe00-53ce-11ea-9432-e389aa3c1a8b.jpg)

- [x] in Twin River Pass,  icons on the bottom are placed low. In unity, they are placed a bit higher so as not to be covered up by info bars.
![20200220095229_1](https://user-images.githubusercontent.com/43391939/74890972-f956c780-53c8-11ea-968e-b215df60c336.jpg)

- [x]  In Silveroak Forest, the icons on the right are over the trees. Also, the wave icons at the bottom are placed a bit low.

Love
![20200220092102_1](https://user-images.githubusercontent.com/43391939/74888993-f9ec5f80-53c2-11ea-8672-7b148689fb81.jpg)

Unity
![unity](https://user-images.githubusercontent.com/43391939/74888976-efca6100-53c2-11ea-97d7-db3e249bc052.jpg)

**Comment by cigumo** [comment]
fixed in kr1-4.0.07
