### ISSUE TITLE
Rangers Hideout - Poison Arrow targeting

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1175]
in cocos, Rangers Hideout upgraded with Poison Arrows prioritizes enemies which are not immune to poison but are not currently poisoned. Rangers spread poison by targeting susceptible enemies first. https://i.imgur.com/TNgYW3O.mp4

in love, Rangers Hideout upgraded with Poison Arrows targets doesn't prioritizes poison-susceptible targets. And the tower keeps shooting at skeletons, magma elementals, and husks at the front line, as if not knowing which ones are immune to poison. https://i.imgur.com/xkzE0xi.mp4

**Comment by cigumo** [comment]
fixed in kr1-4.0.07
