### ISSUE TITLE
Fallen Knight's death spawn

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1179]
- [x] Spectral Knight is vulnerable and can be blocked while it spawns from the defeated fallen knight.

https://cdn.discordapp.com/attachments/567811170342535188/682010336924401743/2020_02_26_08_43_46_838_new.mp4
![2020_02_26_08_18_17_96_new - 1542](https://user-images.githubusercontent.com/43391939/75297338-f6e5e900-5872-11ea-9fd1-ef859e59b36d.jpg)

- [ ] there's a blink when unit is replaced.
![1](https://user-images.githubusercontent.com/43391939/75298130-ffd7ba00-5874-11ea-8059-197a4660d4ed.jpg)

**Comment by mglgmz** [comment]
Couldn't reproduce blink

**Comment by cigumo** [comment]
reverted the previous general fix and made a specific fix for the spectral knight. 
kr1-4.0.08
