### ISSUE TITLE
Cerberus can be instakilled but not slowed

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1180]
- [x] Permafrost and Tar Bomb should slow it.

- [x] The helldog still can be instakilled

**Comment by sunnydaler** [comment]
see this cocos video. the dog is slowed down by permafrost.
https://cdn.discordapp.com/attachments/567811170342535188/682044371226722338/Kingdom_Rush_2020-02-26-10-56-54_new.mp4

**Comment by cigumo** [comment]
cerberus can be slowed by tarbomb and permafrots but not mage's slow curse
fixed in kr1-4.0.08
