### ISSUE TITLE
wave flags for wave 15 are swapped in Pit of Fire

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1181]
![20200226113747_1](https://user-images.githubusercontent.com/43391939/75306577-cf9c1580-588c-11ea-8ca2-6b2bf9b03e69.jpg)

it should be
(Demon Lord x 5, Flareon x 24) on the left
(Demon Legion x 4, Demon Lord x 8) on the right.

**Comment by cigumo** [comment]
fixed in kr1-4.0.08
