### ISSUE TITLE
Blackburn stuns soldiers that are on the move

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1182]
1. hero can move when the lord shakes the ground but the stun effect comes into play once they stop moving. and stun mod (those stars) is always on display for soldiers in its range.
https://cdn.discordapp.com/attachments/567811170342535188/682076826964983820/2020_02_26_13_07_56_400_new.mp4

2. barracks soldiers get stunned while changing rally.
https://cdn.discordapp.com/attachments/567811170342535188/682077474728968192/2020_02_26_13_10_34_480_new.mp4

**Comment by cigumo** [comment]
fixed in kr1-4.0.08
