### ISSUE TITLE
Gerald's dodge

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1184]
https://cdn.discordapp.com/attachments/567811170342535188/682340599462232105/2020_02_27_06_32_53_984_new1.mp4

- [x] double dodge. watch the video.

- [x] against a few enemies,  Gerald visually dodges before or after the attacker's strike. 
Too early on Ogre, Troll Chieftain
A bit late on Bandit, Shadow Archer, Orc Champion, Orc

- [x] Should Bandit and canines dodge Shield of Retribution? I saw Bandit and Worg dodge it in love.

- [x] chance seems to be still 20/40/60 % on Gul'Thak and Myconid.

**Comment by cigumo** [comment]
fixed in kr1-4.0.08

**Comment by cigumo** [comment]
double dodge animation still happening

![Kingdom_Rush_2020-04-08-08-11-34_new mp4](https://user-images.githubusercontent.com/934821/78728651-4574b180-790e-11ea-87c4-05c95e32daad.gif)

**Comment by sunnydaler** [comment]
https://streamable.com/mnf3r7
Dodge chance against attacks from Gul'Thak and Myconid is still high in 4.0.14. Not lowered?

**Comment by cigumo** [comment]
fixed gerald lower chance for gulthak and other bosses in kr1-4.2.00
