### ISSUE TITLE
upgrades and towers' damage

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1185]
- [x] Empowered Magic is not applied to level 2 mage. Damage is still 23-43.

- [x] with Empowered Magic upgrade, level 3 mage's damage is higher than in cocos.
46-86 in cocos, and 53-99 in love.

- [x] with Concentrated Fire upgrade, level 1 artillery's damage is lower than in cocos.
9-17 in cocos, and 8-16 in love.

**Comment by cigumo** [comment]
fixed in kr1-4.0.08
