### ISSUE TITLE
Arcane vfx 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1187]
![arcane](https://user-images.githubusercontent.com/43391939/75319902-dc326500-58b0-11ea-93b7-30dd91543598.png) by vfx, i mean this sprite.
When multiple arcanes attack a single enemy, This vfx appears only on the preceding arcane attack. Not on preceeding attacks of the other arcanes.

https://cdn.discordapp.com/attachments/567811170342535188/682118809053560843/2020_02_26_15_36_15_717_new.mp4

**Comment by cigumo** [comment]
see if it can be solved by setting ```modifier.resets_same = true ``` to the modifier

**Comment by cigumo** [comment]
fixed in kr1-4.0.08
