### ISSUE TITLE
Credits - Korean

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1188]
![20200226080426_1](https://user-images.githubusercontent.com/43391939/75373622-f77f8d80-590d-11ea-8992-437e63a0ee6c.jpg)
1. O-umlaut is X-boxed.
2. replace 생산 with 제작 (same in krf and kro)
3. Community Manager -> 커뮤니티 매니저 (Note: I chose the word that is used in krv credit)

**Comment by cigumo** [comment]
fixed in kr1-4.0.08
