### ISSUE TITLE
Korean localization

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1189]
- [x] hero unlock condition
"Unlocks at stage x"
스테이지 x 에 개방 --> 
스테이지 x에서 개방 (krf and kro also need to be fixed.)
Note: 에서 is a particle that expresses a location where an action is taking place.

- [x] Alleria skill name
"Call of the Wind"
야성의 마력 --> 
야성의 부름
Note: There is a short novel titled "The Call of the Wild" by Jack London, published in 1903. I used its Korean title here.

- [x] Malik skill name
"Hammer Smash"
망치 휘두르기 --> 
망치 내려치기

- [x] Malik bio excerpt 
"A destructive force, an unleashed fury, a bullet train attitude!"
파괴적인 힘을 휘두르고 분노를 표출하며 총알처럼 빠릅니다!" --> 
파괴적인 힘, 고삐 풀린 분노, 거침없는 성격의 그입니다!

- [x] Gerald Lightseeker hero name
Sir Gerald (in game):
제랄드 경  --> 제럴드 경
Sir. Gerald Lightseeker (in the hero room):
제랄드 경 --> 제럴드 라이트시커
Note: 제럴드 is gerald's KRV name which i find better.

- [x] Gerald hero description
"Defender of the righteous, punisher of the dark, protector of the innocent, crusher of evil beings, Gerald Lightseeker is the uncanny of Linirea's armed forces!"
일명 "정의의 수호자", "어둠을 심판하는 자", "무고한 이들의 지킴이", "악을 처단하는 자"인 제랄드 라이트시커는 리니리아의 특별한 영웅입니다! -->
일명 정의의 수호자, 어둠을 심판하는 자, 무고한 이들의 지킴이, 악을 처단하는 자인 제럴드 라이트시커는 리니리아의 특별한 영웅입니다!

- [x] Ingvar Bearclaw hero name
잉그바르 베어클로 --> 잉바르 베어클로

- [x] Ingvar skill name
"Ancestor Call"
선조의 부름  -->
선조 소환

- [x] Hacksaw skill name
"Tiiimber!" (A warning for tree fall)
쓰러져라아아아! --> 
쓰러진다~! or 쓰러진다아아아! 
Note: 쓰러져라 is imperative and 쓰러진다 is declarative.

- [x] Magnus bio
"Unleash the arcane forces of Linirea, let loose a mystical storm, and spellbind your enemies! With his arcane arts and thirst for knowledge."
비전술과 지식에 대한 갈망에 힘입은 리니리아가 비전의 힘을 방출해, 신비로운 폭풍을 일으키고 적들의 마법을 구속합니다. --> 
지식에 대한 목마름과 비전술로 마력을 발휘해 신비로운 폭풍을 일으키고 적들에게 마법을 겁니다!

- [x] King Denas bio excerpt 
"Long live the king!"
왕이여, 만수무강하소서!  --> 
국왕 만세!

- [x] Arcane Wizard tower name
비전 타워 --> 
비전 마법사
Note: The tower is called "비전 마법사" in the description. As shown in the following.

- [x] Arcane Wizard description
"Arcane Wizards focus on altering reality, as well as shooting the deadliest magical ray known to man."
비전 마법사는 현실을 조작하고 무시무시한 마법 광선을 발사합니다. -->
비전 마법사는 인간에게 알려진 가장 치명적인 마법 광선을 발사하고 현실을 왜곡합니다.

- [x] Musketeer Garrison tower name
소총병 초소 (Rifleman Post) --> 
총사대 (Musketeers) 
Note: In Coldstep Mines stage description, "a brigade of His Majesty's Royal Musketeers" was translated to 국왕 폐하의 왕실 총사대. 
국왕 폐하의(His majesty's)  왕실(Royal)  총사(Musketeer) -대(troops, forces)
In the game Civilization 5, Musketeers is called 총사대 in Korean.

- [x] Improved Deployment upgrade description
"Improves rally point range and reduces soldier training time."
집결 지점의 범위가 길어지고 병사의 훈련 기간이 단축됩니다. -->
병사 집결지의 범위가 넓어지고 병사의 훈련 기간이 단축됩니다. 
Note: 길어지다 is to lengthen, and 넓어지다 is to widen.

- [x] Spell Reach upgrade description
"Increases wizard's attack range."
마법사의 사정거리가 늘어합니다. -->
마법사의 사정거리가 늘어납니다.
Note: 합 is a typo.

- [x] Precision upgrade description
"Marksmen attacks have a chance of dealing double damage."
화살이 일정 확률로 두 배의 피해를 줍니다. -->
사격이 일정 확률로 두 배의 피해를 줍니다.
Note: 화살 means arrow. I chose the word 사격 to encompass both arrow and bullet.

- [x] Far Shots upgrade description
"Increases marksmen attack range."
궁수의 사정거리가 넓어집니다. -->
사격의 사정거리가 늘어납니다.

- [x] Piercing Shots upgrade description
"Piercing shots ignore a portion of the enemy physical armor."
화살이 물리 방어력을 일정량 무시합니다. -->
관통 사격이 적의 물리 방어력을 일부 무시합니다. 

- [x] Eagle Eye upgrade description
"Increases Marksmen attack range."
궁수의 사정거리가 늘어납니다. -->
사격의 사정거리가 늘어납니다.

- [x] Salvage description 
"Marksmen towers return 90% of value when sold."
궁수 타워를 철거하면 비용의 90%를 돌려받습니다. -->
사격 타워를 처분하면 비용의 90%를 돌려받습니다.

- [x] tip no. 8
"With the Salvage upgrade, you can sell archer towers with only a 10% of loss."
재활용 업그레이드를 하면 10%의 손해만 보고 아처 타워를 처분할 수 있습니다. -->
재활용 업그레이드를 하면 10%의 손해만 보고 사격 타워를 처분할 수 있습니다. 

- [x] new tower cards for level 4 marksman towers
![20200301122954_1](https://user-images.githubusercontent.com/43391939/75619031-a4316780-5bb9-11ea-9e86-9b506daa307f.jpg)
레벨 4 궁수 타워 -->
레벨 4 사격 타워

- [x] Sylvan Elf tower name and description
"Sylvan Elf": 실바 엘프 --> 숲의 엘프

Before repair: 
"This elven building was once a training hall of Sylvan Elf Warriors."
이 엘프 건물은 한 때 실바 엘프들의 훈련소로 쓰였습니다. -->
이 엘프 건물은 한 때 숲의 엘프 전사들의 훈련소로 쓰였습니다.

After repair:
"Sylvan Elves are masters of bow and blade. They will join your cause... for a price.
실바 엘프들은 활과 칼의 달인이며... 대가를 주면 함께 싸워줄 것입니다. -->
활과 검의 고수인 숲의 엘프들은 대가를 주면 함께 싸워줄 것입니다.

- [x] "Imperial Savier" achievement description
"Complete The Citadel with at least 3 imperial guards."
제국 수호병 3명 이상이 살아남은 상태로 시타델을 완료하세요. -->
제국 수호병이 셋 이상이 살아남은 상태로 성채를 완료하세요. 
Note: 시타델 is a Romanization of the word Citadel. and 성채 is the name of the corresponding level. 

- [x] This is the end! achievement description.
The sentence is missing a period (.)

- [x] Spore achievement description
"Kill 25 Shrooms without them poisoning your soldiers."
아군 병사를 중독시키지 않은 버섯 25마리를 처치하세요. -->
아군 병사를 중독시키지 않고 버섯 25마리를 처치하세요.

- [x] Gulaemon name
괄레몬 --> 탐식마
Note: 괄레몬 is awkward romanization of the word gulaemon. Considering that "gula" means "gluttony (탐식)" in Latin, I think 탐식(gluttony)+마(evil, devil) is a better translation. 탐식마(贪食魔) is also Chinese name of the enemy.

- [x] Demon Lord name
악마 부대장 --> 악마 군주
Note: 부대장 means "section leader", and 군주 means "lord". 

- [x] Marauder enemy name
전투분대장 (battle squad leader) --> 약탈범

- [x] Pandaemonium description excerpts
"We face Moloch, one of the Great Demon Lords."
우리는 강력한 악마 부대장 중 하나인 몰로크를 상대하게 되었습니다. --> 
우리는 위대한 악마 군주 중 하나인 몰로크를 상대하게 되었습니다. 

- [x] Pillager name
지옥칼 대장 ---> 강탈범
Note: 범 is a suffix noun that has a meaning of "criminal"
spectral pillager was translated 유령 강탈자 in Hearth Stone. 

- [x] Husk enemy name
숲 좀비 (forest zombie) -->
껍데기
Note: I took it from a famous poem titled 껍데기는 가라 (Husk, be gone) by Shin Dong-yup.

- [x] range category name "Extreme"
최장거리 --> 초장거리 
Note: 최 is a superlative suffix to nouns. 
 Change  kro's Golden Longbows range, too.

- [x] level 1 Archer Tower description
"Archers ready to strike at your enemies from a distance."
궁수들은 멀리서 적들을 사냥하도록 대기합니다. -->
멀리서 적들을 쏠 준비가 된 궁수들입니다.
Note: Change krf's level 1 archer tower description, too.

**Comment by cigumo** [comment]
- don't have yet different names for heroes in heroroom (except for english, where the original text images are kept), so can't use this for the moment:  Sir. Gerald Lightseeker (in the hero room):
제랄드 경 --> 제럴드 라이트시커

**Comment by cigumo** [comment]
fixed in kr1-4.0.08
