### ISSUE TITLE
Armored enemy tip card

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1190]
- [x] kro's text is used. Stone Druids!

![20200227215322_1](https://user-images.githubusercontent.com/43391939/75447011-d5d4e380-59ab-11ea-9d90-600bf9e0a95f.jpg)

- [x]  Partially localized.
![20200227155119_1](https://user-images.githubusercontent.com/43391939/75420118-9fcb3b80-597a-11ea-91bc-ff6813e52270.jpg)

**Comment by cigumo** [comment]
fixed in kr1-4.0.08
