### ISSUE TITLE
Sunray tower button is not grayed out when maxed

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1192]
gray out the sorcerer icon when maxed.
![20200229014301_1](https://user-images.githubusercontent.com/43391939/75568283-51ab5a80-5a96-11ea-8528-cfb074448ed6.jpg)

**Comment by cigumo** [comment]
actually it's consistent with the way tower power upgrades buttons stay when complete. 
<img width="199" alt="Screen Shot 2020-03-10 at 10 25 05 PM" src="https://user-images.githubusercontent.com/934821/76373006-0575db00-631e-11ea-8ca9-31c60d77fbf6.png">
