### ISSUE TITLE
Crash on survival mode

### ISSUE THREAD

**Issue by victoriadelima** [cigumo/krli#1193]
the game crashes after 5-10 minutes of playing on survival mode and the user gets a blue screen:

![Screenshot_20200227_093532_com ironhidegames android kingdomrushorigins](https://user-images.githubusercontent.com/49003944/75581479-5812e580-5a48-11ea-8635-3abe2cf23567.jpg)

Huawei p30 lite
Emui 9.1.0

ticket:
http://support.ironhidegames.com/a/tickets/61224

**Comment by cigumo** [comment]
I believe it should be fixed in 7deb1c13dea0226792debd0cbee0f58d9f74d5c0
Requires update to google play release, which will be 4.2.09 or later.

**Comment by cigumo** [comment]
moved to #836
