### ISSUE TITLE
tesla and arcane abort attack

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1196]
On cocos and unity, once attack animation has started while a target was within the tower range, the ray still hits the enemy even if the enemy gets out of the range. Like archers and other artilleries do.

Love
https://cdn.discordapp.com/attachments/567811170342535188/683065830145130557/2020_02_29_06_37_11_0_new.mp4

cocos arcane
https://cdn.discordapp.com/attachments/567811170342535188/683077183924863031/cocos_arcane.mp4

cocos tesla
https://cdn.discordapp.com/attachments/567811170342535188/683077186516942886/cocos_tesla.mp4

**Comment by cigumo** [comment]
I've made some changes, so it should be much better now, but it will still interrupt a shot if the enemy goes out of range. 
kr1-4.0.08

**Comment by sunnydaler** [comment]
kr1-4.0.11
tesla calls it a quit even if the target stays in the range long enough for the next attack.
https://cdn.discordapp.com/attachments/567811170342535188/693824035217211473/2020_03_29_23_06_53_47_new.mp4
In this clip, the first chain hits the target on the frame 27, and the next attack is expected to hit the target on the frame 95. but the tower aborts even if the target remains in range until the frame 122.

**Comment by cigumo** [comment]
fixed in kr1-4.0.12
