### ISSUE TITLE
DWAARP core drill 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1198]
DWAARP attacks faster if the drill skill is ready (off the cooldown) and only drill-immune enemies (Bloodshell,  Ghost, Phantom  Warrior, bosses) are in the range. During this time, Furnace Blast doesnt recharge. 
https://streamable.com/01jp4f

**Comment by cigumo** [comment]
https://streamable.com/qcg8vn

**Comment by cigumo** [comment]
fixed in 4.2.29
