### ISSUE TITLE
Green Warden upgrade for Reinforcements spell doesn't change Reinforcements appearance / Dri

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#120]
Green Warden upgrade for Reinforcements spell doesn't change Reinforcements appearance to that of the Green Wardens. Only when taking the Rapid Response Star upgrade does the sprite change to that of the Green Warden. So, the trigger for the appearance change should be moved down to the actual Green Wardens upgrade.

**Comment by sunnydaler** [comment]
Yes, dri is right.

**Comment by cigumo** [comment]
fixed
