### ISSUE TITLE
first map stage flagpole animation hidden by difficulty selection view

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1211]
when u play on a new slot on mobile,
difficulty selection menu opens. And after the difficulty is selected, the flagpole is fixed on the 1st stage of the worldmap.

On steam and switch, the first stage flagpole fixing animation plays automatically behind the difficulty selection menu. It should play after the difficulty menu is closed.

**Comment by cigumo** [comment]
fixed in kr1-4.0.08
