### ISSUE TITLE
Remove the dots between "Dark Tower" and "Rift of Cinder"

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1214]
https://cdn.discordapp.com/attachments/567811170342535188/684902858750951451/after_completing_Level_11_Forsaken_Valley.mp4

https://cdn.discordapp.com/attachments/567811170342535188/684902873703907328/after_completing_Level_12_Dark_Tower.mp4

After completing level 12, the dots that connect "Dark Tower" and "Rift of Cinder" appear out of nowhere. 
I

**Comment by cigumo** [comment]
actually the "path" to stage 12 goes around the mountain :)
fixed in kr1-4.0.08

**Comment by cigumo** [comment]
the dots around the mountain animation is not played
