### ISSUE TITLE
Burning fissure 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1222]
The lava fissures in Pit of Fire and Pandaemonium

- [x] damage area is bigger than in cocos.
![love](https://user-images.githubusercontent.com/43391939/76133669-a2a1ec80-605c-11ea-9742-147f871f739a.jpg)

![VideoCapture_20200307-094448](https://user-images.githubusercontent.com/43391939/76133608-55257f80-605c-11ea-9528-860e29012d3b.jpg)

- [x] on the down right side of Pit of Fire map, there is one more fissure than in cocos.
![2020_03_07_09_32_02_991_new - 2020](https://user-images.githubusercontent.com/43391939/76133634-81410080-605c-11ea-9307-104a48099662.jpg)

**Comment by cigumo** [comment]
fixed in kr1-4.0.08
