### ISSUE TITLE
review Elora skills

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1224]
- [ ] does Permafrost cover more area in love? 
 

- [x] Permafrost - the path is often sparsely covered by decals and it doesn't look pretty. 
![20200308053325_1](https://user-images.githubusercontent.com/43391939/76152036-7474e900-60fe-11ea-907f-19dda47e964a.jpg)

![20200308051734_1](https://user-images.githubusercontent.com/43391939/76151975-c49f7b80-60fd-11ea-98d8-50960d50df10.jpg)

![VideoCapture_20200308-053554](https://user-images.githubusercontent.com/43391939/76152084-d6355300-60fe-11ea-88e1-1bfa6c7cea7b.jpg)
![VideoCapture_20200308-053519](https://user-images.githubusercontent.com/43391939/76152097-f9600280-60fe-11ea-9c8a-c34870a1ad85.jpg)

- [x] Ice Storm doesn't trigger in near range. (min range seems to be bigger than in cocos.)
https://streamable.com/6mjbf

**Comment by mglgmz** [comment]
Permafrost covers more area on non-phone builds.

**Comment by cigumo** [comment]
fixed in kr1-4.0.08:
- spikes spread
- permafrost spread
