### ISSUE TITLE
Hero room barmeter icons

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1250]
Heart and Sword icons are swapped.

![Kingdom Rush_2020-03-24-02-27-11](https://user-images.githubusercontent.com/43391939/77344837-1c351c80-6d77-11ea-86cc-ffdc2733b933.jpg)
![20200324022705_1](https://user-images.githubusercontent.com/43391939/77345005-63231200-6d77-11ea-9287-58e2ed175f61.jpg)

**Comment by cigumo** [comment]
fixed in kr1-desktop-4.0.09
