### ISSUE TITLE
Diedre crash when trying to teleport without the skill trained

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#1251]
> In the sunke citadel map when hero Dierdre is chosen without the teleport skill unlocked; and point her to the other island she becomes stuck in a state that make her basically useless.

**Comment by cigumo** [comment]
![diedre-crash-without-teleport](https://user-images.githubusercontent.com/934821/77347194-3c80bf00-6d16-11ea-92d5-a96885cdfbbe.gif)

**Comment by victoriadelima** [comment]
http://support.ironhidegames.com/a/tickets/61833

**Comment by cigumo** [comment]
fixed in 4.2.24
