### ISSUE TITLE
heroes still attack defeated bosses

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1255]
Magnus rains Arcane Storm
J.T. https://streamable.com/mugxh
Veznan https://streamable.com/d11xg
he rains arcane storm onto the defeated bosses while their death animation plays.
and he summons Shadows during the "dark tower" ending scene as u can hear in the above video.

**Comment by cigumo** [comment]
prevents arcane storm in kr1-desktop-4.0.11
left the shadow summoning anyway.

**Comment by sunnydaler** [comment]
Elora (Ice Storm) and Denas (Catapult Barrage) do the same thing to JT and Veznan.

**Comment by cigumo** [comment]
fixed in kr1-4.0.12
- elora ice storem
- denas catapult
