### ISSUE TITLE
kr1 Unity save game import issues

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#1257]
https://steamcommunity.com/app/246420/discussions/2/1863868161618449791/

> I went Rotwik and Hushwood on 3 stars.
> Now in my profile it shows that I went through the lair of Salazar and the Ruins of Akarot, but I did not pass them.

**Comment by cigumo** [comment]
Ask save file to @victoriadelima . It was sent to the support email.

**Comment by svytbay** [comment]
Archive with [files](https://drive.google.com/file/d/1kEO9n851w1Eay6agunnEHQZnqnXAmDpz/view?usp=sharing)

**Comment by cigumo** [comment]
thanks @svytbay !!

**Comment by cigumo** [comment]
fixed in kr1-desktop-4.0.11
