### ISSUE TITLE
Wrath of Elynie deals 3000 damage multiple times to boss

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1265]
https://streamable.com/t3diq

![VideoCapture_20200326-001338](https://user-images.githubusercontent.com/43391939/77552413-d8692100-6ef6-11ea-9fcf-1269b79781c0.jpg)
![VideoCapture_20200326-001412](https://user-images.githubusercontent.com/43391939/77552414-d901b780-6ef6-11ea-8883-4bf8ad13962e.jpg)
![VideoCapture_20200326-001416](https://user-images.githubusercontent.com/43391939/77552417-d99a4e00-6ef6-11ea-9565-7d2f2411db86.jpg)
![VideoCapture_20200326-001425](https://user-images.githubusercontent.com/43391939/77552408-d737f400-6ef6-11ea-9ada-951f028bd0cd.jpg)
If dropped this item near bosses , it deals damage multiple times.

**Comment by cigumo** [comment]
fixed in 4.2.10
