### ISSUE TITLE
Hero barmeter stats change after playing

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1266]
it happened to Elora and Hacksaw.

one way to reproduce is..

select elora and enter Forsaken Valley
start the battle and restart 3 times
exit to the world map
 check if her sword barmeter in hero room is not 2 bars.

**Comment by cigumo** [comment]
can't reproduce it, mabye fixed with #1260

**Comment by sunnydaler** [comment]
not fixed still.

**Comment by cigumo** [comment]
I still can't reproduce :(

**Comment by cigumo** [comment]
fixed in desktop and console 4.2.12
