### ISSUE TITLE
Icewind Pass tunnel

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#1267]
https://steamcommunity.com/app/246420/discussions/2/2145343189635421056/

> Anyway, there is a bug on icewind pass where minions entering the tunnel just get sent back to the beginning of the level instead of getting sent to the end of the tunnel.

**Comment by cigumo** [comment]
https://streamable.com/5mox0

**Comment by cigumo** [comment]
fixed in kr1-desktop-4.0.11

**Comment by MasterKnightDH** [comment]
Do enemies properly exit out the southwest tunnel in Coldstep Mines? That's worth checking out.
