### ISSUE TITLE
Treants continue to spawn from random spots after Greenmuck's death

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1272]
Rotten Forest
![Screenshot_20200327-211325_Chrome](https://user-images.githubusercontent.com/43391939/77790540-5fa9c680-70a8-11ea-9f02-be4e02d554b5.jpg)

**Comment by cigumo** [comment]
must interrupt s15_rotten_spawner

**Comment by cigumo** [comment]
fixed in kr1-desktop-4.0.12
