### ISSUE TITLE
Denas' aura texture overlaps

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1273]
![2020_03_28_03_23_21_658_new - 21294](https://user-images.githubusercontent.com/43391939/77791899-c5974d80-70aa-11ea-99a6-5c3a834159d2.jpg)
![83c6194e9d78901f13ed40086e0ac7e4](https://user-images.githubusercontent.com/43391939/77792107-1eff7c80-70ab-11ea-8d67-b83690cf6b8d.jpg)

**Comment by cigumo** [comment]
fixed in kr1-4.0.12
