### ISSUE TITLE
Change blood color

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1281]
- [x] Rotshroom and Myconid
In kr1 beta, Myconid bleeds green blood, and Rotshrooms bleed red blood.
Violet would suit the color theme of Fugal Forest stage and the shroom's top.
(In kr3,  shrooms bleed violet blood.)

- [x] Sorcerer's Elemental
In cocos and beta, it bleeds red blood.
Gray would be better suited as a creature made of rock.

**Comment by cigumo** [comment]
fixed in kr1-4.0.12
