### ISSUE TITLE
review crossbow critical chance and falconer

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#1283]
> There is a problem with the special ability of the crossbow fort: falconer. It says it can increase critical chance, but I never actually see it caused any critical hits. There should be a red ‘CRIT’ and deal double damage, like the first version kingdom rush. Is it a bug that the critical hit never appears?

**Comment by sunnydaler** [comment]
https://i.imgur.com/U2kYtVu.mp4
Crit procs on all falconer levels.
What r they talking 'bout?

**Comment by cigumo** [comment]
no idea! will close it
