### ISSUE TITLE
KR3 OOM in Hero Room

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#1287]
> In the role selection interface. When I clicked on another character's avatar, this page appeared.
The game I played was Kingdom Rush Origins purchased on the STEAM platform。My system is windows7, 32-bit system。The error occurred at this step, when I clicked on the avatar of another hero. It has happened twice now. Hope to fix it soon.

- Windows 7
- Steam

![](https://cdn.discordapp.com/attachments/565142610235228172/696796151390928967/QQ202004041757401.png)

**Comment by cigumo** [comment]
Need to know:
- game version
- RAM?
- Video RAM? 
- Graphics card

**Comment by victoriadelima** [comment]
Computer Model Lenovo Qitian M4360-N000 Desktop Computer
  Operating System Windows 7 Ultimate 32-bit SP1 (DirectX 11)

  Processor Intel 3rd Generation Core i5-3470 @ 3.20GHz quad-core
  Motherboard Lenovo MAHOBAY (H61 chipset)
  Graphics Intel Ivy Bridge Graphics Controller (64 MB / Lenovo)
  Memory 8 GB (Hynix DDR3 1600MHz / Kingston DDR3 1600MHz)
  Main hard drive Seagate ST500DM002-1BD142 (500 GB / 7200 rpm)
  Monitor LG GSM4BF2 E1948 (19.1 inches)
  Sound Card Realtek ALC662 @ Intel 6 Series Chipset High Definition Audio
  Network card Realtek RTL8168 / 8111/8112 Gigabit Ethernet Controller / Lenovo

-------- [Motherboard] --------------------------------------- -------------------------------------------

  Motherboard model Lenovo MAHOBAY
  Chipset H61 chipset
  Motherboard version NOK
  BIOS version Lenovo F9KT53AUS / BIOS release date: 04/03/2014
  BIOS size 4096 KB

  Onboard device Video device (enabled)
  Onboard device Ethernet / network card (enabled)
  Onboard device Sound / audio device (enabled)
  Onboard device SATA Controller / SATA controller (enabled)
  Onboard equipment Other (enabled)

-------- [Processor] -------------------------------------- ------------------------------------------

  Processor Intel 3rd Generation Core i5-3470 @ 3.20GHz quad-core
  Step E1
  Speed ​​3.20 GHz (100 MHz x 32.0)
  Number of processors Number of cores: 4 / Number of threads: 4
  Core code Ivy Bridge
  Production process 22 nm
  Socket H2 (LGA 1155)
  Level 1 data cache 2 x 32 KB, 8-Way, 64 byte lines
  Level 1 code cache 2 x 32 KB, 8-Way, 64 byte lines
  L2 cache 2 x 256 KB, 8-Way, 64 byte lines
  Level 3 cache 6 MB, 12-Way, 64 byte lines
  Features MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, EM64T, EIST, Turbo Boost

-------- [HDD] --------------------------------------- -------------------------------------------

  Product Seagate ST500DM002-1BD142
  500 GB
  Speed ​​7200 rpm
  Cache 16 MB
  The hard drive has been used a total of 456 times, a total of 4830 hours
  Firmware KC66
  Interface SATA II
  Data transfer rate 600.00 MB / s
  Features S.M.A.R.T, 48-bit LBA, NCQ

--------[ RAM]--------------------------------------- -------------------------------------------

  ChannelA-DIMM0 Hynix DDR3 1600MHz 4GB
  Manufacturing date 2013 44 weeks
  Model AD HMT351U6CFR8C-PB
  Serial number 36106578
  Manufacturer Hynix
  Module bit width: 64 Bits
  Module voltage: SSTL 1.5V

  ChannelB-DIMM0 Kingston DDR3 1600MHz 4GB
  Manufacturing date 2014 28 weeks
  Model 7F98 99P5474-013.A00LF
  Serial number 2D1BCA38
  Manufacturer Kingston
  Module bit width: 64 Bits
  Module voltage: SSTL 1.5V

-------- [graphics card] --------------------------------------- -------------------------------------------

  Main Graphics Intel Ivy Bridge Graphics Controller
  Video memory 64 MB
  Manufacturer Lenovo
  Manufacturer Intel
  BIOS version Intel Video BIOS
  BIOS date 09/07/20 (non-graphics card manufacturing date)
  Driver version 8.15.10.2696
  Drive Date 3-19-2012

-------- [Display] --------------------------------------- -----------------------------------------

  Product LG GSM4BF2 E1948
  Manufacturer LG
  Firmware program date 5 weeks 2011 (non-display manufacturing date)
  Screen size 19.1 inches (41 cm x 26 cm)
  Aspect ratio widescreen 16: 10
  Resolution 1440 x 900 32-bit true color
  Gamma 2.20
  Power management Standby, Suspend, Active-Off

--------[ other devices]-------------------------------------- ----------------------------------------


  NIC Realtek RTL8168 / 8111/8112 Gigabit Ethernet Controller
  Manufacturer Lenovo

  Sound Card Realtek ALC662 @ Intel 6 Series Chipset High Definition Audio

  Keyboard HID standard keyboard
  Mouse HID-compliant mouse

  Camera Microsoft WDM Image Capture (Win32)

-------- [PCI device] -------------------------------------- -----------------------------------------

  Device Ivy Bridge DRAM Controller
  Device ID 0150
  Manufacturer Intel
  Manufacturer ID 8086
  Category Bridge / PCI to HOST
  Subsystem manufacturer Lenovo
  Subsystem ID 306517AA

  Device Ivy Bridge Graphics Controller
  Device ID 0152
  Manufacturer Intel
  Manufacturer ID 8086
  Category Display / VGA
  Subsystem manufacturer Lenovo
  Subsystem ID 306517AA

  Equipment 6 Series / C200 Series Management Engine Interface
  Device ID 1C3A
  Manufacturer Intel
  Manufacturer ID 8086
  Category Simple Communication / Other
  Subsystem manufacturer Lenovo
  Subsystem ID 306517AA

  Device 6 Series / C200 Series Chipset USB Enhanced Host Controller
  Device ID 1C2D
  Manufacturer Intel
  Manufacturer ID 8086
  Category Serial / USB 2.0 (EHCI)
  Subsystem manufacturer Lenovo
  Subsystem ID 306517AA

  Device 6 Series Chipset HD Audio Controller
  Device ID 1C20
  Manufacturer Intel
  Manufacturer ID 8086
  Category Multimedia / Hi-definition Audio
  Subsystem manufacturer Lenovo
  Subsystem ID 306517AA

  Device 6 Series / C200 Series Chipset PCI Express Ro

**Comment by victoriadelima** [comment]
the game version is ver.kr3-desktop-1.4.8。♪(＾∀＾●)ﾉ

**Comment by victoriadelima** [comment]
http://support.ironhidegames.com/a/tickets/62328

**Comment by cigumo** [comment]
@victoriadelima the issue is basically what it says: Out of memory. 
It should be fixed by running fewer applications in the computer.
