### ISSUE TITLE
kr1-phone import issues

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#1290]
- [ ] towers not unlocked
- [ ] not all enemies unlocked

![](https://cdn.discordapp.com/attachments/567811170342535188/697191845444190278/Kingdom_Rush_2020-04-08-06-11-07.jpg)

![](https://cdn.discordapp.com/attachments/567811170342535188/697192671810289874/Kingdom_Rush_2020-04-08-06-13-12.jpg)

![](https://cdn.discordapp.com/attachments/567811170342535188/697192672087244830/Kingdom_Rush_2020-04-08-06-11-16.jpg)

![](https://cdn.discordapp.com/attachments/567811170342535188/697192672536035508/Kingdom_Rush_2020-04-08-06-12-54.jpg)

![](https://cdn.discordapp.com/attachments/567811170342535188/697192672863060079/Kingdom_Rush_2020-04-08-06-12-59.jpg)

![](https://cdn.discordapp.com/attachments/567811170342535188/697192673140015114/Kingdom_Rush_2020-04-08-06-13-02.jpg)

**Comment by sunnydaler** [comment]
Lvl 4 tower icons are not unlocked in encyclopedia even after building them on stages.

**Comment by cigumo** [comment]
fixed in kr1-phone-4.0.14
