### ISSUE TITLE
kr1 endless miniboss is vulnerable to sniper shot

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1293]
![Kingdom Rush_2020-04-08-09-24-40_new - 634](https://user-images.githubusercontent.com/43391939/78734454-4c89d700-7983-11ea-9b57-c6cdfaef3e5f.jpg)

check hacksaw's drill and oni's death strike on this enemy.

**Comment by cigumo** [comment]
fixed in kr1-4.0.14
