### ISSUE TITLE
Sylvan Elf

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1303]
![Kingdom Rush_2020-04-11-04-21-50](https://user-images.githubusercontent.com/43391939/79022114-2f8a1980-7bb8-11ea-9aa1-e027c5695379.jpg)
![Kingdom Rush_2020-04-11-04-21-50 fix](https://user-images.githubusercontent.com/43391939/79022116-3022b000-7bb8-11ea-843e-45fd499d8f77.jpg)

remove rally range of the unrepaired building.

remove stat in the Repair balloon (reason: redundant as stat is already shown on the info bar)

change the info bar name from "repair" to "sylvan elf" (reason: building's name cant be "repair")

============

Unity
![Screenshot_20200411-041826_YouTube](https://user-images.githubusercontent.com/43391939/79022848-d6bb8080-7bb9-11ea-917a-eb3d45c55d5f.jpg)

cocos 
![Screenshot_20200411-044235_YouTube](https://user-images.githubusercontent.com/43391939/79022861-df13bb80-7bb9-11ea-8173-6d9342ad8a12.jpg)

**Comment by cigumo** [comment]
In kr1-4.0.15: 
- Changed the "Repair" label
- Changed the respawn time from 3 to -
- Left the tooltip stats because it would require major changes in the UI.
