### ISSUE TITLE
Lycan portrait 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1307]
![Kingdom Rush_2020-04-14-00-27-57](https://user-images.githubusercontent.com/43391939/79133548-2d59d200-7de7-11ea-9de1-acb6f84b1168.jpg)
Shifted Lycan still has the human portrait.

**Comment by cigumo** [comment]
fixed in kr1-phone-4.2.00 and kr2-phone-4.2.00
desktop has a single icon
