### ISSUE TITLE
kr1 barbarian nets?

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#1315]
![20200418071340_1](https://user-images.githubusercontent.com/43391939/79618248-7cd03300-8144-11ea-903c-7c46c91664a1.jpg)
> In the encyclopedia it says that one of the barbarians skills is throwing nets but the picture is that of the whirlwind attack.

https://steamcommunity.com/app/246420/discussions/0/4540134287674443009/

**Comment by sunnydaler** [comment]
![Kingdom Rush_2020-04-18-06-20-25](https://user-images.githubusercontent.com/43391939/79615055-ca48a200-813c-11ea-81ef-89d66ec96f85.jpg)

**Comment by cigumo** [comment]
fixed in kr1-4.0.15
