### ISSUE TITLE
kr1-phone korean typos

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1320]
- [x] Are you not entertained? Achievement 
Popup contains the description of Twilight Scourger on top of it.
![VideoCapture_20200420-133554](https://user-images.githubusercontent.com/43391939/79764416-4d960d80-8360-11ea-9db6-ca776fd58f18.jpg)
![Kingdom Rush_2020-04-20-14-07-34](https://user-images.githubusercontent.com/43391939/79764454-5a1a6600-8360-11ea-84ce-784257af3585.jpg)

-  [x] mobile Musketeers has a different name from desktop version.
![Kingdom Rush_2020-04-20-09-29-09](https://user-images.githubusercontent.com/43391939/79764653-9c43a780-8360-11ea-9966-92b3529ba9d9.jpg)
![20200421000148_1](https://user-images.githubusercontent.com/43391939/79766759-5e944e00-8363-11ea-8ef6-3e5abd7b1c5d.jpg)

**Comment by cigumo** [comment]
fixed in kr1-4.0.15
