### ISSUE TITLE
["TIP_HEROES"] display and condition

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1321]
- [ ] card on phone. balloon on desktop.

- [ ] when should it be displayed?

on desktop, a small balloon pops up when Gerald is played for the first time in Twin Rivers campaign. 
![20200420235912_1](https://user-images.githubusercontent.com/43391939/79766744-59370380-8363-11ea-8712-c2475c819327.jpg)

on phone, a card is display on the front when a hero (not just Gerald) is played for the first time in Twin River campaign. ( I don't know if this card opens in the other stages, too)
![Kingdom Rush_2020-04-20-11-30-16](https://user-images.githubusercontent.com/43391939/79767767-c6976400-8364-11ea-9d1c-d83ede2ffdf5.jpg)

**Comment by cigumo** [comment]
fixed in kr1-4.0.15 to show only the icon
