### ISSUE TITLE
review kr1 achievements 50 shots, toxicity

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#1328]
https://steamcommunity.com/app/246420/discussions/0/2260187517776548253/

**Comment by sunnydaler** [comment]
50 sniper shot and toxicity work in ver. 14 phone.
![VideoCapture_20200423-125420](https://user-images.githubusercontent.com/43391939/80057460-9ec11f80-8561-11ea-8711-697d2b903982.jpg)

![VideoCapture_20200423-123302](https://user-images.githubusercontent.com/43391939/80056203-ac28da80-855e-11ea-9e60-0010af13b581.jpg)

**Comment by cigumo** [comment]
works.
