### ISSUE TITLE
Umbra leaves decals behind

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1330]
![Frontiers_2020-04-25-01-30-35_new - 2368](https://user-images.githubusercontent.com/43391939/80238836-1b571980-869a-11ea-9afa-84494d555d04.jpg)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43391939/80238714-dcc15f00-8699-11ea-9c75-6af7d96775a2.gif)

![Screenshot_20200531-224731_YouTube](https://user-images.githubusercontent.com/43391939/83353921-d016e180-a390-11ea-8e52-0a71698d1b1d.jpg)

**Comment by cigumo** [comment]
fixed in 4.2.24
