### ISSUE TITLE
hero room speed barmeters

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1335]
hero room barmeters don't reflect heroes' actual movement speed.

in hero room
8 bars: Magnus 
7 bars: Elora
6 bars: Alleria, Ignus, Oni
5 bars: Gerald, Ingvar, Thor
4 bars: Malik, Bolin
3 bars: King Denas, Hacksaw

actually they should be
8 bars: Magnus 
7 bars: Alleria, Ignus, Elora
6 bars: Oni, Thor
5 bars: Ingvar
4 bars: Gerald 
3 bars: Malik, Bolin, King Denas
2 bars: Hacksaw

( i manually checked each hero's speed and categorized those with the same speed.)

**Comment by cigumo** [comment]
speed | hero
--- | ------------
1.2 | hero_magnus  
1.8 | hero_hacksaw 
2.0 | hero_bolin   
2.0 | hero_denas   
2.0 | hero_malik   
2.2 | hero_gerald  
2.5 | hero_ingvar  
2.7 | hero_oni     
2.7 | hero_thor    
3.0 | hero_alleria 
3.0 | hero_elora   
3.0 | hero_ignus

**Comment by cigumo** [comment]
changed in kr1-4.2.00
