### ISSUE TITLE
Toughness Training and Endurance Training upgrades

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1351]
Screen shots on veteran
![Kingdom Rush_2020-04-30-08-44-41](https://user-images.githubusercontent.com/43391939/80657609-07a71b00-8abf-11ea-84c5-3d510960b492.jpg)
![Kingdom Rush_2020-04-30-08-44-57](https://user-images.githubusercontent.com/43391939/80657613-0970de80-8abf-11ea-8be5-f5c570313096.jpg)
![Kingdom Rush_2020-04-30-08-44-48](https://user-images.githubusercontent.com/43391939/80657614-0a097500-8abf-11ea-9b7e-f4fc4e1c1a96.jpg)

It should be 10% increase each on normal and veteran difficulty 
lvl 1  50 +5 +5
lvl 2 100 +10 +10
lvl 3 150 +15 +15
paladin 200 +20 +20
barb 250 +25 +25

and multiply them by 1.2 for casual.

**Comment by cigumo** [comment]
fixed it in kr1-4.0.03
