### ISSUE TITLE
wrong star count in map

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1352]
![Screenshot_20200429-131020_Kingdom_Rush](https://user-images.githubusercontent.com/43391939/80656576-7767d680-8abc-11ea-98ab-022d6ea7c125.jpg)

**Comment by cigumo** [comment]
![Screenshot_20200430-141720_Kingdom_Rush](https://user-images.githubusercontent.com/934821/80710995-062d2100-8ac6-11ea-981c-118ca34fa901.jpg)

**Comment by cigumo** [comment]
fixed in 4.2.04
