### ISSUE TITLE
kr1-phone: review Fat Boy

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1354]
- [x] damage on (mini-)bosses

It should deal 3000 damage to minibosses and bosses.
but it kills Cerberus
(i didn't check bosses and hobgoblin yet.)

- [x] Should Demons with shield survive from Fat Boy?
They survive from it on beta.

**Comment by cigumo** [comment]
fixed in 4.2.04
- changed atomic bomb damage type to explosive following cocos
- cerberus and hobgoblin are marked as f_boss + f_miniboss, to be excluded from atomic bomb but killed by kill_all_enemies
- demon shield fixed too
