### ISSUE TITLE
New enemy notification issues

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1362]
- [x] card says Legions have great armor. Change it to high armor.
![Screenshot_20200504-205012_Kingdom Rush](https://user-images.githubusercontent.com/43391939/80964250-7c75ae80-8e4b-11ea-9d5a-1d09f741258d.jpg)

- [x] Flareon. Change "ranged magic attack" to "ranged fire attack"
![Screenshot_20200504-205359_Kingdom Rush](https://user-images.githubusercontent.com/43391939/80965406-6ec12880-8e4d-11ea-807b-22d220fa6e6e.jpg)

U may copy it from kr3's gnoll burner.
![20200504_212353](https://user-images.githubusercontent.com/43391939/80965502-9912e600-8e4d-11ea-88b0-928fb4ddd396.jpg)

- [x] Cerberus has a new enemy card on cocos. Missing on love.
![Screenshot_20200504-204349_Kingdom_Rush](https://user-images.githubusercontent.com/43391939/80964308-944d3280-8e4b-11ea-9e67-d16c7dbcdead.jpg)

**Comment by cigumo** [comment]
fixed in 4.2.06
