### ISSUE TITLE
review tesla prediction issues

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#1364]
https://cdn.discordapp.com/attachments/212252625792532480/706889132147998730/Tesla_Fail..mp4

https://cdn.discordapp.com/attachments/212252625792532480/706889132147998730/Tesla_Fail..mp4

**Comment by sunnydaler** [comment]
And there is an issue about jumping.
Lightning can arc to targets across the path
As shown in the following video link
https://cdn.discordapp.com/attachments/212252625792532480/706889817123717231/Interesting_Tesla_jumps..mp4

**Comment by cigumo** [comment]
https://cdn.discordapp.com/attachments/567811170342535188/706927246337769552/not_targeting.mp4

**Comment by cigumo** [comment]
https://cdn.discordapp.com/attachments/567811170342535188/706902984461647922/Tesla_vs_Worg.mp4

**Comment by cigumo** [comment]
made some changes in 4.2.07:
- once it starts charging it will shoot the enemy if it's range is under a 1.2 x max range (covers prediction errors and prevents teleported enemies to be shot too far away)
- at the moment the ray is about to be triggered, if the enemy dies or disappears, another one will be picked within range without prediction or range factor.
