### ISSUE TITLE
kr1: enemy spawn in Nightfang Swale Iron

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1372]
https://steamcommunity.com/app/246420/discussions/0/22601875177889225

![5 lycans from the west cocos](https://user-images.githubusercontent.com/43391939/81346335-16ac4f80-90f5-11ea-90c4-758ecd31f65c.jpg)
57/
![5 lycans from the west](https://user-images.githubusercontent.com/43391939/81346352-19a74000-90f5-11ea-9423-00dfb162be76.jpg)

**Comment by cigumo** [comment]
Mmlh
> If it's any help, the part where everyone seems to get stuck is a part where three human form Lycans come in from the middle and three wolf form Lycans from the left iirc
