### ISSUE TITLE
kr1: wave icons are placed incorrectly

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1390]
- [x] Fungal Forest (north center)

![VideoCapture_20200519-062449](https://user-images.githubusercontent.com/43391939/82261241-a5dd2100-9999-11ea-8c1b-4de2533066e8.jpg)
![VideoCapture_20200519-062604](https://user-images.githubusercontent.com/43391939/82261254-abd30200-9999-11ea-8db5-febf6ab839d8.jpg)
Rotshrooms go to the left and Treants take the middle lane. But the wave icons are incorrectly placed.
The middle one and the left one need to be swapped for proper indication of enemy spawns.

- [x] Ancient Necropolis (bottom left)
![2020_05_20_06_43_03_400_new - 28](https://user-images.githubusercontent.com/43391939/82382419-da6ade80-9a66-11ea-87d4-3ffcffd5f671.jpg)
![2020_05_20_06_51_30_756_new - 40](https://user-images.githubusercontent.com/43391939/82382426-de96fc00-9a66-11ea-813c-ec378f37d817.jpg)
unlike the icons of top-left path, the icons of bottom-left path are incorrectly placed.
in the top picture, icon seems to indicate that enemies will go straight to the west, but no, they go upwards.
same in the bottom picture; the icon is placed on the top of the path. but enemies go straight to the east exit.

**Comment by cigumo** [comment]
fixed in 4.2.15
