### ISSUE TITLE
kr3-phone: Reg'son skill icon backgrounds have no color

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1391]
![Origins_2020-05-20-09-33-37](https://user-images.githubusercontent.com/43391939/82391937-9c2ce980-9a7d-11ea-989a-3b23b7f0e7af.jpg)

Ok on Steam
![Screenshot_20200520-093643_YouTube](https://user-images.githubusercontent.com/43391939/82391984-b23aaa00-9a7d-11ea-8d82-fbf43d684827.jpg)

**Comment by cigumo** [comment]
fixed in 4.2.17
