### ISSUE TITLE
object texture in Rotwick

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1396]
Unity
![KRstage23-1](https://user-images.githubusercontent.com/43391939/82823573-c7329580-9ee2-11ea-81a3-6b23ff236d24.jpg)

Love
![20200525235019_1](https://user-images.githubusercontent.com/43391939/82823734-15e02f80-9ee3-11ea-9f35-df7e5686eba6.jpg)

**Comment by cigumo** [comment]
fixed in 4.2.19
