### ISSUE TITLE
kr2: Saurian Deathcoil - death delays

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1400]
If they die while locked in position for shooting, death animation plays after they release projectiles.
https://cdn.discordapp.com/attachments/418776085086470144/716645456196796466/ezgif.com-crop_1.mp4

**Comment by cigumo** [comment]
I've checked and it does not seem to happen. There is a specific check in the code to prevent this. Also...
![Screen Recording 2020-06-19 at 2 44 51 PM mov](https://user-images.githubusercontent.com/934821/85165049-9c1a3800-b23b-11ea-97b9-d22a8c5abb93.gif)
