### ISSUE TITLE
Bloodletting Shot upgrade does not affect shots from rangers and alleria in Gryphon Point

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#141]
Bloodletting Shot upgrade does not affect shots from the 3 rangers and Alleria Swiftwind on the high ground in Gryphon Point map.

They are affected by the upgrade on mobile.

**Comment by cigumo** [comment]
I don't see them affected on mobile.

**Comment by sunnydaler** [comment]
They used to be but no more
