### ISSUE TITLE
kr1: DE Sasquatch 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1415]
![Screenshot_20200614-193403_Kingdom_Rush](https://user-images.githubusercontent.com/43391939/84604352-4d357100-aed0-11ea-89d3-bd7df1bed90e.jpg) 
German users said 
it should be "Der legendäre Sasquatch wird dir für Nahrung und Gold helfen."

**Comment by cigumo** [comment]
fixed in 4.2.20
