### ISSUE TITLE
Golden Longbows' Hunter's Mark does not work in short range. / sunnydaler

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#143]
The tower shoots at a target in short range but the victim is not affected by it. I mean the enemy neither take double damage from all source nor is highlighted in yellow.

**Comment by cigumo** [comment]
I've tested it and works with golems and avengers. 
In this video it's not clear if it's due to coming out of portal.
https://youtu.be/cMnYH8c4l4w

**Comment by cigumo** [comment]
I can't reproduce it even I can see it in sunnydaler's video

**Comment by sunnydaler** [comment]
Now, Hunter's Mark is not working even in long range on v9.4.
Test condition: I upgraded Elven Training on tech tree.
https://youtu.be/Vki8QI3Rt7Q

**Comment by cigumo** [comment]
fixed in v0.9.6
