### ISSUE TITLE
kr1: encyclopedia images are wrong

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krli#1443]
![Screenshot_20200831-151035](https://user-images.githubusercontent.com/40719238/91723604-4dbed900-eb9c-11ea-94f9-89798c8667c2.png)
![Screenshot_20200831-151047](https://user-images.githubusercontent.com/40719238/91723616-50b9c980-eb9c-11ea-8d6d-a00be7ffd56e.png)
![Screenshot_20200831-151101](https://user-images.githubusercontent.com/40719238/91723625-53b4ba00-eb9c-11ea-9821-0e0002dab073.png)

It seems like this wasn't fixed after all.

**Comment by sunnydaler** [comment]
it somehow rolled back in 4.2.27

**Comment by sunnydaler** [comment]
#1395

**Comment by cigumo** [comment]
fixed in 4.2.33
