### ISSUE TITLE
kr2: colored border of the towers disappear when select

### ISSUE THREAD

**Issue by 252542477** [cigumo/krli#1444]
When click the towers，the colored border of the towers disappeared in latest version.this not happen in latest kr1 version.
older version：
![FD247FF1-A15E-4B33-9775-DBD5C88BC709](https://user-images.githubusercontent.com/55611142/92261297-c9f24d00-ef0b-11ea-8c59-dc1d9c122162.jpeg)
latest version：
![04C7856C-9647-4B7B-8C95-C8BB8085C15C](https://user-images.githubusercontent.com/55611142/92261336-d9719600-ef0b-11ea-9295-b7e50a5c2dc5.jpeg)

**Comment by Mmlh1** [comment]
This is fixed in 4.2.29 as far as I can see.
