### ISSUE TITLE
"Rift of Cinders" - Korean localization

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1448]
Rift of Cinders is a place name in the KR universe. And, rift is a geologic term.
However, in Korean localization, it was translated into a crack.

- [x] kr1 - Pit of Fire stage description
![20200927131341_1](https://user-images.githubusercontent.com/43391939/94385309-c440fd80-017f-11eb-8529-4ac6bfba0655.jpg)
original English text goes: Demons have ravaged our troops stationed at Vez'nan's tower (.....)

Change 불타는 균열에서 to 잿불의 열곡에서

Corrected Korean text (desktop version. Mobile version has a line break inserted before 사령관님.): 베즈난의 타워 근처에 주둔했던 부대가 악마들의 공격에 궤멸되고, 단 한 명이 겨우 살아남았습니다. 두려움에 미쳐 횡설수설하는 그의 말에 따르면, 그 지옥의 군대는 **잿불의 열곡에서** 나타났다고 합니다. 사령관님, 그곳을 탈환하고 적들의 진짜 근거지를 파악해 베즈난에게 반드시 승리해야 합니다.

- [ ] kr3 - Shrine of Elynie Comics outro
![20200927131559_1](https://user-images.githubusercontent.com/43391939/94385381-02d6b800-0180-11eb-8762-4e363db85568.jpg)

Original English text: Then it must be cast into the flames of the Rift of Cinder!

Corrected Korean text: 그렇다면 **잿불의 열곡의** 불길에 던져버려야 해!

**Comment by cigumo** [comment]
fixed the kr1 part in 4.2.31

@sunnydaler shouldn't the kr3 be 그렇다면 잿불의 열곡에서 불길에 던져버려야 해!?
