### ISSUE TITLE
Hero unlocking stage descriptions are wrong

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1453]
![Kingdom Rush_2020-10-14-01-45-11](https://user-images.githubusercontent.com/43391939/95890832-3f7cf300-0dbf-11eb-9cea-e654b0235723.jpg)
![Kingdom Rush_2020-10-14-01-45-15](https://user-images.githubusercontent.com/43391939/95890841-43107a00-0dbf-11eb-90ba-0a6496a16479.jpg)
![Kingdom Rush_2020-10-14-01-45-19](https://user-images.githubusercontent.com/43391939/95890850-46a40100-0dbf-11eb-8821-45105c799aa8.jpg)
Gerald unlocks at stage 4.
Alleria at 6
Malik at 8.

**Comment by cigumo** [comment]
fixed in 4.2.33
