### ISSUE TITLE
KR1 - Wrong music is played in Ruins of Acaroth

### ISSUE THREAD

**Issue by Danchetovich** [cigumo/krli#1456]
If you start a Ruins of Acaroth, preperation music for it would be the music from Ice stages, even tough it should be Music from Goblin stages and etc. When you start the game, Goblin music starts playing, which is pretty weird. Cig, please fix it,

KR1 - Steam

**Comment by sunnydaler** [comment]
-----Ruins of Acaroth preparation music------
cocos, unity: Kingdom Rush - Forest - Battle Preparations.wav (the one that has bird chirping sound)
love: Kingdom Rush - Icewind Pass.wav (the slow march music with heavy wind sound)

**Comment by cigumo** [comment]
fixed in 4.2.31
