### ISSUE TITLE
kr2: Mirage's Shadow Dance gets put on cooldown after moving

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krli#1461]
https://cdn.discordapp.com/attachments/418776085086470144/774694093238173696/clip_1604770203956.mp4

Unlike all other skills on all other heroes (pretty much), if you move Mirage during the start of Shadow Dance animation, it gets put on cooldown without it dealing damage.

**Comment by cigumo** [comment]
fixed in 5.6.14
