### ISSUE TITLE
kr2: Shrine of Regnos and Pirate Watchtower offset duplicate when hovering over it/selecting it

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krli#1473]
https://cdn.discordapp.com/attachments/418776085086470144/780032463517777920/unknown.png
https://cdn.discordapp.com/attachments/704316172882935828/796498140991586314/unknown.png

When you hover over the Shrine, or select it, it will have this weird duplicate, offset image of it. This happens at all upgrade levels, in both Storm Atoll and Sunken Citadel. The same applies to the Pirate Watchtowers in Port Tortuga.

This only happens on Steam, Android is fine (not sure about Switch).

**Comment by cigumo** [comment]
<img width="524" alt="Screen Shot 2021-07-13 at 10 56 58" src="https://user-images.githubusercontent.com/934821/125464815-781bcfbc-a4c3-4b2a-bbc5-6d8791f6f12c.png">

**Comment by cigumo** [comment]
fixed in 5.4
