### ISSUE TITLE
kr3: Vez'nan, skills not interruptable 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1481]
BBB said
![Screenshot_20210101-072207_Discord](https://user-images.githubusercontent.com/43391939/103427197-a1046f00-4c02-11eb-87f1-b84f61891418.jpg)

https://cdn.discordapp.com/attachments/423213564644556822/794334197187739678/YouCut_20210101_073957536.mp4

**Comment by cigumo** [comment]
fixed in 5.6.14
