### ISSUE TITLE
kr1: Fungal Forest wrongly unlocks

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krli#1482]
https://cdn.discordapp.com/attachments/567811170342535188/795804288621871204/unknown.png

Reported by ThrowingHydra
Beating Pandaemonium (stage 21) before Rotten Forest (stage 14) unlocks Fungal Forest (stage 22), even though only beating Rotten Forest should unlock it.

Editing the save file such that Pandaemonium has been beaten and Rotten Forest hasn't does not trigger this bug - Pandaemonium has to be manually beaten without Rotten Forest being beaten.

**Comment by cigumo** [comment]
fixed in 5.6.06
