### ISSUE TITLE
kr1: King Denas's skills are put on cooldown when interrupted

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krli#1491]
https://user-images.githubusercontent.com/40719238/105560114-37641600-5d13-11eb-9360-a6cb5a8034f4.mp4

If Denas's skills are interrupted, they are put on cooldown, even if they've been interrupted early enough to have no effect. You can see in the clip that the text bubble for Royal Edict pops up, but the effect is not applied, thanks to Denas being moved. This is also true for Catapult Barrage as far as I could tell, but it's much harder to replicate there, since the window is much smaller - as soon as the X is put on the ground, it'll be triggered properly even if you move him. I might be able to get a clip of that as well.

**Comment by cigumo** [comment]
fixed in 5.6.06
