### ISSUE TITLE
regenerating enemies regen faster for a short while after released from thorn/freeze

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1502]
- [ ] KR1 
regenerating enemies:
swamp thing
troll
forest troll
troll brute
troll skater
troll axe thrower
troll chieftain
werewolf
lycan
mod:
freeze - Elora, mobile freeze items
thorn

https://cdn.discordapp.com/attachments/567811170342535188/810697747976028180/YouCut_20210215_112137755.mp4

After released from thorn or freeze (Elora, items), they regen in each frame for a while.
For 11/18/23 frames on level 1/2/3 thorn, respectively.
For 15 frames on Elora's 2s freeze.

- [ ] KR3
enemies:
ettin
ogre magi
mod:
freeze - arivan (hero spell and icy prison)
timelapse 

https://cdn.discordapp.com/attachments/567811170342535188/810707277207568434/2021_02_15_11_55_59_508_new.mp4
https://cdn.discordapp.com/attachments/567811170342535188/810702190162477066/YouCut_20210215_114043090.mp4

-----------
somehow, this bug is not present in kr2. (I tested freeze items and twister on lycan and werewolf)

**Comment by cigumo** [comment]
fixed in 5.6.14
