### ISSUE TITLE
Eridan hero spell sound missing?/ THWeaver

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#154]
Is there supposed to be a sound effect for Eridan’s Hero Power? If so, I either can’t hear it or it doesn’t seem to be playing. (8)

**Comment by sunnydaler** [comment]
I can hear it. No problem on my pc.

**Comment by cigumo** [comment]
@Thought-Weaver  reported many issues with audio... maybe it's some issue with their setup.
