### ISSUE TITLE
kr1: suggested hero description changes

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#1547]
- [x] Alleria has 'too many have fallen by her gaze', but I would definitely say 'too many have fallen for her gaze' here (though probably best to double check with Aeris)
- [x] Magnus just has a very weird final sentence, which isn't a real sentence, but instead is something that should be part of the previous sentence.
- [x] 'Your majesty itself' for Denas is weird, and I'd change that to 'His majesty himself'
- [x] For Ingvar, the description would flow a bit more nicely when the first comma is changed to a period.
- [x] 'Mechanical Marvel/Contraption' in Hacksaw's description is a bit awkward, with the capital letters and the slash. 'Gangway' also appears to be very archaic, so it does fit with the medieval theme, but I'm not sure if people actually understand what it means (namely, 'Make way').

**Comment by Mmlh1** [comment]
Gerald is also described as 'the uncanny of Linirea's forces', which is weird - 'uncanny' generally has a negative sound. I'm not sure what would be a suitable replacement.

**Comment by AerisDraco** [comment]
- [ ] Gerald - Perhaps 'champion' could work to replace 'uncanny'?
- [x] Alleria - Change "Too many have fallen by her gaze and many more by her bow" to "Too many have fallen **to** her gaze, and many more **to** her **arrows**." (Bow is also acceptable as the last word)
- [x] Malik - Add 'comes' to the first line "From a land far, far away, **comes** a hero...". The "bullet train attitude" bit also doesn't quite end the sentence right but I guess it's fine.
- [x] Magnus - As Mmlh said, last sentence is weird. His suggestion works, change it to "...spellbind your enemies with his arcane arts and thirst for knowledge!"
- [x] Ignus - "raging flames, **and consume** evil in fire and brimstone!"
- [x] Denas - See Mmlh's suggestion. Also, "arsenal" typically describes physical objects, but it's probably fine.
- [x] Ingvar - Change first sentence: "**A** fierce warrior from the northern wastes. His physical..." (Add a period)
- [x] Hacksaw - Either remove contraption or add a space between the slash and the words. Also 'Make way' makes more sense to most people over 'Gangway'.
- [x] Oni - Change first sentence: "**A** relentless warrior in search of vengeance."" (Remove the comma)

**Comment by cigumo** [comment]
not changed uncanny, not changed Marvel/Contraption. 
fixed the rest with Aeries, Voduke and Mmlh participating, so blame them! :D
