### ISSUE TITLE
Certain stages have inaccessible spots that should be accessible

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krli#1563]
- [X] kr1 - The Wastes:
![image](https://user-images.githubusercontent.com/40719238/147156782-c99ba9db-4172-4bd7-959e-000cc1bdb3f8.png)

- [X] kr1 - Rotwick:
![image](https://user-images.githubusercontent.com/40719238/147156803-84695231-0f93-4ab5-9379-2315e4d0606c.png)
(Bottom left is accessible on Cocos, https://youtu.be/TeWJeBOaScg?t=546)

- [X] - kr1 - Nightfang:
![image](https://user-images.githubusercontent.com/40719238/147157222-dd5d79b1-703c-4373-8339-6cba5368e543.png)

- [X] - Crystal Lake:
![image](https://user-images.githubusercontent.com/40719238/147157431-5a1d00e7-6f96-4cb8-ba53-2a1c3897eacf.png)

**Comment by cigumo** [comment]
fixed in 5.6.17+

**Comment by cigumo** [comment]
fixed all these: 
<img width="308" alt="Screen Shot 2021-12-22 at 21 23 06" src="https://user-images.githubusercontent.com/934821/147169571-e831f571-a985-4904-ad2e-28b27ef4eb7e.png">
