### ISSUE TITLE
Is Cigumo dead?

### ISSUE THREAD

**Issue by TurkPasha** [cigumo/krli#1584]
He is not someone one would call active. When he has not been active in Months and wont even address the issues, whats the point of this threads when that bastard isnt even online anymore?

**Comment by Mmlh1** [comment]
Please do not insult people. Cigumo is very busy with other things - he doesn't solely work on these three games. For example, he was involved in the release of Rise of the Dragon on Steam, which obviously takes a lot of time. The fact he does not say anything here does not mean that he is not busy.
