### ISSUE TITLE
anurian plaza does not end after all enemies are dead for like 5 minutes

### ISSUE THREAD

**Issue by notdrerror** [cigumo/krli#1593]
![Screenshot_2023-08-25-19-25-21-24_a7c007cd1e4f3675e855d3907cf2df60](https://github.com/cigumo/krli/assets/142210138/1258017a-1ac8-4bbc-8e9f-b274a51e2abe)
![Screenshot_2023-08-25-19-27-18-64_a7c007cd1e4f3675e855d3907cf2df60](https://github.com/cigumo/krli/assets/142210138/bfcfeaf0-201f-4d6d-9c0f-5f7bd9aa431c)

**Comment by Mmlh1** [comment]
I'm closing this as it is the wrong github repo for this game - KRV has its own github repo. See the issue [here](https://github.com/cigumo/krvi/issues/300). I added your images there!
