### ISSUE TITLE
Arcane Sentinel deals more damage on Steam.

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#178]
> sunnydaler: When I tested Sentinel in early July on Android, the damage was 1 to 31.
> sunnydaler: On Steam, I've seen it dealing 29-32
> sunnydaler: It is a good buff for HEM as it s UP without them.

**Comment by sunnydaler** [comment]
How about changing it to 16-32 or 15-30?
29-32 is a bit too powerful and the damage range on mobile varies  too much.

**Comment by cigumo** [comment]
looks like a bug in the iOS code.
waiting for gerson to reply

**Comment by cigumo** [comment]
gerson agrees to 16-32
