### ISSUE TITLE
Ricardo Antonaci: a que se refiere con optimizado para nexus 7?

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#18]
Ricardo Antonaci: a que se refiere con optimizado para nexus 7? Nos puede describir lo que cambió?  
https://play.google.com/apps/publish?account=6098018911218203911#ReviewDetailsPlace:p=com.ironhidegames.android.kingdomrushfrontiers&reviewid=gp:AOqpTOHieCgKnms4OsrjGES43Y7M--EFqNpLmU1anlkyjBF2XAC7Q-XAlF2qHpZtCwDfNJ3sZkf7WsuXoLpDjA

**Comment by luciag27** [comment]
"Now, during each game session, the tablet navigation bar (the one with back button, home button, etc.) is always showed instead to be minimized, as usual: in this way the lower portion of screen is covered and is not possible to use, for example, special items. Let's see attached pic.
Furthermore, when I try to build a tower the screen automatically zoom in."

![c8smpfcce9apd3fdbxjooqxuerghsifpqw](https://user-images.githubusercontent.com/30800937/37538165-8a4d4eb6-292e-11e8-9ffa-3a27a5683d64.jpg)

First time of problem I think 3/4 days ago. 
Before the game was perfect. 

In credit page, at upper left corner,  I read KR2-PHONE-3.0.25

The Nexus runs CM 10.2 (based on Android 4.3.1).

Whit this firmware I also play K. Rush and K. Rush Origins and they are perfect.

**Comment by cigumo** [comment]
fixed in v3.0.27  (not yet released)
