### ISSUE TITLE
Steam Razorboars are unblockable when they charge / sunnydaler

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#184]
- Steam Razorboars are unblockable when they charge, while  mobile Razorboars can be blocked even if they charge.
- review speed when charging

**Comment by sunnydaler** [comment]
And they can charge even near the exits.

**Comment by cigumo** [comment]
![mobile_razorboar](https://user-images.githubusercontent.com/934821/45785309-381ba780-bc42-11e8-8302-cbd093477935.gif)
![steam_razorboar](https://user-images.githubusercontent.com/934821/45785390-7dd87000-bc42-11e8-9e66-f87f552537b2.gif)

**Comment by cigumo** [comment]
- there is a bug in the original code and the speed mult is 3 on Ipad and 1 on iphone.  changed steam version to 1, as in the iphone version. 
- increased the max allowed distance from exit to charge
