### ISSUE TITLE
Bladesingers' Edge Mastery attack speed remains the same / sunnydaler

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#186]
https://youtu.be/ZDALIqXMaTM

**Comment by sunnydaler** [comment]
Perpect Parry needs to be checked, too. Its proc chance seems to ne too low for 30% at level 3. And the sound effect is missing.

**Comment by cigumo** [comment]
- fixed edge mastery cooldown
- fixed perfect parry chance and sound
