### ISSUE TITLE
 Forest keepers seems to have their own reloading time for Eerie Gardener / sunnydaler

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#193]
note: sunnydaler likes this buff

**Comment by sunnydaler** [comment]
Cooldown is 16 seconds and each FK has use the skill independently to each other.
I mean even though one Fk uses the skill at 0'00", the other FK can use it at 0'02".

**Comment by cigumo** [comment]
fixed eerie garden and cicle of life having individual cooldowns. 
will ask Gerson about buffing it up.
