### ISSUE TITLE
remove hero skill cooldown at start of the game / sunnydaler

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#194]
> [12:55 PM] sunnydaler: some heroes' skills need to wait for cooldown even at the start of the game.(edited)
> [12:56 PM] sunnydaler: They are not in KRF Steam. Sha'tra uses Abduction right off the bat. Cronan does Deep Lashes right away. Dante shoots Silver Bullet after a few shots.(edited)
> [12:57 PM] sunnydaler: However, Bravebark has to wait 37 something seconds to use Branchball and needs more time to use Springsap. Reg'son has to wait for his Eldritch Blade to reload. So do Prince Denas, Xin, Vez'nan.(edited)
> [12:58 PM] sunnydaler: On KRO mobile heroes  have the same problem.

**Comment by sunnydaler** [comment]
It is ok.
