### ISSUE TITLE
Typo with Gnome Garden / THWeaver

### ISSUE THREAD

**Issue by Thought-Weaver** [cigumo/krli#197]
The Gnome Garden "Total Mischef" upgrade description should have an apostrophe: "Adds a poison attack to the gnomes' repertoire."

**Comment by Thought-Weaver** [comment]
![screen shot 2018-09-19 at 9 47 06 am](https://user-images.githubusercontent.com/10130985/45761490-5f4e8680-bbfa-11e8-8ee6-a5a924d3641f.png)

**Comment by cigumo** [comment]
fixed
