### ISSUE TITLE
Clicking an enemy before entering a faerie path leaves a selection marker / THWeaver

### ISSUE THREAD

**Issue by Thought-Weaver** [cigumo/krli#198]
If you click an enemy right as it's about to disappear into a faerie path, the marker will remain on the ground and the information will display on the bottom bar.

<img width="1280" alt="screen shot 2018-09-19 at 10 51 15 am" src="https://user-images.githubusercontent.com/10130985/45761469-51990100-bbfa-11e8-8400-31c19a192769.png">

**Comment by cigumo** [comment]
fixed
