### ISSUE TITLE
stage background glitches / sunnydaler

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#219]
![krostage02a-](https://user-images.githubusercontent.com/934821/45918849-2c5afb80-be63-11e8-9a76-94192726dd00.jpg)
![krostage11a-](https://user-images.githubusercontent.com/934821/45918850-2c5afb80-be63-11e8-984d-d53b6678bb05.jpg)

**Comment by sunnydaler** [comment]
![neverwonder](https://user-images.githubusercontent.com/43391939/45958501-8cfc5b00-c052-11e8-87d0-a4b0026f9c6e.jpg)
Found a glitch in Neverwonder map. I circled it yellow.

**Comment by cigumo** [comment]
fixed
