### ISSUE TITLE
Catha's Pixie Warriors do not spread out immediately / THWeaver

### ISSUE THREAD

**Issue by Thought-Weaver** [cigumo/krli#224]
When Catha creates her Pixie Warriors, their health bars appear where they're supposed to move, but the bodies do not.

![screen shot 2018-09-22 at 3 36 05 pm](https://user-images.githubusercontent.com/10130985/45921158-3a6a4580-be7e-11e8-82dc-f0e0b86938df.png)

**Comment by cigumo** [comment]
fixed
