### ISSUE TITLE
Prince Denas' Celebrity stun is shorter than the description / sunnydaler

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#227]
> sunnydaler: My test results (runned and recorded at FPS 60): 2.25s /3.217s/4.617s on Scouger and 1.617s/2.617s/3.05s on Hyena

**Comment by sunnydaler** [comment]
Just tested it against Golem under the same condition.
level 1: 2.233s
level 2: 3.217s
level 3: 4.617s

**Comment by cigumo** [comment]
it's ok. 
he keeps stunning while performing the skill. once he finishes, the stun lasts 3 seconds in level 3
