### ISSUE TITLE
Steam Ettin has a higher health regeneration rate.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#235]
[sunnydalerToday at 6:54 PM]
Tested Ettin's health regeneration.
On mobile, they heal 20 health every second
On Steam, they heal 27.5 health every second on average.(edited)
[sunnydalerToday at 7:14 PM]
they heal 2 hp per 3 frames at 30fps on mobile, and
4 hp per 8 or 9 frames (8.5 on average) at 60fps on Steam.

**Comment by cigumo** [comment]
fixed
