### ISSUE TITLE
Reg'son's Eldritch Slash damage is incorrectly described. 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#239]
I tested it on Steam and these numbers are results. I don't know the exact range of damage for each level.

level 1: 21 23 24 27 29 30 31 32 33 34 35 38 39 40 41 42 43 45 46 47 48 49 50 51 53 54 57 58

level 2: 46 50 52 54 56 58 65 68 69 71 72 80 82 83 86 91 92 106 109 110 111 114 115 117 121 122 123 124 125 130

level 3: 75 78 83 86 89 92 99 101 103 106 111 116 119 128 130 136 142 146 148 171 174 179 180 181 186 187 188 189 190 193 212 213 216 217 220

**Comment by cigumo** [comment]
they are 20-60, 45-130, 75-225
fixed.

**Comment by sunnydaler** [comment]
45 mutiply by 3 is 135. Isn't it?
