### ISSUE TITLE
Matheus: can't reach next level

### ISSUE THREAD

**Issue by luciag27** [cigumo/krli#24]
![image](https://user-images.githubusercontent.com/30800937/37538263-dc66e374-292e-11e8-87ac-162583384b62.png)

Mensaje original: "I've updated Kingdom Rush Frontiers and now I can't reach the next level" 

Oneplus5, with Android 8.0.0

**Comment by luciag27** [comment]
![image](https://user-images.githubusercontent.com/30800937/37973307-9385d090-31b0-11e8-8bad-336592da1313.png)

"And now, most of the UI numbers are missing."

**Comment by cigumo** [comment]
v3.0.26 adds a sanitize pass to the level data to fix the game being blocked in level 4 as shown above.
