### ISSUE TITLE
Steam Faery Dragons do not attack Gloomies and crystallization lasts shorter than the description.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#243]
sunnydalerToday at 1:17 PM
I found that Steam Faery Dragons ignore Gloomies and do not attack them. https://youtu.be/UHZO6yS1Zdo
They attack Gloomies on mobile.

sunnydalerToday at 5:56 PM
Faery Dragon's crystallization lasts precisly 1/1.5/2 seconds. The tower upgrade description says 1.5s/2s/2.5s.

**Comment by cigumo** [comment]
- fixed gloomies
- fixed description
