### ISSUE TITLE
Twilight Harassers and Satyr Cutthroats are also affected by Obsidian Heads upgrade.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#244]
I tested them on Steam.
With this upgrade,
Satyr Cutthroats knives deal 7 damage and 
Twilight Harassers arrows deal 30 damage.

I do not know if this bug was fixed along with the issue number 218: https://github.com/cigumo/krli/issues/218

**Comment by cigumo** [comment]
yes, it was fixed with #218
