### ISSUE TITLE
Twilight Avenger Encyclopedia picture

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#245]
https://cdn.discordapp.com/attachments/423213564644556822/493698094605795338/20180924171844_1.jpg
The encyclopedia picture shows avenger putting a curse on harassers. But actually avenger  does not do that on harassers. I suggest changing the picture accordingly.

**Comment by cigumo** [comment]
I think the code shows all dark elves are not to be cursed. 
check again

**Comment by cigumo** [comment]
fixed!
