### ISSUE TITLE
reinforcements and Elemental Storm cannot be placed in the temple on The Ascent

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#246]
On Steam, Reinforcements and Arivan's Elemental Storm cannot be placed further into the entrance of the temple on The Ascent map. Besides, heros cannot move to the inside of the temple. Btw, the Hero Spells of the other 8 Steam heroes can be placed there. On mobile, all is possible.
https://cdn.discordapp.com/attachments/423213564644556822/493668262694092820/20180924152036_2.jpg

**Comment by cigumo** [comment]
there are many effects that overlap the temple columns and stairs rail. 
to allow this:
- split the rail 
- move the columns above the bullets/effects

**Comment by sunnydaler** [comment]
never mind
