### ISSUE TITLE
Melee heroes get stuck if they stand on the gap between islands

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#247]
https://youtu.be/Lssio-ZU-fc 
Melee heroes engage avenger that spawned on a portal. Then I cannot move them to a different spot until heroes defeat the avenger.

I tried the same on mobile and it didn't happen.
the difference was that heroes choose to take on the left side of Avenger on mobile.
On Steam, heroes take on the right side of Avenger, standing on the small gap between the portal and the other island across it.

**Comment by cigumo** [comment]
Mitigated by patching the heading angle.
The full solution involves checking if the grid is valid before picking a target, which is expensive for all heroes.
