### ISSUE TITLE
Renegades Life Stealer Strike's healing amount description

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#248]
Its description says "Attack that deals 50/100/150 damage, healing the Renegade for half that amount."
According to my tests, its damage works fine and is physical.
However, it heals Renegades for 50/50/?? when they use the skill to unarmored enemies on Steam.
it should be 25/50/75 health. 
Mobile seems to have the same bug.

**Comment by cigumo** [comment]
The description should say: "healing the Renegade for the actual amount inflicted" or similar.

**Comment by sunnydaler** [comment]
I just tested the skill against Avengers and Fungus Breeders on the Steam debug build.
It heals Renegades by 25/50/75 now. Just as the description says.

**Comment by sunnydaler** [comment]
it works fine as the game description says.
