### ISSUE TITLE
Magic tower teleport seems to interrupt Wild Magus explosion spell. / VirtualTT

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#253]

**Comment by sunnydaler** [comment]
I think this happens because
Teleport happens in the blink of an eye, while Eldritch Doom is performed in deliberately delayed fashion. I think it is a way of maximizing explosive damage. It waaits for other enemies to come and then BOOM!

**Comment by cigumo** [comment]
happens when teleport hit first

**Comment by cigumo** [comment]
eldritch now checks flags on insert. 
requires more testing
