### ISSUE TITLE
Soldiers don't heal while ranging / sunyydaler

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#263]
![](https://cdn.discordapp.com/attachments/423213564644556822/493851297942994946/Soldiers_heal_whil_ranging.gif)

**Comment by sunnydaler** [comment]
level 2-3 barracks and level 2-5 reinforcements

**Comment by cigumo** [comment]
They heal while idling. As FK cooldown is longer than the ranged animation duration, they accumulate healing between shots. For others it's too short. 
I'm not going to fix this one.
