### ISSUE TITLE
Webspitter Spider can web Vez'nan's Demon and seems to have no limit in number of soldiers it can web at once.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#266]
I tested it on Steam.
The spider can web Vez'nan's Demon for 3 seconds. I have read that Demon is immune to it on mobile.
![webspitter spider webs demon](https://user-images.githubusercontent.com/43391939/45994379-48aea080-c0ce-11e8-9ec4-85c61c8c1971.gif)

What's the limit number of soldiers a single Webspitter Spider can web at a time? I suppose this is normal because it is AoE attack.
I have seen it webbing 10 soldiers at once: 2 reinforcements, 5 Kingsguards, 3 barracks.
![webspitter spider webs 10 soldiers](https://user-images.githubusercontent.com/43391939/45994382-4cdabe00-c0ce-11e8-97ce-5e7f0ae78966.gif)

**Comment by cigumo** [comment]
there is no limit in mobile. all soldiers melee fighting the spider will be webbed. 
the demon was missing a flag check. fixed.
