### ISSUE TITLE
Erik: progress not saved

### ISSUE THREAD

**Issue by luciag27** [cigumo/krli#28]
Mensaje original: 
"I'm an Android user who recently updated Kingdom Rush Frontiers to version 3.0.25, and I've encountered an issue with your cloud saves. Often when I play a level then exit the game, the game doesn't save. So, when I reopen the game, it loads from the cloud, and I lose my progress. I'm on a Samsung Galaxy S6 if that helps. "

Android version 7.0.

**Comment by cigumo** [comment]
fixed in  #33
