### ISSUE TITLE
The sound of Crystal Serpent rolling at the lake surface is missing

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#280]
when the crystal serpent appears above the surface of the lake in the begining of wave 1, 
there's no sound. It can be heard on mobile.
https://youtu.be/wZMLL_z43j4
I found the audio file inside the .exe file and its name is "kro_sfx_crystalserpent_passby[sinsublows]_B.ogg".

**Comment by cigumo** [comment]
fixed
