### ISSUE TITLE
Eldritch Doomed Hoplite summons cutthroats while exploding.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#282]
https://youtu.be/2T1WrLmIyhE

WM instan-kills Hoplitewhen the enemy is just about to summon cutthroats. and then two sprites are overlapped. One explodes, the other slams is shield and summons allies.

**Comment by cigumo** [comment]
the hoplite is now properly interrupted
the ray has a check in the update which should mitigate it. 
also added an F_RANGED check to ray_simple
