### ISSUE TITLE
blighter range attack still hits soldiers if they move / sunnydaler

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#283]
BoltEnemy.m has a check fo target.isActive that nulls the target. 
Review all enemy bolts.

**Comment by sunnydaler** [comment]
Heretic's bolt does track the target, while Evoker's ranged attack doesn't.
https://cdn.discordapp.com/attachments/423213564644556822/495891514736640020/Heretics_bolt_also_tracks_the_target.gif

**Comment by cigumo** [comment]
fixed for ray_enemy, bolt_enemy and bullet_gnoll_blighter
