### ISSUE TITLE
some of Gryphon Rider's sound effects are missing.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#286]
There is a particular sound at the end of the fire attack on mobile.
https://youtu.be/mu2vNVIRaFA

But on Steam, that sound is missing and it is silent at the end of the attack.
https://youtu.be/pGlokasf2jw

I searched for the corresponding sound file in the .exe file and it is named
kre_sfx_gryphon_shot_v2[end].ogg

The left Gryphon Rider is missing only that sound. However, the right Gryphon Rider is missing more than one.
I made videos for comparison.
First, mobile
https://youtu.be/Uv7YmY-bduY

and Steam
https://youtu.be/IdAvRp0kzKg

**Comment by cigumo** [comment]
fixed
