### ISSUE TITLE
Flame is not displayed on Spider Goddess' body after being hit by Fiery Nut.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#289]
https://cdn.discordapp.com/attachments/423213564644556822/495995938486091789/spider_goddess.gif
This gif shows 2 bugs.

First, The flame is not displayed on her body after being attacked by Fiery Nut.

Second, the boss's ranged attack doesn't damage the dragon.
Here's another gif for the second bug.
https://cdn.discordapp.com/attachments/423213564644556822/495998517832056833/spider_goddes_ranged_attack.gif

**Comment by cigumo** [comment]
fixed
