### ISSUE TITLE
Freddy: level not saved

### ISSUE THREAD

**Issue by luciag27** [cigumo/krli#29]
Mensaje original: 
"Como les había explicado hay a veces que el juego no se graba como es debido. Y por esta razón me ha tocado a repetir misiones y volver a subir a héroes que de supone que ya había ya había subido. Aquí les adjunto la versión de mi celular (de hecho el correo les envió por vía celular) y además una captura de imagen del requisito que me pidieron sobre los créditos en la parte superior izquierdo (KR2-PHONE-3.0.25)"

"Realmente no eh probado con todos desde la actualización. Pero me ha pasado con algunos 7 (alterando) que subo de nivel, salgo de la aplicación y vuelvo a meterme (y a veces me sale que se está actualizando el save cloud) y mi héroe sigue en el mismo progreso antes de hacer una misión. Ahorita estoy en la misión Dark Decent en donde pase la campaña normal, heroico y iron, pero cada vez que me salgo del app y vuelvo a entrar me sale que aun no he pasado el heroic y iron. Me paso lo mismo con la mission anterior de esa y recién fue que cuando me pase directo al Dark Decent (sin haber concluido el heroic y el iron) que se me grabó. Pero la idea tampoco que sea así, sino como era antes que se iba actualizando bien el progreso."

**Comment by cigumo** [comment]
fixed in #33
