### ISSUE TITLE
razorboar charging speed slower than mobile / sunnydaler

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#299]

**Comment by sunnydaler** [comment]
On mobile, the first Razorboar in wave 3 of The Ascent can kill level-1 barracks (three soldiers) at once with Burning Charge.
On Steam, it cannot.

**Comment by sunnydaler** [comment]
https://cdn.discordapp.com/attachments/423213564644556822/496970156552093707/mobile_Razorboar.gif
https://cdn.discordapp.com/attachments/423213564644556822/496970274923610112/Steam_Razorboar.gif

**Comment by cigumo** [comment]
ipad and iphone uses different speed increments for razorboar (1 and 3). 
changed steam from 1 to 2.
