### ISSUE TITLE
Mohd: progress not saved but achievements are

### ISSUE THREAD

**Issue by luciag27** [cigumo/krli#30]
Mensaje: 
"I have problem with cloud storage kingdom rush frontier.
My device xiaomi mi a1 latest version android oreo. 
My purchase hero sync to my new device but not my game progress. "

Le pregunte: "When you level up a hero or complete a stage, if you exit the game and go back in, do you have that progress saved?" A lo que contestó que si.

**Comment by cigumo** [comment]
@luciag27 sabes si le funciono en  3.0.26?
