### ISSUE TITLE
Drider attack different from mobile / sunnydaler

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#304]
"1 basic - poison - 8 basic - poison" on mobile
poison -- 5 basic attacks - poison on steam

drider attack speed slower on steam?

**Comment by cigumo** [comment]
> [6:18 AM] sunnydaler: Steam Drider's poison damage is different from mobile.
> [6:20 AM] sunnydaler: on mobile, 84 damage (2 dmg. per 7 frames)
> [6:20 AM] sunnydaler: on Steam, 98 or 100 damage (2 dmg. per 6 frames)

**Comment by cigumo** [comment]
Each generation of Driders spawns increases the poison cooldown by 5 seconds. Was the 8 basic attacks one a first gen drider?

**Comment by sunnydaler** [comment]
The firtst drider from the west in shrine of elynie iron.
