### ISSUE TITLE
Niloo: game isn't being saved

### ISSUE THREAD

**Issue by luciag27** [cigumo/krli#31]
Mensaje original:
"Since the recent update my game isn't being saved anymore.  I finished the Emberspike Depth and got the three new levels but when i finish them, it doesn't save them. The flag remains red and it doesn't progress to next level even though i finished with 3 stars"

![image](https://user-images.githubusercontent.com/30800937/37977041-52249470-31b9-11e8-9aa7-fe2a23219790.png)

galaxy note 4 and android version 6.0.1

**UPDATE:**

"I just did a software update on my phone and the gamenis fixed and levels are being saved again."

![image](https://user-images.githubusercontent.com/30800937/37977105-79c1a568-31b9-11e8-8d26-08657bb29359.png)
![image](https://user-images.githubusercontent.com/30800937/37977119-802d74a4-31b9-11e8-8259-5f35833a768c.png)

**Comment by cigumo** [comment]
fixed in #33

**Comment by cigumo** [comment]
@luciag27 te podra dar mas info sobre el mensaje de cloud saving?
