### ISSUE TITLE
Yingdi: heroes don't show up (comprados con otra cuenta)

### ISSUE THREAD

**Issue by luciag27** [cigumo/krli#32]
Mensaje original: 
"All of my in app purchases (8 heroes) don't show up after recent update."
El Restore no le funciona aparentemente. 

![image](https://user-images.githubusercontent.com/30800937/37983122-e02f5412-31c8-11e8-91b8-1c662f34e346.png)

**Comment by luciag27** [comment]
pixel 2， Android 8.1

**Comment by cigumo** [comment]
Investigar si cambiaron los ids de esas ofertas. 
Tambien es raro que que haya pago por el KRF luego de comprar los IAP.

**Comment by luciag27** [comment]
Le pregunte y me dijo
"At first, I installed the game using other’s google account. And later I found it is really a good game then I bought it with my own account."

**Comment by cigumo** [comment]
¿No habrá comprado los heroes con la otra cuenta también?
Creo que vamos a precisar algo similar a lo del Iron Marines, que le mandemos un link y le podamos cargar heroes o desbloquear cosas.

**Comment by luciag27** [comment]
Me pareció que podía ser lo de otra cuenta pero le pregunte y me dijo que previo al update podía usarlos lo mas bien, entonces me parecio raro. 
Lo del Iron Marines es ideal.

**Comment by cigumo** [comment]
Los podia usar porque en el savegame del viejo se mantenian los heroes aunque la cuenta cambiase. Se guardaban en el savegame, porque no tenían sincronizacion de IAPs luego de la compra salvo que apretase el boton de restore abajo del heroe manualmente. 
En la versión 3 se sincronizan con la cuenta de IAPs cada vez que se arranca el juego y también funciona aunque el device este offline (porque tiene un cache). 

Es un caso raro... comprar con una cuenta y usar otra. Suena a "mi amigo me paso los heroes" jaja. 
De todas formas creo que lo mejor es implementar aunque sea una parte de lo del Iron Marines.

**Comment by luciag27** [comment]
Ahh, y qué podemos hacer entonces en este caso?
Debería hacerle un refund de los héroes?

**Comment by cigumo** [comment]
Creo que lo mejor es implementar lo del Iron Marines y verlo caso por caso. 
Veo de hablarlo con Lito.

**Comment by luciag27** [comment]
Ok, espero entonces.

**Comment by cigumo** [comment]
si, decile que se lo vamos a solucionar de alguna forma en el proximo update.

**Comment by cigumo** [comment]
@luciag27 por como esta programado esto no podemos darle heroes con un token como iron marines. Si lo voy a implementar en algun momento para nivelacion de heroes, desbloqueo de niveles, y gemas. 

La solucion es mandarle promo codes por los heroes que le faltan, o uno con todos los heroes y chau :)  ¿Te quedan?  Sino habría que pedirle a Billy.

**Comment by cigumo** [comment]
@luciag27 le mandaste promos?
