### ISSUE TITLE
wild magus eldritch fails on teleport / sunnydaler

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#321]
https://streamable.com/w15ts

the explosion is shown in the teleported bandersnatch anyway.

**Comment by sunnydaler** [comment]
if the target is teleported within WM's range, Wild Magus can change Eldritch Doom's angle in the process, killing the target.

**Comment by cigumo** [comment]
changed in 1.2.0 so eldritch always wins and removes teleports.
