### ISSUE TITLE
When the Unseelie Court campaign is restarted, the intro is not skipped 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#322]
it is skipped on mobile.

**Comment by sunnydaler** [comment]
there has to be consistency across the kr games.
Shrine of Elynie campaign has an intro on mobile but not on Steam. and
 the krv mobile has some stages with an intro and they are not skipped on restart.

**Comment by cigumo** [comment]
made bot intros skippable on restart. 
fixed in 1.2.0
