### ISSUE TITLE
Grip of Darkness damage is strange

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#325]
|Barracks\Platform |Steam| Android |
| ------------- | ------------- |------------- |
| Warden Barracks  | 84 (56) | 81 (81) |
| Ranger Barracks  | 56 (56)  | 81 (54)  |
| Bladesingers  | 56 (56) | 81 (54)  | 
| Forest Keepers | 140 (112)  | 135 (135) | 

Values in parentheses are the results with level-3 upgrade on tech tree.

**Comment by cigumo** [comment]
fixed to be the same as mobile.
