### ISSUE TITLE
Tesla tower's Overcharge actually deal more damage than in-game descriptions. / sunnydaler

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#328]
>   Tesla tower's Overcharge actually deal more damage than in-game
>   descriptions.

**Comment by sunnydaler** [comment]
This nerf requires intensive test to verify it does not break game in veteran mode.

**Comment by sunnydaler** [comment]
Oh... there was a miscommunication on this issue. I meant not KRF Dark Forge but KR original's Tesla x104.
I am closing this issue.
