### ISSUE TITLE
Bravebark's Branchball health limit / sunnydaler

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#347]
Even though the description says "any enemy" at level 3, 
it cannot be used on an enemy over 1500 health.

Big Bad Bug told me that mobile version has the same bug and really wanted it to be fixed.

I hope you just remove the limit, without changing the description. :-)

**Comment by cigumo** [comment]
Asked Gerson and we will remove the limit, except for bosses and mini bosses of course. 
:)

**Comment by cigumo** [comment]
fixed in v 1.0.5
