### ISSUE TITLE
Matheus: UI numbers are missing

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#35]
![image](https://user-images.githubusercontent.com/30800937/37973307-9385d090-31b0-11e8-8bad-336592da1313.png)

**Comment by cigumo** [comment]
duplicate of #25

**Comment by luciag27** [comment]
Update del mensaje:
"In this level (the next one I wasn't reaching last time) the GUI keeps hiding some of the text."

![image](https://user-images.githubusercontent.com/30800937/38211024-8783a7c0-368f-11e8-8180-7cb524b29c8e.png)

**Comment by luciag27** [comment]
Solo pasa en el level 5, jugo más juego y no se reprodujo en ningún otro nivel.

**Comment by cigumo** [comment]
duplicate
