### ISSUE TITLE
Hajjar: tapping doen't respond (sometimes) / zenfone 2

### ISSUE THREAD

**Issue by luciag27** [cigumo/krli#39]
Mensaje original:
"I bought the games KR origins and KR Frontiers. This last one, has been acting erraticaly since 2 months ago. The button of skills of the hero or placing the troops have a functionality bug making it that sometimes the tapping does not respond, damaging highly the game performance.
Since I bought it, I deleted the game and reinstalled it, finding the same issue."

ASUS_Z00AD
Android v. 5.0
KR2-phone-3.0.25-5-G9010860

**Comment by cigumo** [comment]
imposible de probar/reproducir
