### ISSUE TITLE
Pablo Terraga : donde estan mis partidas guardadas?

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#40]
> El juego es genial pero dónde están mis partidas guardadas? Al desinstalar y reinstalar, aunque se sincroniza con google y veo todos los logros, no aparecen mis partidas. Dice que sincroniza con la nube, pero no.   Increíble haber pagado por esto.

https://play.google.com/apps/publish?account=6098018911218203911#ReviewDetailsPlace:p=com.ironhidegames.android.kingdomrushfrontiers&reviewid=gp:AOqpTOEg1BacZH1eGPF82Gy7iYWwq0hhxWnlVPAXV8-vbAD1M-YjsA15YrnS-StYj-DlNxQNfmgAlnmX5LM0cg

**Comment by luciag27** [comment]
Update: comenzó a testear la beta.
