### ISSUE TITLE
Malicia walks very fast on Steam.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#407]
https://streamable.com/q2awk
https://streamable.com/7lgmr
https://streamable.com/3z5fk  (regson)

**Comment by cigumo** [comment]
I cannot reproduce it. 
Tried alone and combinations of: 
- scourger lash
- forest keepers vine
- bravebark ultimate (levels 3 and 5)

If anybody can reproduce it please let me know!!
A sshot of the tower setup will also be helpful.

**Comment by cigumo** [comment]
Also happened to VirtualTT and SealDarkLight
![turbo_malicia](https://user-images.githubusercontent.com/934821/49182818-0c035d80-f33a-11e8-9eec-a9bb14712b08.gif)

**Comment by guaranteed-to-be-unique** [comment]
My tower setup: Wild Magus - Eldrich Doom, Weirdwood - both upgrades maxed, Forest Keepers - spear and heal maxed, Golden Longbows - both upgrades, but not maxed, gnomes - all maxed. Also I should mention that speedup seem to happen only after Malicia retreats and returns back. At least I've never seen it happening during initial encounter.
![2019-01-11_230806](https://user-images.githubusercontent.com/22380626/51057341-5c86ff80-15f6-11e9-9adf-3af9433590c7.jpg)

**Comment by cigumo** [comment]
Is it related to gnomes??
Happened to me with gloomies too

**Comment by cigumo** [comment]
found!!! yes! 
fixed in 1.4.1-alpha-31
