### ISSUE TITLE
Shroom Says achievement bug

### ISSUE THREAD

**Issue by luciag27** [cigumo/krli#414]
I've done it and went beyond the required repeats of 9; I've went to the maximum, which is 13, if I'm correct.

And I think the very last, 13th repeat, actually offers no gold reward, while all the previous ones do. It makes no sense for the 13th pattern to give no gold reward if all the previous ones do.

https://steamcommunity.com/app/816340/discussions/0/1734342161870892247/

**Comment by cigumo** [comment]
sunnydaler and I could not reproduce this bug.
