### ISSUE TITLE
Di Vi: after level 5 screen goes black (chromebook)

### ISSUE THREAD

**Issue by luciag27** [cigumo/krli#42]
Mensaje original: 
"i purchased this game today (31/03). it was working fine until i got to level 4. the screen goes black. fix this please"

"I have it downloaded on my chromebook.  I then downloaded it on my android which is working well and made progress, only that i prefer playing it on chromebook because the screen is larger and my hubby would like to play  it there too". 

"When i play on chromebook, it turns black(i can only hear the sound) in between the game, so im not progressing. I only make progress when i play on my phone which i dislike due to it smaller screen".

**Comment by cigumo** [comment]
@luciag27  this should have been solved with the latest release.
