### ISSUE TITLE
Wave icon is missing for the wave 14 of The Ascent / DarkSide

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#429]
DarkSide says, "In wave 13 or 14 it tells 2 razorboars will come. But actually more do".

sunnydaler says, "Steam shows only 2 upcoming wave icons (2 of "1 razorboar") for wave 14 at the right entrance,  while the mobile shows 3."

**Comment by sunnydaler** [comment]
1st razorboar heads to north directly.
2nd goes to north (via east portal and lower portal)
3rd goes to south (via east portal and lower portal)
4th goes to north (via east portal and upper portal)
5-7th go to north directly.

**Comment by cigumo** [comment]
overlapped?
<img width="72" alt="screen shot 2018-11-21 at 9 45 38 am" src="https://user-images.githubusercontent.com/934821/48842156-42593f80-ed72-11e8-95ac-0c75a2d22aed.png">

**Comment by cigumo** [comment]
fixed. 
![screen shot 2018-11-21 at 9 52 50 am](https://user-images.githubusercontent.com/934821/48842564-5b162500-ed73-11e8-87e7-7b351c3b0927.jpg)
