### ISSUE TITLE
Korean tranlation of Harasser / sunnydaler

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#433]
right now it was translated to assassin. 

two suggestions: 
- spell english harasser with korean characters: 허래서
- use the skirmisher translation: 산병, or 척후병

**Comment by cigumo** [comment]
also check texts in
https://docs.google.com/spreadsheets/d/1-M__pGxA-WFO4qnFWUKzf2d0dOE6p-qQlqa1gImo_lg/edit#gid=0

**Comment by sunnydaler** [comment]
Lets leave it like it is.
A Krv tower has same name.
