### ISSUE TITLE
Facu: no se guardan las partidas

### ISSUE THREAD

**Issue by luciag27** [cigumo/krli#44]
Mensaje original: 
"Hola buenos dias, estos ultimos dias las partidas del juego kingdom rush frontier no se han estado guardando es decir que todas las partidas que jugue nose quedan guarda en el juego e invertido dinero no solo comprandolo si no tambien e comprado a los heroes de pago me gustaria que lo arregluen por favor, Gracias!"

Samsung Galaxy J7 Modelo 2016

**Comment by cigumo** [comment]
@luciag27 que pruebe con 3.0.26 (en credits aparece como 3.0.25-5 por un error mio)
