### ISSUE TITLE
Wrong display on wave icons in Beheader's Seat campaign.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#446]
![1](https://user-images.githubusercontent.com/43391939/48661007-a0ee9700-eaae-11e8-9f9f-11c0822f432a.jpg)
![2](https://user-images.githubusercontent.com/43391939/48661000-81f00500-eaae-11e8-8b07-5fdae01786b4.jpg)
![3](https://user-images.githubusercontent.com/43391939/48661001-82889b80-eaae-11e8-8e80-2cae23b061de.jpg)
![4](https://user-images.githubusercontent.com/43391939/48661002-83b9c880-eaae-11e8-88d8-414d9a304056.jpg)
![5](https://user-images.githubusercontent.com/43391939/48661003-86b4b900-eaae-11e8-941d-ef3b2213e318.jpg)

**Comment by cigumo** [comment]
fixed!
