### ISSUE TITLE
Lililth's ultimate; Fallen Angels damage is glitched.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#447]
Tested it against Avenger and Heretic.
result:
level 0, 50 damage x 6 attacks (total 24 dmg to avenger, 300 dmg to heretic)
level 1, 100 damage x 8 attacks (total 72 dmg to avenger, and 800 dmg to heretic)
level 2, 80 damage x 10 attacks  (total 70 dmg to avenger, and 800 dmg to heretic) 
level 3, 100 damage x 12 attacks (total 108 dmg to avenger, and 1200 dmg to heretic)
 

on android, it deals true damage.
level 0, 25 damage x 12 attacks = 300 dmg
level 1, 50 damage x 16 attacks = 800 dmg (the damage is the same as level 2. this looks like a bug.)
level 2, 40 damage x 20 attacks = 800 dmg
level 3, 50 damage x 24 attacks = 1200 dmg

**Comment by cigumo** [comment]
Changed: 
- set to true damage
- lowered level 1 damage to 512 total damage  (8 x 64 damage)
