### ISSUE TITLE
Syed: game achievements not syncing with Google Play

### ISSUE THREAD

**Issue by luciag27** [cigumo/krli#45]
Mensaje original: 
"Game achievements not syncing with Google play. Missing the google play icon on start screen."

"I have tried playing the game using Google Play and by directly tapping on the game icon.
My device is Huawei Honor 5X, OS is 6.0.1."

**Comment by cigumo** [comment]
@luciag27 podra mandarnos un screenshot de la start screen para ver a que se refiere con que no tiene el google play icon?
