### ISSUE TITLE
Malik's  Earthquake damage is lower.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#452]
![youngmalikearthquake](https://user-images.githubusercontent.com/43391939/48669196-7ea65900-eb42-11e8-9208-a5e9245c1cd0.png)
And also the stun stars are not displayed.

|Earthquake skill level (Malik hero Level) |Steam (Gnawer/Ogre)| Android (Gnawer/Ogre)|
| ------------- | ------------- |------------- |
| 1 (4)| 0* / 25  | ?? / 25 |
| 2 (7)|  30 / 50 | ?? / 100  |
| 3 (10)| 90 / 150  | 165 / 375 | 

*Gnawer is not stunned.

**Comment by cigumo** [comment]
I've teted Level 10 + Ogre Magi and I can't have it make more than 225 damage on mobile. 
The steam version was wrong, but I think it's not 375 but 225. 
Fixed the stun texture not appearing.
