### ISSUE TITLE
Eridan has dead distance between melee and ranged / TomikPlay

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#454]
![20181118154406_1](https://user-images.githubusercontent.com/934821/48732761-3d37ab80-ec1f-11e8-889c-098219902032.jpg)

**Comment by cigumo** [comment]
I can't reproduce this one.

**Comment by sunnydaler** [comment]
experienced this twice recently.

**Comment by sunnydaler** [comment]
https://i.imgur.com/gTU8HEk.mp4

**Comment by cigumo** [comment]
Fixed in 4.0.01
Changed melee and min ranged to 135/2.
