### ISSUE TITLE
Check Malik's XP point

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#458]
Steam Malik seems to level up faster.

**Comment by cigumo** [comment]
I can see it levels up faster but cant' find the error. 
Enable xp debugging on mobile.

**Comment by cigumo** [comment]
The bug was smash attack not considering minimum enemies and triggering a lot more often. 
Now both, mobile and steam, ramp up approximately at the same speed.
wave/malik level: 4/1, 6/4, 8/6, 10/9

fixed in 1.2.0
