### ISSUE TITLE
Ettin does not regenerate health under the efffect of Catha's ultimate and pixie's curse / sunnydaler

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#459]
also check Ettin and Magi regens under stuns.

**Comment by sunnydaler** [comment]
This is fixed

**Comment by sunnydaler** [comment]
Enemies regen under all stun. (slumber arrows, clobber, catha, celebrity, king's roar, demon, magical shackles, hammertime, xin's daring strike and ulti.)
