### ISSUE TITLE
Nitsch: no coins for calling early waves on endless mode

### ISSUE THREAD

**Issue by luciag27** [cigumo/krli#46]
Mensaje:
"My Samsung Galaxy S7 has the latest Android available and the latest Kingdom Rush games available, and in Frontiers endless mode I don't get coins for early waves anymore. Ruins my Cpt. Blackthorne tactics :("

I believe since the update that changed the in-game font, and when the playfield got a little wider near the edges (at least in the endless round)

**Comment by cigumo** [comment]
si, estaba mal.
arreglado en v3.0.27
