### ISSUE TITLE
Durax's movement speed in long distance is slower.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#467]
![the distance steam durax moves in a sec](https://user-images.githubusercontent.com/43391939/48913763-c15a8f00-eebc-11e8-8416-8a70528f94af.jpg)
![the distance mobile durax moves in a sec](https://user-images.githubusercontent.com/43391939/48913765-c1f32580-eebc-11e8-83fe-5d4e87a82dcd.jpg)
Pictures show the distance Durax moves in a second on each platform.

Razz moves at the same speed on both platforms.
Lilith is very slightly slower on Steam.

**Comment by cigumo** [comment]
fixed in 1.2.0
