### ISSUE TITLE
Bloodsydian has no electric arc around it.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#468]
on mobile, it looks like this:
![mobile bloodsydian](https://user-images.githubusercontent.com/43391939/48916634-662d9a00-eec6-11e8-9193-4b5324eb7d95.gif)

**Comment by cigumo** [comment]
yes... only happens before the first wave :)
don't ask!

**Comment by cigumo** [comment]
fixed in 1.2.0
