### ISSUE TITLE
Loss of control of Durax's copy 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#473]
![20181123061919_3](https://user-images.githubusercontent.com/43391939/48922199-6179dd80-eee8-11e8-9bac-cd7784f7e94e.jpg)
If it goes too deep into the temple or tunnel, it is not possible to move the copy out of it.
the right most one in the screenshot.

Another place this can happen is: the tunnels where Zealot spawns,

**Comment by cigumo** [comment]
fixed
