### ISSUE TITLE
Next wave auto sent / VirtualTT

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#488]
> It seems that there is a bug with sudden next wave activation. I think this happens when you press left mouse button to set target for some ability (for example Arrow Storm) just prior to next wave pop up and then releasing mouse button may summon next wave. This does not happen every time, but definitely on regular basis.

**Comment by cigumo** [comment]
I could not reproduce it.

**Comment by guaranteed-to-be-unique** [comment]
Still happens on v1.3.2
https://streamable.com/7lq00
dunno how to stably reproduce it though

**Comment by sunnydaler** [comment]
it happened on kr1 debug build also.
My hands were not on either mouse or keyboard when it happened.

**Comment by cigumo** [comment]
https://github.com/cigumo/krli/files/4309672/next_wave_auto_sent.txt

**Comment by cigumo** [comment]
wave 14 called right away
![kr1-love-wave-called-right-away-400h mov](https://user-images.githubusercontent.com/934821/76270297-887e2f00-6253-11ea-8598-bad19c342c61.gif)

**Comment by cigumo** [comment]
click in previous wave happens after the wave flags start fading and it's queued for the next wave
![kr1-love-wave-called-right-away-click-in-prev-wave mov](https://user-images.githubusercontent.com/934821/76272387-15c48200-625a-11ea-893f-3c05eaea8b1c.gif)

**Comment by cigumo** [comment]
fixed in:
- kr1-desktop-4.0.08
- kr2-console-3.2.23
