### ISSUE TITLE
Check the CD of the merged bloodsydian's arc animation 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#506]
you know that there are two animations for the gem's electric arc.
one for the fragmented one, 

another for the merged one.

The later's CD is too short on Steam. and is played two or three times in a row.
On mobile, its CD is longer . I mean when there's no targets around.

On mobile I can use the animation as a useful indication that the targets are in its range and the gem is going to use the power in a sec.

**Comment by cigumo** [comment]
@sunnydaler are you sure it changes? 
from the original code I can see it's just random.

**Comment by cigumo** [comment]
I was waiting frames, not seconds. 
fixed in 1.2.1
