### ISSUE TITLE
Mobile Veznan's demon burns enemy with its melee attacks

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#528]
In Steam, its melee attack leaves no flame on the opponents.

**Comment by cigumo** [comment]
I can see the flame.
<img width="164" alt="screen shot 2018-12-17 at 9 05 21 pm" src="https://user-images.githubusercontent.com/934821/50123454-7a538580-023f-11e9-8e59-e55ba554de5b.png">

**Comment by cigumo** [comment]
fixed in 1.2.5
