### ISSUE TITLE
Heretic freezes for unknown reason.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#530]
https://streamable.com/51q18

**Comment by cigumo** [comment]
also https://steamcommunity.com/app/816340/discussions/1/2521353993649821444/

**Comment by sunnydaler** [comment]
It seems to happen in this scenario.
A soldier/hero is about to engage in melee with an enemy, and fails to do so. 
Then, the enemy freezes.
https://streamable.com/1n22f Mounted Avenger freezes for the above reason, I think.

**Comment by cigumo** [comment]
I've made a fix in 1.3.3 that solves this problem.
