### ISSUE TITLE
Bonus barracks' rally point at the start of Royal Gardens campaign

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#531]
in Heroic and Iron, the rally points of the bonus barracks are identical to mobile counterparts.

but the barracks in the campaign is placed differently at the beginning.
![campaign](https://user-images.githubusercontent.com/43391939/49658027-6318d900-fa84-11e8-87ad-e127a5957200.jpg)

![screenshot_20181208-005645](https://user-images.githubusercontent.com/43391939/49658014-58f6da80-fa84-11e8-8966-0836bbe543db.png)

**Comment by cigumo** [comment]
fixed in 1.2.5

**Comment by sunnydaler** [comment]
This was fine in 1.2.6 but is reverted in v 1.3.1 and 1.3.2. How did it happen?
I don't know how it was in v 1.3.0.

**Comment by cigumo** [comment]
fixed again in 1.3.3
