### ISSUE TITLE
mobile Arivan's freeze stops Ettin and Ogre Magi from regenerating.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#532]
mobile ogre magi: https://streamable.com/tf1bm
mobie ettin: https://streamable.com/ud9k8
Icy Prison and Elemental Storm
 it is not true on Steam.
Which one is glitched?

**Comment by cigumo** [comment]
changed in 1.4.3 so auras will not regen when frozen (arivan, faerie dragons, etc.)
