### ISSUE TITLE
Hero and soldiers do not attack Blood Ogre which was teleported by crystal / DancheZi

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#539]
DancheZi: I WAS PLAYING LAST LEVEL OF R2. BLOOD OGRE (from wave 8) JUST PASSED OVER MY SOLIDERS, REINFORCEMENTS AND LILITH. AND I LOST 3RD LIFE
sunnydaler: did towers attack it?
DancheZi: yes (Danche is not so sure about this)
sunnydaler: was it teleported before?
DancheZi: i think it is by crystal
sunnydaler: did the enemy attack your soldiers?
DancheZi: no

**Comment by cigumo** [comment]
fixed in 1.2.5
