### ISSUE TITLE
Perythons don't drop stone/Gnawer when affected by Catha's sleep.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#542]
https://streamable.com/zu59c

**Comment by cigumo** [comment]
fixed in 1.2.5

**Comment by cigumo** [comment]
Mobile version Perythons react like this:  
    
event name      | internal      | drops | notes 
----------------|---------------|---------|----- 
death           |               | yes   |
flying heroes   |               | yes   | bug or feature?
king's roar | stun      | yes  |
mage teleport   | teleport      | no    |
unstable tele   | teleport      | no    |
faustus tele    | teleport      | no    | possible when positioned off the the birds' path
faerie dragon   | freeze        | yes   | never happens
elemental storm | slow        | yes   |
timelapse       | timelapse     | yes   |
catha curse     | stun          | yes   |
slumber arrow   | stun          | yes   |
denas celebrity | stun          | yes   |
veznan demon    | stun          | yes   |
veznan shackles | stun          | yes   |
veznan soulburn | stun          | yes   |
regson vindicat | stun          | yes   | but after the explosion... weird
eldritch doom   | stun          | no    |  werid case
xin ulti        | stun          | no    | does not hit flying enemies
rag hammertime  | stun          | no    | does not hit flying enemies

**Comment by cigumo** [comment]
differences in steam: 
- elemental storm does not drop load
