### ISSUE TITLE
Faustus's hit animation is different from mobile.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#543]
Steam: 
![steam faustus](https://user-images.githubusercontent.com/43391939/49726025-67c1d500-fcb0-11e8-9562-77ca3d7af9ec.gif)

Mobile:
![mobile faustus](https://user-images.githubusercontent.com/43391939/49726047-73ad9700-fcb0-11e8-9637-de1845a5a34b.gif)

I circled the relevant sprites black. (this png file is from mobile version.)
![elves_hero_faustus_2-hd](https://user-images.githubusercontent.com/43391939/49726188-c12a0400-fcb0-11e8-933f-282a1bec0d3c.png)

**Comment by cigumo** [comment]
fixed in 1.2.5
