### ISSUE TITLE
"Malik Unchained" pops up too early.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#544]
steam: https://streamable.com/5wxnj
The achievement notice pops up as soon as Thunderbolt hits Gnawers that watch Malik.
![steam](https://user-images.githubusercontent.com/43391939/49787068-03af1780-fd69-11e8-9607-2f8d4c1da168.jpg)

mobile version: https://youtu.be/YPcHx6SX6pE?t=215
This is not my video, but I remember this is how it is.
![mobile](https://user-images.githubusercontent.com/43391939/49786920-a5823480-fd68-11e8-9b0e-5afcfc1d4142.jpg)

**Comment by cigumo** [comment]
changed in 1.2.5
moved it a little late even. 
https://streamable.com/56ira
