### ISSUE TITLE
HEM sometimes shoots less than 3 bolts.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#548]
![hem shoots 1 bolt](https://user-images.githubusercontent.com/43391939/49846503-d9179a00-fe0e-11e8-9f35-fae3014ee912.gif)
![hem shoots 2 bolts](https://user-images.githubusercontent.com/43391939/49846507-da48c700-fe0e-11e8-9916-42b52ae2e25e.gif)
![hem shoots 2 bolts b](https://user-images.githubusercontent.com/43391939/49847262-8cce5900-fe12-11e8-836a-83d7e91b6339.gif)
![hem fail](https://user-images.githubusercontent.com/43391939/49847326-e33b9780-fe12-11e8-923e-892f09339491.gif)
Sometimes HEM shoots only 1 or 2. and other times it fails to shoot.
link for the full vid https://streamable.com/z4376

**Comment by cigumo** [comment]
fixed in 1.2.5
