### ISSUE TITLE
Instakill and Freeze interactions

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#549]
When instakilled, bloody animation is shown, but the enemy's sprite remains on the screen for a while.

1. Icy Prison + Crimson Sentence: https://streamable.com/3tsr6

2. Faery Dragon + Vindicator: https://streamable.com/yykvd

(Eldritch Doom works alright on a freezed target. https://streamable.com/jjlep)

**Comment by cigumo** [comment]
fixed in 1.2.5
added new flag: unit.hide_during_death that freeze checks before showing the original sprite
