### ISSUE TITLE
review blood ogre range and target selection concurrency

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#558]
- [ ] check range
- [ ] check two ogres targeting the same targets

**Comment by sunnydaler** [comment]
![steam](https://user-images.githubusercontent.com/43391939/50232367-1de59700-03f4-11e9-98d2-e4279e070734.jpg)
range seems to be fine.

vid on targeting.
https://streamable.com/mgrty
I think this has something to do with issue # 533.
