### ISSUE TITLE
bram freeze / sunnydaler

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#559]
https://streamable.com/b9e2k

**Comment by cigumo** [comment]
I need help reproducing this one. Thanks!

**Comment by guaranteed-to-be-unique** [comment]
I think this is a problem with Razz&Rags instead, all kinds of enemies fighting him in melee combat freeze sometimes.

**Comment by cigumo** [comment]
I think this was fixed in kr-love/57f0ba47ed2f138a243932e46917e062ae82f4be
verison 1.3.5
