### ISSUE TITLE
Gnolls during Bloodsydian transformation.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#561]
v 1.2.6
![gnoll killed](https://user-images.githubusercontent.com/43391939/50315633-df84d080-04f6-11e9-9cdf-8a203c33d3f2.gif)
![gnolls killed 1](https://user-images.githubusercontent.com/43391939/50321718-8a0bec00-0515-11e9-97fc-d5ea8c13e895.gif)

- Health bar is shown.
- can be targeted by towers and spells.

**Comment by cigumo** [comment]
fixed in 1.3.1
