### ISSUE TITLE
Malik's Earthquake sometimes does not stun enemies.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#562]
Even the nearest enemy 

https://youtu.be/RH0tjg9Wrg4?t=345     https://youtu.be/RH0tjg9Wrg4?t=392

https://youtu.be/sYNduFF1OiU?t=224    https://youtu.be/sYNduFF1OiU?t=270

https://streamable.com/rrxvd

https://streamable.com/l8i7h

https://streamable.com/p98kp

**Comment by sunnydaler** [comment]
I have not seen Malik fail to stun enemies with this attack on mobile version.

**Comment by cigumo** [comment]
increased aura radius 33% to avioid missing enemies in the highest hero level.
changed in 1.4.3.
