### ISSUE TITLE
The slave patrol Gnawer on the right is not aimable with Thunderbolt

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#563]
To free Malik from slavery, one has to cast Thunderbolt on the Gnawers that watch over him.
on mobile, I can aim either of the two Gnawers.
on Steam, X sign is displayed when I try to cast the spell on the Gnawer on Malik's right side.
![free malik](https://user-images.githubusercontent.com/43391939/50464651-7fe66380-09d5-11e9-8fc8-52afd0ffae13.gif)

**Comment by cigumo** [comment]
fixed in 1.3.1
