### ISSUE TITLE
Golden Longbow sfx problems.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#565]
https://streamable.com/nia35

- [x] Sound_ArrowRelease2.ogg is used for the arrow release, instead of the kr3_sfx_goldenbow_arrowshot.ogg.

- [x] Hunter's Mark arrow sfx (kr3_sfx_goldenbow_flareshot_v2-convoz.ogg) slightly lags behind the animation. It is more apparent in short range.

**Comment by cigumo** [comment]
fixed in 1.3.1
