### ISSUE TITLE
Forest Keepers do not throw upgraded spears to the enemies they are blocking.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#567]
I upgraded FKs with Ancient Oak Spear and Eerie Gardener, then tested them against a single Twilight Avenger.

On mobile: https://streamable.com/90i73
FKs throw spears to the Avenger they are blocking. but do not use Eerie Gardener to the enemy.
(FKs do not throw normal spears to the enemy they are blocking though.)

On Steam: https://streamable.com/rqqbn
FKs do not throw spears in that situation. but still use Eerie Gardener to the Avenger.

------------
On mobile, FK's Oak Spear throw is not disabled even when they are fighting in melee. But normal spear throw is disabled. And Eerie Gardener is used on the enemies that are moving. But does not target enemies that are stunned or blocked.

**Comment by cigumo** [comment]
fixed in 1.3.1
