### ISSUE TITLE
Runed Bears' sfx problems.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#568]
- [x] Death sound is missing on Steam. The filename is kr3_sfx_druidhenge_beardeath_v3_op1-condesplome.ogg

- [x] Even though there exists a separate sound file for bear attack (kr3_sfx_druidhenge_bearattack_v4-op1.ogg), 
 android version uses bear summon sound --this must be a bug--, and steam version uses the common barracks fight sound.

**Comment by cigumo** [comment]
fixed in 1.3.1
