### ISSUE TITLE
Thunderbolt's slowdown factor

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#571]
On mobile,
level 3 Thunderbolt (Thunderstorm) reduces enemies' speed by 40%.
level 4 Thunderbolt (Monsoon) slows enemies down by 60%.

On Steam,
they are reversed.
![level3 thunderbolt](https://user-images.githubusercontent.com/43391939/50554607-d834a280-0d00-11e9-97c0-91de52438632.jpg)
Thunderstorm slows down by 60% 

![level4 thunderbolt](https://user-images.githubusercontent.com/43391939/50554605-d4088500-0d00-11e9-8e82-872d345109f0.jpg)
and Monsoon slows down by 40%.

**Comment by cigumo** [comment]
fixed in 1.3
