### ISSUE TITLE
Eldritch Blade should have a chance of slaying.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#575]
On Steam, Eldritch Blade's instakill never seems to proc.

The following gif is from mobile version.
![mobile eldritch blade](https://user-images.githubusercontent.com/43391939/50629573-7a15f280-0f80-11e9-9ec9-9a7fcfa7813d.gif)

**Comment by cigumo** [comment]
I think the attacks are not resorted after they are changed in berkserk mode, so the lower chance instakill is never processed.

**Comment by cigumo** [comment]
fixed in 1.3.1
