### ISSUE TITLE
when Kingsguard's lifetime is up, they are auto-killed.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#576]
In this instance, they should disappear like on mobile.

mobile: 
![mobile](https://user-images.githubusercontent.com/43391939/50685783-e87cb280-105d-11e9-9b3b-cbbc7375ff11.gif)

Steam:
![steam](https://user-images.githubusercontent.com/43391939/50685820-1661f700-105e-11e9-8b96-6c7b4ddf9c30.gif)

**Comment by cigumo** [comment]
fixed in 1.3.1
