### ISSUE TITLE
Missing animations in Bravebark's attacks 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#577]
![basic attacks](https://user-images.githubusercontent.com/43391939/50637798-b9ebd280-0f9e-11e9-9bda-dda7a2736bdd.jpg)
left: mobile, right: Steam
- [ ] In mobile version, his hit impact makes cracks in the ground and dust arises like the boulder explosion. 

![branchball](https://user-images.githubusercontent.com/43391939/50637688-5366b480-0f9e-11e9-8d2b-b1a27ffc6da0.jpg)
left: mobile, right: Steam
- [ ] In mobile version, Branchball leaves a cavity in the ground. 

---------------------------

mobile:
![mobile bravebark](https://user-images.githubusercontent.com/43391939/50637291-ba836980-0f9c-11e9-8782-e963a396a5bf.gif)

Steam:
![steam bravebark](https://user-images.githubusercontent.com/43391939/50637429-58773400-0f9d-11e9-95b7-c48f1b29c223.gif)

.

**Comment by cigumo** [comment]
fixed in 1.3.1
