### ISSUE TITLE
Poisoned units should not spawn Drider unless killed.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#578]
Currently, poisoned units spawn Drider (and Shadowspawn on mobile) if their lifetime is up while being afflicted.
https://streamable.com/mbwje
![soldier spawning drider](https://user-images.githubusercontent.com/43391939/50682249-99308500-1051-11e9-953c-ab829c4db67c.gif)
They neither died of poison nor were killed while under the affliction. 

I think Greenlings, Reinforcements, Pixie Warriors, and Kingsguards should not spawn Drider (or Shadowspawn) if their health is sufficient to stay "not dying" until their time is up.
They should just disappear without spawning anything.

**Comment by cigumo** [comment]
greenlings are poison resistant. there's another ticket for that, but the rest should be fixed in 1.3.1
