### ISSUE TITLE
Harasser should not shadow-jump and dodge Branchball.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#580]
![mobile](https://user-images.githubusercontent.com/43391939/50684292-4d350e80-1058-11e9-9fe6-beb85ac124e7.gif)

mobile: https://streamable.com/q27mi
On mobile, harassers can't dodge Branchball. 

On steam
![steam](https://user-images.githubusercontent.com/43391939/50684295-502fff00-1058-11e9-8a15-5c2877c6c85f.gif)
Steam: https://streamable.com/u7sac
Mobile Harassers perform a single melee attack before shadow jumping. But it seems like Steam Harassers  sometimes skip it and just shadow jump right away.

**Comment by sunnydaler** [comment]
I think it has something to do with the Steam Harassers' attack pattern. 
They dodge all kinds of melee attacks with shadow jump.

**Comment by cigumo** [comment]
fixed in 1.3.1
