### ISSUE TITLE
Faustus Liquid Fire cooldown too slow on steam / sunnydaler

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#583]
Mobile: 60
Steam: 25

Should we leave it around 45? 
Let's ask BBB

**Comment by sunnydaler** [comment]
BBB said "His Hero Spell does almost the same thing but has only 40 seconds cooldown... Liquid Fire on the other hand is much weaker:
1. Requires Faustus to be alive
2. Requires Faustus to be in position
3. Requires multiple enemies in range to cast
4. Cooldown can't be shortened by calling waves early."
"40 seconds is the ultimate's cooldown. Maybe 40 would work for Liquid Fire as well"

I replied, "the skill requires 3/3/3 hero points which is the same as his ultimate."

**Comment by cigumo** [comment]
ok! we have a winner! 40secs
changed in 1.3.1
