### ISSUE TITLE
Enemies' area attacks and flying heroes

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#585]
I checked enemies' area attacks on ground units to see if they can indirectly damage Faustus.

|attack name |love| cocos |
| --- | --- | --- |
| Catapult | yes | yes| 
| Hi-Hi Enha's special attack | yes | yes |
| Perython's stone | yes | yes | 
| Blasting Curse | yes | yes | 
| Bandersnatch basic attack | no | no | 
| Bandersnatch spine attack | yes | yes | 
| Shroom explosion | no | no | 
| Golem's attack | **no** | yes | 
| Razorboar's charge | no | no | 
| Shadow champion | no | no |

**Comment by cigumo** [comment]
changed in 1.4.3.
now bandersnatch hit flying heroes. 
not sure about golem... will ask gerson.

**Comment by cigumo** [comment]
> Gerson [2019-03-18 21:31]  ok, se va el ataque a volador del golem
