### ISSUE TITLE
Heavy Load upgrade makes victims not to explode when killed by druids.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#586]
On Steam, 
with Heavy Load upgrade, the enemies killed by druid's attacks (except for Fiery Nut) do not explode on death.

**Comment by sunnydaler** [comment]
I am not sure when it was fixed but...
Rags' basic area attack and hammertime & Arivan's Seal of Fire make enemies explode on death.
:+1: Love it!

**Comment by sunnydaler** [comment]
A big inconsistency found!

In all side missions of stage 1 thru 8,
enemies explode when killed by druids. However, in the main challenge of those stages, they don't.
in all missions of stage 9 and above, they don't.
![grimmsburg heroic](https://user-images.githubusercontent.com/43391939/51599155-4fe1a000-1f42-11e9-8bfa-f34bb719d8c7.jpg)

**Comment by cigumo** [comment]
fixed heavy load upgrade to allow enemies to explode in 1.4.0
