### ISSUE TITLE
Son of Mactans' poison attack pattern

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#588]
On cocos, 
when the spider is in melee with a unit, it attacks as followed:
attack with poison - 5 attacks - attack with  poison
So, there is about 3 sec of time when the unit is not afflicted with poison.
https://i.imgur.com/NOTGlBf.mp4
Cocos seems to be bugged in that the spider deals zero damage during that 3 sec time.
i don't know if it resets this pattern whenever the spider fights a new unit, (like poisoning them on every first attacks without a cooldown)

on steam, the victim is afflicted all the time while he is fighting the spider.

**Comment by cigumo** [comment]
The cooldown is specified as 1 sec, but... the counter is only incremented while the spider is idling between attacks. The attack animation lasts 20 frames, and the cooldown is 30 frames, so every 30 frames the counter only advances 10. This means that a 1 sec cooldown will take 3 seconds.

Also, while the poison is in cooldown, the attacks do no damage. This looks like an awful bug.

**Comment by cigumo** [comment]
I'll change the poison attack to have a 6 sec cooldown, which will leave 3 sec of no poison attacks. 
But I'm keeping making damage with the normal attacks, because it's nonsense otherwise. 

changed in 1.3.1
