### ISSUE TITLE
Lynn casts Weakening Curse on enemies without any resistance.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#589]
Wrong targets I checked are
-Gnoll Burner
-Gnoll Reaver
-Ettin
-Blood Servant
-BajNimen
-Bram
-Malicia
It seems like she targets any enemy whether they have resistance or not.
![2019_01_10_10_50_new - 609](https://user-images.githubusercontent.com/43391939/50941056-b2f52080-14c6-11e9-9743-e1cb06e8a609.jpg)

**Comment by cigumo** [comment]
fixed in 1.3.1
