### ISSUE TITLE
Some bosses are excluded from the target of Fate Sealed.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#590]
Hi-Hi Enha and Bajniem are not targetable.
![2019_01_10_10_45_new - 581](https://user-images.githubusercontent.com/43391939/50941306-afae6480-14c7-11e9-9896-1111dffbdf20.jpg)
![2019_01_10_10_39_new - 3119](https://user-images.githubusercontent.com/43391939/50941307-b1782800-14c7-11e9-8b2d-269b91fd990d.jpg)

Malicia, Bram and Spider Goddess are targetable. 
![2019_01_10_11_25_new - 1488](https://user-images.githubusercontent.com/43391939/50942197-1d0fc480-14cb-11e9-9471-2558ac564235.jpg)
![2019_01_10_10_50_new - 424](https://user-images.githubusercontent.com/43391939/50941096-da4bed80-14c6-11e9-846b-826e6b5e0825.jpg)
![2019_01_10_10_52_new - 1115](https://user-images.githubusercontent.com/43391939/50941149-0d8e7c80-14c7-11e9-875d-6456caa535ac.jpg)

**Comment by cigumo** [comment]
aim higher sunny! :)
