### ISSUE TITLE
Curse of Despair does not reduce some bosses' damage.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#591]
It works on Bram and Malicia.
![2019_01_10_11_19_new - 3386](https://user-images.githubusercontent.com/43391939/50942278-6a8c3180-14cb-11e9-9a8e-ba5a782a98eb.jpg)
![2019_01_10_10_50_new - 680](https://user-images.githubusercontent.com/43391939/50942323-8d1e4a80-14cb-11e9-83e4-6043503c495b.jpg)

But not on Hi-Hi Enha, Spider Goddess.

![2019_01_10_10_45_new - 725](https://user-images.githubusercontent.com/43391939/50940973-69a4d100-14c6-11e9-8572-7ad8f7d3ab28.jpg)
![2019_01_10_10_52_new - 1391](https://user-images.githubusercontent.com/43391939/50940976-6d385800-14c6-11e9-9159-a4960eb364d3.jpg)

I cannot test this skill on Baj'Nimen because no other enemies spawn (issue 592).

**Comment by cigumo** [comment]
checked mobile and affects Hi-Hiena, so fix the attacks to use the damage factor

**Comment by cigumo** [comment]
it's just the info bar

fixed in 1.3.1
- [x] Hi-Hi Enha: fixed
- [x] Spider Goddess: infobar shows no reduction on mobile, so no change
- [x] Baj'Nimen: fixed
