### ISSUE TITLE
Only the boss spawns after the Duredhel Outskirts wave 15.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#592]
After wave 15 of stage 20 is completed, only Baj'Nimen spawns.
No other enemies spawn after him, until the boss fight ends.

**Comment by cigumo** [comment]
this is weird. it's working properly for me. 
i'll review it with care.

**Comment by sunnydaler** [comment]
This might be a fault on my part-- the result of abusing n key

**Comment by sunnydaler** [comment]
Yes, found that this happens with n key abusement.

**Comment by cigumo** [comment]
closing it then
