### ISSUE TITLE
Fate Sealed animation is missing on certain enemies.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#593]
This Malicia pic shows how the display should be.
![boiling](https://user-images.githubusercontent.com/43391939/50943057-39613080-14ce-11e9-8238-eb9868203f5b.jpg)

Gnoll Catapult: the boiling animation and also the decal on the shadow are missing.
![2019_01_10_11_43_new - 236](https://user-images.githubusercontent.com/43391939/50942952-c952aa80-14cd-11e9-9e4c-56a0a0127622.jpg)

Spider Goddess: The shadow decal is there, but the boiling animation is missing.
![2019_01_10_10_52_new - 1115](https://user-images.githubusercontent.com/43391939/50941149-0d8e7c80-14c7-11e9-875d-6456caa535ac.jpg)

**Comment by cigumo** [comment]
fixed in 1.3.1
