### ISSUE TITLE
Bruce's ultimate should hide the target's sprite.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#595]
![bruce ulti](https://user-images.githubusercontent.com/43391939/50944892-b04df780-14d5-11e9-9483-c3f8b4ec8bcf.gif)

![bruce_ulti](https://user-images.githubusercontent.com/43391939/51416470-fe8d8580-1bbc-11e9-8e21-416f3512d51b.png)

This is how it is on cocos.
![mobile_bruce_ulti](https://user-images.githubusercontent.com/43391939/51416490-149b4600-1bbd-11e9-96a8-c8589638214a.gif)

**Comment by cigumo** [comment]
I kind of like it :) 
Let's see :)
