### ISSUE TITLE
Bravebark's ultimate deals zero damage to all bosses.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#597]
Hi-Hi Enha
Malicia
Spider Goddess
Bram
Baj'Nimen

**Comment by cigumo** [comment]
I've just checked mobile and there's a specific filter for bosses!

**Comment by sunnydaler** [comment]
The spell is similar to sapphire fangs but much weaker and underwhelming. Even if it could hit boss, the damage would be only 2 hundred something. 
I see no reason to exclude bosses when it is this weak.

**Comment by sunnydaler** [comment]
Never mind
