### ISSUE TITLE
Interval before the boss fight in stage 20

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#601]
I wish there were a short interval between the last enemy's death and the appearance of Baj'Nimen.
https://streamable.com/mbo9t

**Comment by cigumo** [comment]
to make it more epic? 
people always complain about these dead times

**Comment by sunnydaler** [comment]
Being the most durable and last one to spawn, golem is alway the last one to die. 
I think  2 sec break (starting from the moment the last enemy's bounty is given) would do good because  Golem's death animation is 2-sec long. 

On mobile, there is a short break after the last enemy's death and before the Boss appears on the screen.

**Comment by sunnydaler** [comment]
Android version
![mobile](https://user-images.githubusercontent.com/43391939/51477350-8e088380-1dcb-11e9-99b1-e5c3ed3b100f.gif)
