### ISSUE TITLE
enemies sometimes move faster after Curse of Despair wears off.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#602]
https://streamable.com/0ws50

**Comment by cigumo** [comment]
still looking for a way to reproduce it

**Comment by sunnydaler** [comment]
https://streamable.com/vheh2
I think it has something to do with interaction between Weakening Curse and Curse of Despair.

**Comment by cigumo** [comment]
found it! double remove: tween.remove and mod_track_target.update

**Comment by cigumo** [comment]
fixed in 1.3.1
