### ISSUE TITLE
fire and poison are displayed on Lynn's feet

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#604]
![2019_01_11_02_17_new - 95](https://user-images.githubusercontent.com/43391939/50985764-7a962680-1548-11e9-9044-3fda1556fc51.jpg)

![2019_01_11_02_28_new - 215](https://user-images.githubusercontent.com/43391939/50985951-deb8ea80-1548-11e9-8535-ba0e16de65ca.jpg)
![lynn](https://user-images.githubusercontent.com/43391939/50986362-ff357480-1549-11e9-8287-be2269ccc872.gif)
![bruce](https://user-images.githubusercontent.com/43391939/50986363-0066a180-154a-11e9-904c-09c111a9d08f.gif)

**Comment by cigumo** [comment]
fixed in 1.3.1
