### ISSUE TITLE
Explosions of Razz&Ragz's bunnies is drawn on top of building on Unseele Court map

### ISSUE THREAD

**Issue by guaranteed-to-be-unique** [cigumo/krli#607]
KRO steam 1.2.6 (Windows)

![bunny explosion](https://user-images.githubusercontent.com/22380626/51057900-16cb3680-15f8-11e9-8847-4ce1a463f24e.jpg)

**Comment by cigumo** [comment]
Welcome to github VirtualTT :D
Thanks for the feedback.

**Comment by cigumo** [comment]
fixed in 1.3.1
