### ISSUE TITLE
Lynn's ultimate explosion is denied

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#609]
![no explosion](https://user-images.githubusercontent.com/43391939/51065141-a7c8fe80-1646-11e9-8d0b-c938576a51f1.gif)

![no explosion 2](https://user-images.githubusercontent.com/43391939/51065315-8a486480-1647-11e9-9fde-877dfba910e6.gif)

**Comment by cigumo** [comment]
I think these two should work in 1.3.1

**Comment by sunnydaler** [comment]
It works.
