### ISSUE TITLE
KR3 R1 beta issues / THWeaver

### ISSUE THREAD

**Issue by Thought-Weaver** [cigumo/krli#61]
* [ ] (1) The dark overlay covering the hero selection screen misses the bottom half and top of the done button.
* [ ] (2) Eridan’s “Eldritch Slash” ability could be better worded as: “A special maneuver dealing 3 attacks for 15 to 45 damage on up to 3 enemies.”
* [ ] (3) When moving the map side to side, part of the map glitches and seems to move upward, then back downward while in fullscreen.
* [ ] (4) Top of text in the Encyclopedia is cut off slightly (by one or two pixels).
* [ ] (5) Bottom of text for Strike of Thunderbolt is cut off slightly (by one or two pixels).
* [ ] (6) The text for Strike of Thunderbolt says “they have a long cooldown” which should be “it has a long cooldown.”
* [ ] (7) There shouldn’t be a comma after “Eridan” when describing the Hero Power.
* [ ] (8) Is there supposed to be a sound effect for Eridan’s Hero Power? If so, I either can’t hear it or it doesn’t seem to be playing.
* [ ] (9) Perythons are slowed by Arivan’s Tornado, but not damaged.
* [ ] (10) Pressing an upgrade icon causes the upgrade achievement sound to play.
* [ ] (11) If you kill a Gnoll Catapult while the boulder toss animation is playing, no boulder will fall.
* [ ] (12) Despite having a healthbar, Gnoll Catapults can’t be damaged until reaching the end of their path.
* [ ] (13) If you get two achievements at once, only one appears at the top of the screen -- but both are mentioned by Steam at the bottom right-hand corner of the screen.
* [ ] (14) Sometimes when Hyenas die, they make the same sound as a humanoid character dying.
* [ ] (15) There is no application icon on Mac.
* [ ] (16) Arivan’s Hero Power, upgraded to its second level, causes some enemies to be permanently frozen on screen.
* [ ] (17) The text is quite small for the defeat tips.
* [ ] (18) Reg’son’s Eldritch Heal should say “Reg’son is healed for 15% of the enemy’s total life.”
* [ ] (19) The High Elven Mage Sentinel can be clicked like a friendly or enemy unit, but the information at the bottom disappears instantly. It causes a flash of a ring around the Sentinel.
* [ ] (20) When the Lake Monster crystalizes the Arch-Druid, the two upgrades appear in front of the crystal.
* [ ] (21) Malicia’s line “Sorry to have…” has a period and a comma at the end -- it should only be the latter.
* [ ] (22) Freezing with one of the magic stones on the floating island levels causes the enemy to also appear crystalized -- as though by the little dragons on the Lake Monster level.
* [ ] (23) A Cloud Stalker appeared with no notification or information. I don’t believe it was supposed to be part of the wave at all.
* [ ] (24) Scourger Banshees can be targeted and affected by tower abilities despite not being targeted by tower attacks.
* [ ] (25) Young Beresad has no sound effect when he burns the path.
* [ ] (26) Malicia can be attacked even when she is shielded.
* [ ] (27) An enemy, when teleported back, turned invisible. The health bar is visible in the lower left-hand corner.
* [ ] (28) The music and SFX sliders remember where they were, but the music and SFX plays at default volume.
* [ ] (29) If you upgrade barracks while they are moving, they will not continue to move towards their destination.
* [ ] (30) Teleporting an enemy with Faustus as they enter the teleporter on the floating island levels will not teleport them back down the path.

A list of images for these issues in addition to the listing is available here: https://docs.google.com/document/d/13kCqoTJwcKCrMp-3wt4SB2d3ew2-sUzMcCtYZokvoBw/edit?usp=sharing

**Comment by cigumo** [comment]
split into separate issues except these: 
- 6
- 3 does not happen with vsync
- 22 duplicate
