### ISSUE TITLE
Bruce's Ultimate ending sound is missing.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#615]
I think it is kro_sfx_bruce_guardianlions-hit[loop-end].ogg

and is there a Ulti starting sound effect on Steam? I am not sure.

**Comment by cigumo** [comment]
That sound is used in two cases
1. when the lions time out or reach the end of a path
2. when the whirl modifier finishes

I can hear them both in my build. Am I missing something?

**Comment by cigumo** [comment]
fixed in 1.3.1
