### ISSUE TITLE
Explosion overlaps Gnome's disintegration.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#618]
mobile:
![mobile](https://user-images.githubusercontent.com/43391939/51164291-ceee2d00-18df-11e9-8461-49947585e599.gif)

Steam:
![steam](https://user-images.githubusercontent.com/43391939/51164417-31472d80-18e0-11e9-9ab4-e00a68f136b1.gif)

**Comment by cigumo** [comment]
fixed in 1.3.1
