### ISSUE TITLE
Lynn ultimate tick is lost during teleportation

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#619]
I tested Fate Sealed level 3 against Hoplite and Evoker, they both have 700 hp in veteran mode.
If they either go thru a portal or are teleported during Fate Sealed progress,
they sometimes survive because a step is lost during teleportation.

mage teleport https://streamable.com/9fsce

portal https://streamable.com/8a20e

Venom vines poison affliction also loses 6-7 steps during teleportation.
it  might also affect other afflictions and health regen.

**Comment by cigumo** [comment]
will fix for R4 as it requires testing. 
related to #620

**Comment by cigumo** [comment]
Lynn's ulti modifier is a special case in that it does not check the target to be active before damaging it (most do) so it's an inconsistency in cocos code. I'm not sure if I need to fix this.
