### ISSUE TITLE
Young Ashbite damage / SealDarklight

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#62]
- [x] he deals twice the ammount of damage than in the mobile one. Dealing 83-125 instead of 42-62
- [x] dragon's attack rate is buffed. It attacks very slow on mobile; 2.8 seconds. But it attack relatively faster on Steam; 1.8 seconds. / sunnydaler

![816340_screenshots_20180910180806_1](https://user-images.githubusercontent.com/934821/45709912-8a35cd80-bb5b-11e8-82e6-78cd55ae1821.jpg)

**Comment by sunnydaler** [comment]
The damage is incorrectly listed on mobile. The dragon can actually deal more than that.

**Comment by cigumo** [comment]
fixed the attack rate, but left it at 2.6 so the animations syncs properly
