### ISSUE TITLE
Hermetic Insight description needs to be changed.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#621]
Veznan's Hermetic Insight

Description says "Increases Vez'nan's attack and ability range by 20/40/60%."

In fact, it increases range by 10/20/30%.

**Comment by cigumo** [comment]
fixed in 1.3.1

**Comment by sunnydaler** [comment]
Typo is there in lvl 2.
10%/10%30%

**Comment by cigumo** [comment]
fixed in 4.2.10
