### ISSUE TITLE
Eerie Gardner duration 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#626]
In the game description, its duration is 4/6 sec (damage is not stated.).

tick is 5 frames.

On Steam:
level 1: 30 ticks (5 sec), 30x3 dmg = 90 dmg
level 2: 42 ticks (7 sec), 42x4 dmg = 168 dmg

On mobile:
duration is one-step shorter than the description.
level 1: 23 ticks, 69 dmg
level 2: 35 ticks, 140 dmg

======================

**Comment by cigumo** [comment]
changed in 1.3.1  to 3.5/5.5 + 0.5 modifier duration 
damage: 72/144
