### ISSUE TITLE
Forest Keepers' ranged attacks often miss flying enemies.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#629]
![steam version](https://user-images.githubusercontent.com/43391939/51356682-e3f4d700-1afe-11e9-91b6-f6de8f7e0527.gif)
![steam version1](https://user-images.githubusercontent.com/43391939/51357431-3aafe000-1b02-11e9-890a-c6944d4a5612.gif)

They have difficulty targeting Cloud Stalkers and Bats that are flying towards exits.
They can target bats that halt and screech.

**Comment by cigumo** [comment]
fixed in 1.3.2
