### ISSUE TITLE
Cloud Stalkers: Druids can target them while flying / SealDarklight

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#63]
For what i know Druids can target Cloud Stalkers if they latch on soldiers on mobile, but this one they target them like regular enemies even if they fly. Druids can´t target Perythons or Gloomies but they can target on Cloud Stalkers.

Weirdwood too

**Comment by sunnydaler** [comment]
In my humble opinion, Druids should be able to target low flying enemies. I hope devs don't discourage building druids because they are already underused by their low impact and spamming of flying enemies, especially in Elite stage campaigns.

**Comment by cigumo** [comment]
kept mobile way: only targeted while facehugging
