### ISSUE TITLE
Eerie Gardner is triggered on blocked enemies.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#630]
Even including face-hugging Stalkers.
![steam version](https://user-images.githubusercontent.com/43391939/51356703-f8d16a80-1afe-11e9-9a56-cb0776168d2b.gif)

Here is how it is on mobile. https://streamable.com/ffbi1

**Comment by cigumo** [comment]
fixed in 1.3.2 and adds also a check for stunned enemies.
