### ISSUE TITLE
No "crit" chance on Golden Longbows' short-range shot

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#632]
Steam GL's  short-range shot doesn't seem to have crit chance.
Or, is it that "CRIT" is not displayed even when proced?

The following gif is from mobile.
![crit mobile](https://user-images.githubusercontent.com/43391939/51364683-3eeaf600-1b20-11e9-8c1b-8cb7dd1cfe9b.gif)

**Comment by cigumo** [comment]
because of how the comparison is used, we have to add a 1% to the chances in the settings. 
fixed in 1.3.2
