### ISSUE TITLE
Dark Pact - demon stutters

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#635]
v 1.3.2

1. demon stutters.  

2. the enemy that was stunned upon demon spawn never fights demon. (this applies only to the one in melee with demon)

https://streamable.com/9p52x
https://streamable.com/tuak2
Demons behaves normally when fighting among swarms of enemies.

----------------

in v 1.3.1, no.1 is present but not no.2. However, there's other bug in this version. golem freezes at some point while fighting demon. https://streamable.com/w0wp1

---------------
in v 1.3.0, it didn't have these problems. https://streamable.com/dfzzy

-------------
I think no.1 has something to do with the bug fix of #627 .

**Comment by cigumo** [comment]
fixed in 1.3.3
