### ISSUE TITLE
Scourger's whiplash attack

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#636]
https://streamable.com/bwwyw
on mobile, it is consists of 3 whiplashes (with 1 sec CD). 
And each whiplash is also consisted of 3 attacks, each dealing 6-10 damage (with 7 frames CD).
Thus, if enemies stay in the attack's damage area for the whole 3 whiplashes, they take 9*(6~10) damage.
And the damage can be stacked upon other scourger's whiplashes. 
Also, the new whiplash overlaps the old whiplash in the buff duration. https://streamable.com/fn0y2

on Steam, it is just a single attack, dealing 6-10 damage once. https://streamable.com/7unpy 
And it does not attack. So, the already "whiplashed" allies are immune to the attack and dealt zero damage.

**Comment by cigumo** [comment]
fixed in 1.4.3
