### ISSUE TITLE
Bleeding mark offset on running Blood Servant and Hyena

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#637]
Steam:
![blood](https://user-images.githubusercontent.com/43391939/51433765-294b0d00-1c95-11e9-9178-122a80aa3d5a.png)

![steam](https://user-images.githubusercontent.com/43391939/51433746-bb064a80-1c94-11e9-982e-64d9a8514b16.gif)
![steamhyena](https://user-images.githubusercontent.com/43391939/51433875-4fbe7780-1c98-11e9-8a0f-f02e85b96ea2.gif)

------------------------

Mobile:
![mobile](https://user-images.githubusercontent.com/43391939/51433882-72509080-1c98-11e9-9b06-5bf536de1157.gif)
![mobilehyena](https://user-images.githubusercontent.com/43391939/51433932-d0ca3e80-1c99-11e9-9a0c-838da059dadd.gif)

**Comment by cigumo** [comment]
fixed in 1.3.3
