### ISSUE TITLE
Burst Arrows - hit offset

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#641]
Steam
![steam](https://user-images.githubusercontent.com/43391939/51655037-3726c800-1fde-11e9-8d3a-ba72ae005994.gif)

Mobile
![mobile](https://user-images.githubusercontent.com/43391939/51655041-39892200-1fde-11e9-840a-19af187004e6.gif)

**Comment by cigumo** [comment]
also review how the range is applied and centered. looks small even on cocos

**Comment by cigumo** [comment]
fixed in 1.4.2
- moved the range to the target pos. 
- moved decal to the target position
- moved the explosion to the Z_EFFECTS layer
