### ISSUE TITLE
Kamihare hits flying enemies.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#642]
![boombunnies](https://user-images.githubusercontent.com/43391939/51778232-f0eb7900-2143-11e9-825b-549404a1e7e8.gif)
It is not triggered on birds though.

**Comment by cigumo** [comment]
also check wilbur bombs

**Comment by cigumo** [comment]
fixed wilbur bombs and kamihare not to trigger on flying enemies but hit them.
fixed 1.4.2
