### ISSUE TITLE
Arcane Sentinel - hit effect offset

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#643]
![sentinel offset](https://user-images.githubusercontent.com/43391939/51779269-a0771a00-2149-11e9-87ce-6712b9dec9b1.gif)
![sentinel](https://user-images.githubusercontent.com/43391939/51779318-ea600000-2149-11e9-880e-96e421f7de4c.jpg)

**Comment by cigumo** [comment]
fixed in 1.4.2
