### ISSUE TITLE
Forest Keepers - Circle of Life healing amount

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#646]
The description says,
"Heals themselves and nearby allies for 80/160/240 points over 4 seconds."

When I checked it on Steam with Xin (without his healing skill), total HP healed is 76/152/228.
Level 1 https://streamable.com/ti1k3
Level 2 https://streamable.com/o77eq
Level 3 https://streamable.com/pgon8

t heals 4/8/12 points per step and goes 19 steps.
It is one-step short of what is supposed be.

**Comment by cigumo** [comment]
fixed in 1.4.2
