### ISSUE TITLE
Timelapse interaction with razorboar rage / sunnydaler

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#647]
Lynn https://streamable.com/qcull
Bruce https://streamable.com/kpdr7 
Veznan https://imgur.com/v0CPyhN
Denas https://i.imgur.com/omteZ32
Bravebark https://i.imgur.com/7Fx80ee

**Comment by cigumo** [comment]
It's an interaction between mod_timelapse and mod_razorboar_rampage_speed.

**Comment by cigumo** [comment]
fixed in 1.4.2
