### ISSUE TITLE
bravebark's ultimate spikes are more distributed over the area.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#648]
Mobile:
![mobile](https://user-images.githubusercontent.com/43391939/51885212-dfb59d00-23cd-11e9-8af8-326c8196c32b.jpg)

Steam:
![steam](https://user-images.githubusercontent.com/43391939/51885215-e3492400-23cd-11e9-8e9b-31be1064df50.jpg)

The description says, "Densely covers a wide area with spiked vines." 
On Steam, spiked vines cover a wider area but with less density, which means less overlapping and more sparseness.
Each spiked vine's aoe doesn't overlap much. As a result, targets are dealt less damage and the effectiveness is reduced.
On mobile, the aoe overlaps up to 6 times on a big enemy, and up to 4 times on a normal or small sized enemy.

**Comment by cigumo** [comment]
post fix in 1.4.2

![screen shot 2019-02-07 at 10 18 26 pm](https://user-images.githubusercontent.com/934821/52453513-8284be80-2b26-11e9-9872-f2272473363c.jpg)
![screen shot 2019-02-07 at 10 18 36 pm](https://user-images.githubusercontent.com/934821/52453514-8284be80-2b26-11e9-9e17-ad24efd3bb1a.jpg)
