### ISSUE TITLE
Alric's Spiked Armor

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#656]
On flash version,
Spiked Armor gives back a 10/30/60 percentage of the raw damage that the opponent inflicts to Alric.
By "raw damage", I mean the damage value before being reduced by Alric's physical resistance.
for example, when Gorillon slams Alric with 60 damage, spiked armor III returns 36 damage to the ape. 

On love, this is not the case. and I think it is glitched in that the return percentage is based on the reduced damage by his armor, not the raw damage. Thus, spiked armor reflects lesser and lesser amount of damage in a given situation as his armor rating increases along with hero level.

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.00
