### ISSUE TITLE
blood pact / mounted avenger and instakills / explosions

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#657]
blood pact should be prevented by: 
- vindicator: not in cocos
- boulder: yes in cocos

**Comment by sunnydaler** [comment]
cocos boulder prevents: https://streamable.com/vxj0r 
v 1.4.1 love Eridan Double Strike doesn't: https://streamable.com/l1p08
v 1.4.1 love Wilbur M.A.D. Missile doesn't: https://streamable.com/veh61

**Comment by cigumo** [comment]
a summary: 
https://docs.google.com/spreadsheets/d/17WiHoZ-kx3VW4LmapIpvpZnepvOEz7jvXAPNCCi-Iiw/edit#gid=0

Both mounted and blood are weird cases.

**Comment by cigumo** [comment]
Current behaviour in love (v1.4.2)
- Shadow Champion
  - will spawn blood pact with instakills 
- Mounted Avenger
  - will not spawn avenger with reapers and other instakills

I will leave it like this for the moment.

**Comment by cigumo** [comment]
If I allow explosions to show it will break #657
