### ISSUE TITLE
Wave issues

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#66]
- [x] Waterfalls Trail it seems like the timing for the early call of the waves is off. Sometimes you can call them really early and sometimes you're just waiting. / 7ofAnn
- [x] On Arcane Quarters 13, at the end of wave 4, it takes an unusually long time for the last remaining creeps to emerge and the next wave icon to appear. / kevin32
  - seems ok
- [x] On Mactans' Retreat 14, at the end of wave 9, it takes an unusually long time for the last remaining creeps to emerge and the next wave icon to appear. / kevin32
  - feels ok. maybe this was because of #212
- [x] On Mactans' Retreat 14 Iron Challenge, when you start the wave, creeps don't come down the path for almost 1 minute. / kevin32
  - this was because of #212
- [x] Mactans' Retreat 14 Iron Challenge is very short with only several creeps to kill instead of dozens. / kevin32
  - probably this was because of #212
- [x] I just played Mactans' Retreat 14 Iron challenge and was surprised to find that the wave composition is different from the mobile version. On mobile, 30 Spiderbroods and 24 Mactans' Sons are spawned at the first part of the challenge. I mean the part until the Golem appears. Til then only the giant spider Mactans appears and tries to web my towers. / sunnydaler
  - this must have been due to #212 
- [x] On Shrine of Elynie 15, at the end of wave 8, it takes an unusually long time for the last remaining creeps to emerge and the next wave icon to appear. / kevin32
  - agree

**Comment by cigumo** [comment]
- Stage 3
  - both mobile and pc are the same
  - waves with too much waiting time in the flag: 3, 4
 -

**Comment by sunnydaler** [comment]
I dont see any problem with waiting time.
they can just call the wave and get some extra gold.
And this kind of waiting time is not confined to certain waves in kro.

**Comment by sunnydaler** [comment]
long wait time isn't just there. it is time to harvest extra gold!
