### ISSUE TITLE
Check the damage type

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#660]
entity                                     | cocos | love
--------------------------- | ------- | ------- 
 Gunboat bomb            |  phys   |  **explo** 
 Enemy ship's canonball.    |   phys  | phys      
 Quincon's ranged           |  phys |  **explo**     
 Quincon's melee            |  phys  | phys
 volcano fireball level 10  | explo  | explo      
 Jack O'Lantern's ranged    |  explo  | explo

**Comment by cigumo** [comment]
changed gunboat to pysical in kr2-desktop-3.2.00
left the others.
