### ISSUE TITLE
Razz and Rags both attack some enemies.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#662]
Razz throws bolt at Shadow Champion, Bram, Bandersnatch, Hi-Hi Enha even when Rags is fighting them.

**Comment by cigumo** [comment]
I think it's working properly. It shoots the melee blocked enemy unless there are other enemies nearby. 
![screen shot 2019-02-18 at 12 25 07 pm](https://user-images.githubusercontent.com/934821/52960843-65e35480-3378-11e9-8e66-8b64f44f462a.jpg)
