### ISSUE TITLE
Shrine of Regnos's explosive effect is shown behind the enemy's body.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#663]
This picture is from cocos iOS.
![cocos ios](https://user-images.githubusercontent.com/43391939/52531861-7cc5ed80-2d5f-11e9-978f-754f4c7b8ca0.jpg)

And this is from love.
![steam](https://user-images.githubusercontent.com/43391939/52531892-cdd5e180-2d5f-11e9-9d8d-d81886fa3f6a.jpg)

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.00
