### ISSUE TITLE
Gnomish Tinkering doesn't affect some.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#665]
At least on flash and Steam, "Gnomish Tinkering" level 4 upgrade only reduces Core Drill's cooldown (-3 seconds).
Wasp Missiles, Waste Disposal, and Furnace Blast cds are not reduced by this upgrade.

Maybe for balancing? dunno,

**Comment by cigumo** [comment]
- Had a bug in mecha which I fixed, 
- The lava attacks is part of the normal attack, which has a 3s cooldown, so unless the cooldown is reduced by 3 or more seconds, it will not be noticed. I will not fix this.

fixed in kr2-phone-3.1.0
