### ISSUE TITLE
Cronan's Deep Lashes

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#666]
Description: "special attack that deals 14/24/36 damage then bleeds its target for additional 12/36/72 damage."
In love, the additional bleeding damage is 12/36/72 per second.
It has been accepted as a buff by forum members but
https://forums.ironhidegames.com/viewtopic.php?f=5&t=26268&sid=e677030b0a2f64968522c38de8e5128d&start=20#p134510

I think it might be actually a mistake. A bug.

**Comment by cigumo** [comment]
yes, confirmed bug. 
fixed in kr2-phone-3.1.05
