### ISSUE TITLE
Death Rider should not be counted in the number of skeletons Necromancer Tower can have.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#667]
In love, Death Rider is counted as one of 8 skeletons that the tower can have at a time.
![love](https://user-images.githubusercontent.com/43391939/52544381-fc9d9780-2df3-11e9-8a71-19190b2d82e8.jpg)

--------
Flash
![flash](https://user-images.githubusercontent.com/43391939/52544383-00311e80-2df4-11e9-87d1-0a234922bfb9.jpg)

iOS
![ios](https://user-images.githubusercontent.com/43391939/53206055-4d728300-3673-11e9-9c1c-1cdecb50cbfc.JPG)

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.1.09
