### ISSUE TITLE
Enemy's bleeding effect is shown on flying heroes.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#670]
(and somehow bloodsydian is missing. it happened only once.)
![2019_02_11_20_25_new - 1720](https://user-images.githubusercontent.com/43391939/52560852-f67fd900-2e3c-11e9-96fd-a8e8280caa98.jpg)

It is not on cocos.

**Comment by cigumo** [comment]
fixed in 1.4.2
