### ISSUE TITLE
Shadowspawn and Dark spitters pics are switched in the New enemy popup.

### ISSUE THREAD

**Issue by guaranteed-to-be-unique** [cigumo/krli#683]
happens on krf 1.4.2 steam / windows
![2019-02-16_1844391](https://user-images.githubusercontent.com/22380626/52902101-11779200-321d-11e9-8c1b-aeb2a26d7945.png)

**Comment by sunnydaler** [comment]
Is it fixed with #677?

**Comment by cigumo** [comment]
fixed in 1.4.3
