### ISSUE TITLE
Soldiers are transformed to Werewolf when there's no Lycan around

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#684]
An Assassin turned into Werewolf as soon as the full moon period started.  :o
While just dealing with Abomination, not Lycan.
![qqdnu5c](https://user-images.githubusercontent.com/43391939/52907533-d326b500-32a6-11e9-98cd-2861d8c9efb3.jpg)

https://i.imgur.com/F4aUg7s.gif

![dj3a9th](https://user-images.githubusercontent.com/43391939/52907540-e89bdf00-32a6-11e9-9a16-1c393453f950.jpg)
https://i.imgur.com/0p3md5s.gif

**Comment by cigumo** [comment]
seems alright
