### ISSUE TITLE
Burning effect offset on veznan

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#690]
![burn](https://user-images.githubusercontent.com/43391939/53144756-df7d7b80-35e0-11e9-9d75-b085f640c76a.gif)
![burn2](https://user-images.githubusercontent.com/43391939/53144838-3a16d780-35e1-11e9-8ba9-9fc0149112a1.gif)

**Comment by cigumo** [comment]
fixed in 1.4.4
