### ISSUE TITLE
check if jack o'lantern spawn spawns should give gold

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#693]

**Comment by sunnydaler** [comment]
3 more things to check,
1. the soldier transformed into a werewolf by lycan
2. Saurian Quetzal's spawn
3. Reaper bred by Parasyte

**Comment by cigumo** [comment]
- [x] jack o'lantern spawns: useGold = 0
- [x] soldier transformed into werewolf: useGold = 0 in SoldierModifierLycanthropy
- [x] quetzal's spawn: should give gold (enemy_saurian_razorwing default gold value)
- [x] reaper from parasyte: useGold=false in EnemyAlienBreeder

fixed in kr2-desktop-3.2.00
- removes gold from jack o' spawns
- adds gold to spawned razorwings
