### ISSUE TITLE
Bloodsydian - teleport's safe node from the exit

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#697]
![1](https://user-images.githubusercontent.com/43391939/53353073-59a65b00-3967-11e9-9e91-4ca427ecdccd.gif)
![2](https://user-images.githubusercontent.com/43391939/53353079-5c08b500-3967-11e9-88ab-dc4a0ebeb517.gif)

**Comment by cigumo** [comment]
fixed in 1.4.5
range for teleport was to big
there seems to be something else limiting how far they go on iphone. reducing the max node to 20, and the min nodes to 10.
