### ISSUE TITLE
wave 6 flag for Blood Gnoll spawn is missing in Stage 18 Heroic.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#698]
22 blood gnolls spawn from the cave and head to the right exit

**Comment by cigumo** [comment]
![screen shot 2019-02-27 at 4 11 34 pm](https://user-images.githubusercontent.com/934821/53516242-9038be80-3aaa-11e9-8bbe-42bf633fcd81.jpg)

There are 22 blood gnolls in that snapshot. 
Is it not right?
