### ISSUE TITLE
Cronan's Stampede is weaker in love.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#699]
- [x] CD is longer: 25 second in love, 20 seconds in iOS and flash.

- [x] distance that rhinos travel is shorter.
![love](https://user-images.githubusercontent.com/43391939/53467866-3c72a900-3a9b-11e9-87dc-0c27e98097bc.jpg)
![ios](https://user-images.githubusercontent.com/43391939/53467861-38468b80-3a9b-11e9-89cf-d5e597512a8d.jpg)
![steam](https://user-images.githubusercontent.com/43391939/54485947-d07aa800-48c4-11e9-9e0c-df6cfbca3398.jpg)
![ios](https://user-images.githubusercontent.com/43391939/54485950-d40e2f00-48c4-11e9-9d09-4dbaf90edf25.jpg)

- [ ] damage is lower and very random.  maybe the damage also chance-based like stun, or rhino's aoe is small.

in flash version, each rhino deals 20/30/40 damage-totaling 40/90/160 damage, and the damage is very consistent along the path.

flash version stampede absolutely wrecks desert thugs in veteran mode.
![Stampede_flash_version](https://user-images.githubusercontent.com/43391939/54485765-44678100-48c2-11e9-8656-a3871edf47e1.gif)

**Comment by cigumo** [comment]
- my tests of the cooldown in cocos give 25s too
- fixed the distance (0.5s extra time)
- fixed a cooldown rounding error
- kept an ellipse instead of a circle for picking up enemies as used in cocos

kr2-desktop-3.2.00

**Comment by sunnydaler** [comment]
https://streamable.com/a4oxr 
stampede not casted over 1 min. (kr2-desktop-3.2.01)

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.07

**Comment by Mmlh1** [comment]
Will the damage remain at 15 per rhino instead of 40, like in Flash?
