### ISSUE TITLE
Kutsao's Leopard Style unblocks his target.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#700]
in iOS, his melee target remains still in its placed until kutsao finishes leopard style and comes back to it.
![ios](https://user-images.githubusercontent.com/43391939/53471925-a7c37780-3aa9-11e9-81a3-5e54e619326f.gif)

in love, it is unblocked just when kutsao starts to perform leopard style.
![love](https://user-images.githubusercontent.com/43391939/53471947-b6119380-3aa9-11e9-804d-68db0306c8fc.gif)

**Comment by cigumo** [comment]
yes, but I'm not going to fix this to prevent some enemy blocking issues.
