### ISSUE TITLE
Karkinos's Burrow speed

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#701]
The descriptions for each level are as followed.
Level 1 "Grants Karkinos the ability to travel 60% faster below ground." 
Level 2 "Increases burrow travel speed by an additional 60%." 
Level 3 "Increases burrow travel speed by an additional 60%." 

- [ ] In love, level 3 Burrow has the same speed as level 2. 

- [ ] actual speed difference doesn't match the descriptions.
Level 1 is actually 50% faster than walking. and level 2 is 80% faster than walking.
Descriptions have to be changed to match the speed modifier in the code.

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.1.09
- increased level 3 speed

The percentages are approx. ok. 

```
base: 1.9
1.1, 1.8, 2.8

(/ 1.1 1.9)
0.5789473684210527

(/ 1.8 (+ 1.1 1.9))
0.6

(/ 2.8 (+ 1.1 1.8 1.9))
0.5833333333333333
```
