### ISSUE TITLE
Wilbur's boom box, Rags' boom bunnies, and cloud stalkers

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#706]
flying cloud stalkers trigger boombox and boom bunnies.

remark: https://github.com/cigumo/krli/issues/642 

It looks like cigumo changed them not to hit flying enemies since then.

**Comment by cigumo** [comment]
fixed in 1.4.7

**Comment by cigumo** [comment]
they hit flying enemies, but their explosion should not be triggered by them. 
fixed here is that the attack is not triggered by flying enemies.
