### ISSUE TITLE
Check Phoenix's purification range

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#707]
It is smaller on love. 
On cocos phone, purification range seems to be bigger than the firebird's basic attack range. I see enemies turn to fireballs even if they die outside her attack range. https://streamable.com/v3av0

love: 
![love](https://user-images.githubusercontent.com/43391939/53718020-5cd8a400-3e9d-11e9-8043-c4bce0a823e1.gif)

cocos phone:
![cocos](https://user-images.githubusercontent.com/43391939/53718023-619d5800-3e9d-11e9-8a32-279d04ec1158.gif)

**Comment by cigumo** [comment]
It's a bug in Cocos. They forgot about GAME_SCALE, again. IPad has the right radius, but phones don't.  I'll leave as in iPad.
