### ISSUE TITLE
Ring of fire and disabling

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#711]
- [ ] while the infused tower is disabled by banshee,
ring of fire duration is paused in cocos, but not in love.
cocos https://streamable.com/3azpy 
love https://streamable.com/pjrhv 

- [ ] If the infused tower is diabled by crystal serpent,
In cocos, ring of fire is paused. it resumes after disabling wears out.
https://streamable.com/w64m1 
In love, it is not disabled at all.
https://streamable.com/03yaz

I haven't checked the interaction with Mactans' disabling.

**Comment by cigumo** [comment]
I'm not sure this was intended in cocos.

**Comment by sunnydaler** [comment]
Fine
