### ISSUE TITLE
Fireball explosion fx tracks heroes

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#712]
This happens when Veznan teleports and dodges it. The sound is heard but explosion is not shown.
![veznan](https://user-images.githubusercontent.com/43391939/53866419-e2428c80-4034-11e9-9644-ce42496d6275.gif)

And fireball explosion tracks heroes.

![lilith](https://user-images.githubusercontent.com/43391939/53868898-651a1600-403a-11e9-99db-1311cf995e90.gif)

![durax](https://user-images.githubusercontent.com/43391939/53868171-c4772680-4038-11e9-807a-719caa0e42f4.gif)

![regson](https://user-images.githubusercontent.com/43391939/53866793-bbd12100-4035-11e9-8162-4c91bc6053b9.gif)

**Comment by cigumo** [comment]
fixed in 4.0.01

**Comment by sunnydaler** [comment]
not fixed in desktop v 1.4.8
https://streamable.com/c4klm
https://streamable.com/8g1bi

**Comment by cigumo** [comment]
will be fixed in the next update as it's fixed in the code.
4.2.10
