### ISSUE TITLE
Veznan's Arcane Nova 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#713]
in cocos, veznan seems to target crowd and cast it on them.

in love, veznan casts it when there are 2 or more enemies are in his basic attack range. 
Thus, this happens. he casts it on a single enemy.
![2019_03_07_12_00 1 _new - 114](https://user-images.githubusercontent.com/43391939/53929505-4adf4700-40d1-11e9-9392-b5124aa25128.jpg)

**Comment by cigumo** [comment]
This is cocos. I see the exact same behaviour. What am I missing here @sunnydaler? 
![kr3-cocos-veznan-arcanenova mov](https://user-images.githubusercontent.com/934821/55635613-7bc99f00-5797-11e9-875e-ffa8344715df.gif)

**Comment by sunnydaler** [comment]
Ah, they are the same!
It doesnt have such code. Ok.
