### ISSUE TITLE
Zealot HP is the same in all difficulty modes

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#715]
in cocos, zealot's HP differs in every difficulty mode.
zealot's HP in casual/normal/veteran is well-documented here.
today I checked it again.
https://kingdomrushtd.fandom.com/wiki/Zealot

in love,
zealot's HP is the same in all difficulty modes.
150 in wave 3
180 in wave 5
200 in wave 8
250 in waves 11 and 15

**Comment by cigumo** [comment]
fixed in 4.0.01
