### ISSUE TITLE
Blood Pact and Lynn's Charm of Misfortune

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#716]
is it the only attack that she can't avoid?

**Comment by cigumo** [comment]
> [5:19 PM] cigumo: Lynn avoids damage in two ways
> [5:19 PM] cigumo: 1. dodging attacks when performed (melee, ranged)
> [5:20 PM] cigumo: 2. avoiding damage (area attacks, mods)
> [5:20 PM] cigumo: mods will still affect her, but she might avoid some damage from them
> [5:21 PM] cigumo: if it's a dps mod, she checks every time damage is applied
> [5:21 PM] cigumo: if it's a single damage hit, she might avoid all of it
