### ISSUE TITLE
hi-hi-ehna ground shake does not affect soldiers / kevin32

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#72]
- On Gryphon Point, Hi-Hi-Eyna slams his chain on the ground causing an earthquake, but nothing appears to be affected by this. Towers, heroes, and ground troops continue to function normally without being stunned.

**Comment by sunnydaler** [comment]
Damage not stunning

**Comment by cigumo** [comment]
it does not sutn. it's only damage and it seems to work.

**Comment by cigumo** [comment]
![screen shot 2018-09-28 at 8 07 52 pm](https://user-images.githubusercontent.com/934821/46237351-4d878480-c35a-11e8-82d5-9fef85c3c9e8.png)
