### ISSUE TITLE
Catha ultimate fail

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#720]
I have seen this glitch several times but this is the first time I captured it on video.
:-)
https://streamable.com/e8xsb
I had put enemies in sleep with it, 
then called the next wave and the spell became available again.
So I cast the ultimate on the same area hoping it would put the same enemies in sleep again.
but it failed to do so.

**Comment by cigumo** [comment]
I think this is because all the enemies in range are already stunned by the ultimate, and it is configured not to reset their time. A split second later it should have worked. 
I guess I'm not going to change this, but let me know what you think @sunnydaler

**Comment by sunnydaler** [comment]
a limitation that players have to be accustomed to.
