### ISSUE TITLE
Alric summons Sand Warriors behind him.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#725]
it is a disadvantage because it takes more time for sand warriors to travel to enemies.
Android, Steam:

![android](https://user-images.githubusercontent.com/43391939/54474832-44697180-482d-11e9-9871-b43d214b12f2.gif)

iOS (it is the same on Flash):
![ios](https://user-images.githubusercontent.com/43391939/54474803-eb99d900-482c-11e9-9f4d-60140ca8c249.gif)

**Comment by cigumo** [comment]
The rationale behind this difference is to block with enemies the hero is fighting and not skip them.

**Comment by sunnydaler** [comment]
ok~
