### ISSUE TITLE
Young Ashbite's Blazing Breath damage

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#727]
description says 150/250/350 damage.
in love, actual damage is 198/252/300 (in other words, 33/42/50 damage per 5 frames @ 30fps)
in cocos, it is 140/175/210 (20/25/30 damage per 3 frames @ 30fps)

Considering its upgrade cost (250/200/200), cocos seems to be bugged.

**Comment by cigumo** [comment]
set to 150/250/350 in 4.0.01
