### ISSUE TITLE
Hide the number of leftover stars on Upgrades menu.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#734]
in mobile/Flash KR1, iOS/Flash KR2, and cocos KR3
The number of leftover stars is not displayed after all upgrades are done.
![Screenshot_20190319-233115_Origins](https://user-images.githubusercontent.com/43391939/54614623-117ae400-4aa0-11e9-8ba6-f5c04f5505c9.jpg)
![Screenshot_20190319-233207_Kingdom Rush](https://user-images.githubusercontent.com/43391939/54614624-117ae400-4aa0-11e9-811f-4183f3aefaa2.jpg)

**Comment by cigumo** [comment]
fixed in phone 1.4.9

**Comment by cigumo** [comment]
fixed in kr2-desktop.3.1.11
