### ISSUE TITLE
Dark Forge Lightning Strike description is incorrect. 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#742]
Level 1: "arc to an additional target". 
Actually it arcs to 2 additional targets on ios and love.

Level 2: "arc to up to 2 additional targets". 
It arcs to 3 additional targets in fact.

===
The damage to additional targets doesn't increase with upgrades. Is this normal?
30-45 to the 2nd target
20-30 to the 3rd and above

**Comment by cigumo** [comment]
fixed in version kr2-phone-3.1.03
- description 
- bug in ray bounce upgrade level
