### ISSUE TITLE
Renegades' ranged attack cooldown

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#755]
Steam https://i.imgur.com/s9nibtj.mp4

cocos (Android) https://i.imgur.com/THrZbNm.mp4 

This makes me wonder why some attack cds are affected by animation length when most others are not. Is this intended..... or are these glitches

**Comment by cigumo** [comment]
you were right. cooldown in love was 1s instead of 1.74s 
fixed in 4.0.05

**Comment by cigumo** [comment]
fixed in 4.0.05
