### ISSUE TITLE
Arcane Sentinel can go and search enemies even if the tower gets disabled.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#756]
Scourger banshee https://streamable.com/1v9xz
Mactans https://streamable.com/cyij3
Malicia https://i.imgur.com/dBNzCev.mp4 
Grootslang https://i.imgur.com/998jQF8.mp4 
Spider Goddess (haven't checked this)

**Comment by cigumo** [comment]
cocos: 
- banshee block does not disable sentinels
- malicia block disables sentinels

**Comment by cigumo** [comment]
fixed in 4.2.10
