### ISSUE TITLE
no bell ringing sfx at the mission start.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#772]
When you press the challenge start button, 
 there is no bell ringing sound.
only fanfare is heard.

**Comment by cigumo** [comment]
I don't understand this one. 
Which challenge?

**Comment by sunnydaler** [comment]
every challenge, cig. I can hear the bell sound in kr1/ kr2 flash versions, kr1 cocos, and iOS gameplays on YouTube.

**Comment by cigumo** [comment]
do you mean the "ding" when powers/bag icons are unlocked with the first wave?

**Comment by sunnydaler** [comment]
I think i was wrong.
