### ISSUE TITLE
achievements not kept when upgrading

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#790]
some are kept but some are lost. 
check the plist names again.

**Comment by sunnydaler** [comment]
iron rush, heroic rush, mitchel-hedges, i like to move it, call me mr. pig, white rabbit, george fall, shenzi banzai & ed, dwarf falls, scissorfinger, ding ding ding, wile e, shroom says, peekaboo, candy rush, we are the champions, red five, heavyweight class, ace of spades, get the party started are lost. there are more. but I forgot which ones...

**Comment by cigumo** [comment]
fixed in 4.0.05
  - ace of spades
  - call me mr. pig
  - candy rush
  - ding ding ding
  - dwarf falls
  - get the party started
  - heavyweight class
  - heroic rush
  - i like to move it
  - iron rush
  - shenzi banzai & ed
  - we are the champions

could not find errors for: 
  - george fall (worked on cocos->love test moto4g android 7)
  - mitchel-hedges
  - peekaboo
  - red five
  - scissorfinger (worked on cocos->love test moto4g android 7)
  - shroom says
  - white rabbit  (worked on cocos->love test moto4g android 7)
  - wile e
