### ISSUE TITLE
ward of disruption removes hihi aura / sunnydaler

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#793]
also check vasile and spirit totem

**Comment by sunnydaler** [comment]
I didnt said it does. I was questioning.

**Comment by sunnydaler** [comment]
Justed checked that Ward of Disruption doesnt remove hihi enha's aura.

**Comment by sunnydaler** [comment]
found that Axthrowers don't cast Spirit Totem on Vasile in his second form.
