### ISSUE TITLE
Heartbox and bosses

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#801]
I let Nazeru go thru the exit after adding 5 hearts to the life.
And the game declares neither defeat or victory.
![Screenshot_20190419-151812_Frontiers](https://user-images.githubusercontent.com/43391939/56413126-66896000-62c1-11e9-8f69-313af885f6b5.jpg)

**Comment by cigumo** [comment]
hehe... the same happens in cocos :D

**Comment by cigumo** [comment]
fixed in kr2-phone-3.1.0
if the boss leaves it's a defeat
