### ISSUE TITLE
young ashbite can't target mantarays properly /sunnydaler

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#809]
More so in impossible mode.
Arcane Quarters wave 13 has mantaray rush that is good for testing.
Missed 16 times out of 22 attacks against mantaray rush in wave 13
I don't know how it is on cocos.

**Comment by sunnydaler** [comment]
arcane quarters wave 13 is good for testing.

**Comment by cigumo** [comment]
mitigated in 4.0.08
