### ISSUE TITLE
Alchemical Powder doesn't work.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#810]
KR1 has Smart Targeting (Artillery suffers no reduction of splash.) upgrade. and it makes artillery towers to deal maximum damage in their area of effect.

KR2 has a similar but chance-based upgrade, Alchemical Powder.
Alchemical Powder: Artillery has a chance of dealing maximum damage with no splash reduction.

I tested Level-3 artillery tower and Battle Mecha 20 attacks each on Steam. and I didn't see the max damage chance proc.

**Comment by cigumo** [comment]
I've tested it and it seems to work properly. 
It's only 10% and will only be visible on targets that have some distance from the bomb hit point.
