### ISSUE TITLE
Review Forge ray does jump through Frankie or enemies /sunnydaler

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#822]
iPad:
![Screenshot_20190504-105617_YouTube](https://user-images.githubusercontent.com/934821/57181181-d1f93300-6e66-11e9-90fc-b54d2329d140.jpg)

**Comment by sunnydaler** [comment]
https://youtu.be/h0vCdVTe7KA?t=360
https://youtu.be/h0vCdVTe7KA?t=697 
![cap](https://user-images.githubusercontent.com/43391939/57183742-55109c80-6eec-11e9-8d62-63ce5ac0ba53.jpg)

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.1.09
