### ISSUE TITLE
Teleporting chance is low on High Elven Mage

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#826]
I tested it against a single Golem. 
teleport happened 15 out of 485 attacks. (counting hem's 3 bolts as a single attack)
That's 3.092% chance.

**Comment by cigumo** [comment]
tt.alter_reality_chance = 0.03
@"teleportChanceHighElven":@(0.03f),

**Comment by cigumo** [comment]
it's the same as cocos.
