### ISSUE TITLE
Nivus bolt prediction on Saurian Darters

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#842]
LÖVE: https://i.imgur.com/HrgLj3H.mp4 
![2019_06_04_03_30_50_549_new - 426](https://user-images.githubusercontent.com/43391939/58825918-69c28a80-867a-11e9-9a26-f40f9f794a2b.jpg)

And the bolt end shouldn't look like it is cut even if the original target dies before getting hit by the bolt.

**Comment by cigumo** [comment]
https://i.imgur.com/HrgLj3H.mp4

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.1.09
