### ISSUE TITLE
buy upgrade button can be touched through the description

### ISSUE THREAD

**Issue by victoriadelima** [cigumo/krli#845]
if twin shot is the last upgrade to buy and you buy it, tapping the lower half of the description board buys it again (as you can see from the negative stars
![Screenshot_20190606-122158](https://user-images.githubusercontent.com/49003944/59105600-a5738380-890a-11e9-8763-93c7ae3c484d.png)

**Comment by cigumo** [comment]
fixed in kr2-phone-3.2.14 and kr3-phone-4.2.14
commit a9e9d9e58fdeeecd2402885b473e855334c57675
