### ISSUE TITLE
ranged enemies should abort ranging Dierdre if she teleports.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#857]
and their projectile should miss.

Blazefang
https://streamable.com/jlida
https://streamable.com/g82o0

Deathcoil
https://streamable.com/mncu8

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.1.09
- [x] deathcoil
- [x] blazefang
- [x] munra
- [x] shaman necromancer
- [x] bluegale
- [x] savant ray
- [x] umbra ray
- [x] umbra guy ray
