### ISSUE TITLE
Tetsubo Storm excludes bosses and pumpkin-headed knight.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#859]
Considering other heroes' signature attacks are ok to be performed on these targets.
Mirage's backstab
Cronan's deeplashes
Dante's silver bullet
Alric's flurry
Kutsao's dragon style
Grawl's shard punch

I wonder why not

**Comment by cigumo** [comment]
For some reason Tetsubo is not applied to any bosses, and the pumpkin head is classified as one.
