### ISSUE TITLE
Gunboat missile is missing the launching sfx.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#867]

**Comment by sunnydaler** [comment]
No sfx when it crashes either.

**Comment by cigumo** [comment]
- SOUND SpecialVolcanoLavaShoot defined but sound sources missing.
- SOUND SpecialVolcanoLavaShootHit defined but sound sources missing.

**Comment by cigumo** [comment]
fixed sounds and bullet rotation in kr2-phone-3.1.03
