### ISSUE TITLE
achievement great defenders not being granted

### ISSUE THREAD

**Issue by victoriadelima** [cigumo/krli#871]
The achievement was not granted on a ipad air with OS 12.4.1 and game version 3.7.2

![1](https://user-images.githubusercontent.com/49003944/63968410-0330eb00-ca76-11e9-89a9-a2710a7f48d0.jpg)
![2](https://user-images.githubusercontent.com/49003944/63968418-04faae80-ca76-11e9-8da4-03833dbebb8e.jpg)

Ticket
http://support.ironhidegames.com/a/tickets/57330

**Comment by cigumo** [comment]
this is ipad
