### ISSUE TITLE
Blood is displayed behind the body.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#881]
![Screenshot_2019-09-15_005137](https://user-images.githubusercontent.com/43391939/64966514-e0a62b00-d8d9-11e9-8b66-48cf132bffd0.jpg)
Falconer's Attack, Cronan Deep Lashes, Arterial Strike.

**Comment by cigumo** [comment]
fixes in kr2-phone-3.1.06
- arterial seems to be fine
- deep lashes: fixed
- falconer's attack: fixed
