### ISSUE TITLE
Localization unfinished on a tip card

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#885]
![Screenshot_2019-09-26_185134](https://user-images.githubusercontent.com/43391939/65684755-60cb4e00-e09b-11e9-830c-3b4169040819.jpg)
![Screenshot_2019-09-26_202058](https://user-images.githubusercontent.com/43391939/65684757-62951180-e09b-11e9-8570-f5a20be2ac54.jpg)

Korean: 갑옷 입은 적은 공병, 병사, 돌 드루이드 공격의 피해를 더 적게 받습니다.
![steam](https://user-images.githubusercontent.com/43391939/65683580-8acf4100-e098-11e9-8358-63eea89f2fa1.jpg)

**Comment by sunnydaler** [comment]
titles are different, too.
 "새 팁" (new tip) in mobile, and "힌트" (hint) in Steam.

**Comment by cigumo** [comment]
fixed in kr3-phone-4.1.07
