### ISSUE TITLE
korean translation suggestions / sunnydaler

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#887]
## KR2
- [x] On the new archer tower cards of kr1 and kr2, it says "레벨 4 장궁병 타워 (level 4 longbowmen tower)" on the title. I suggest replacing it with "레벨 4  궁수 타워".

## KR3
- [ ] Archer: 궁병 -> 궁수 (more commonly used)

**Comment by sunnydaler** [comment]
On the new archer tower cards of kr1 and kr2,
it says "레벨 4 장궁병 타워 (level 4 longbowmen tower)" on the title.
I suggest to replace it with "레벨 4  궁수 타워".

**Comment by cigumo** [comment]
all these lines have the word archer and have to be reviewed 
https://docs.google.com/spreadsheets/d/1sOgYFAE83UyD3d-0sfrWRhRpfhOC6dCVUVAWKu6QDC0/edit#gid=0
