### ISSUE TITLE
"barracas" on the Golden Longbows card 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#888]
![Screenshot_2019-09-26_233645](https://user-images.githubusercontent.com/43391939/65699390-fd501900-e0b8-11e9-8ed7-d1025cfea9b8.jpg)
![Screenshot_2019-09-26_235116](https://user-images.githubusercontent.com/43391939/65699393-fde8af80-e0b8-11e9-82bb-49a7de51bfac.jpg)

**Comment by cigumo** [comment]
fixed in 4.2.10
