### ISSUE TITLE
Korean localization of Hammerhold

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#890]
<Hammerhold>

![Screenshot_2019-09-27_192737](https://user-images.githubusercontent.com/43391939/65766563-56c25180-e166-11e9-8763-0e5b1ea9764a.jpg)

![20190927193048_1](https://user-images.githubusercontent.com/43391939/65766529-40b49100-e166-11e9-8a16-56bb79eabc7c.jpg)

Original text:
"Defender of Linirea! Your services are once more required, as evil forces are attacking the ancient stronghold of Hammerhold! It hasn't been attacked in a long time... and now it's again under siege by nomadic desert tribes!

Take command of the kingdom's forces, and defend us!"

Corrected version
"리니리아의 수호자여! 악의 세력이 고대 요새 해머홀드를 공격하고 있어 당신의 도움이 다시 한번 필요합니다! 이곳은 한동안 평화로웠지만, 이제 다시금 사막 유랑 부족에게 포위되고 말았습니다!

왕국의 군대를 지휘해 우리를 지켜주십시오!"

Reasons:
there is a typo in mobile version.
Both versions are not faithful to the original text.

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.1.09
<img width="295" alt="Screen Shot 2019-10-14 at 9 37 52 AM" src="https://user-images.githubusercontent.com/934821/66751843-5fa16b80-ee66-11e9-9ef0-23765764d433.png">

**Comment by sunnydaler** [comment]
Thx!
