### ISSUE TITLE
Armor buff aura and Dante's Relics of Power 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#894]
In the clip, Dante got Relics of Power lvl 3.
https://streamable.com/cb42p

the buff aura is off and the armor/resistance is lowered 100% by dante.  However, the enemy still has armor/resistance when it had none before the buff.

**Comment by cigumo** [comment]
- mitigated in kr2-desktop-3.1.09
- relic will remove all armor modifiers before reducing the armor.
- shaman mod will track total increased armor (initial and later).
