### ISSUE TITLE
Cloudstakers facehugging Durax and the clones not in the right way.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#895]
Mobile: Face on Durax, belly on the clones.
![Screenshot_2019-10-08_232647](https://user-images.githubusercontent.com/43391939/66404557-a8e75a80-ea23-11e9-8515-ebb98cc46963.jpg)

Steam: Chest on Durax, belly on the clones.
![20191008232350_1](https://user-images.githubusercontent.com/43391939/66404653-cf0cfa80-ea23-11e9-9f6c-44a9e0de442e.jpg)

**Comment by cigumo** [comment]
fixed in 4.2.10
