### ISSUE TITLE
Frankenstein tower ray glitch

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#898]
http://support.ironhidegames.com/a/tickets/58053

**Comment by cigumo** [comment]
![](https://cdn.discordapp.com/attachments/212252625792532480/631587946637557781/Screenshot_20191009-080742_Frontiers.jpg)

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.1.09

**Comment by victoriadelima** [comment]
http://support.ironhidegames.com/a/tickets/58305
