### ISSUE TITLE
Korean translation of "Life" in Encyclopedia

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#900]
![20191014203427_1](https://user-images.githubusercontent.com/43391939/66748532-6231ae80-eec2-11e9-8beb-4403593ea8ce.jpg)
![20191014201954_1](https://user-images.githubusercontent.com/43391939/66748543-64940880-eec2-11e9-875d-adf129b14ae5.jpg)
생명력 means vitality, vitalidad. In KR games, 생명력 is used to convey the meaning of "Health" as in healing skills and regeneration. 
And it is also used to mean "Life" in Encyclopedia.

The correct translation of "Life (Vida)" is "라이프 (Romanization of "life")" as it is shown below.
![Screenshot_2019-10-13_200026](https://user-images.githubusercontent.com/43391939/66748878-47ac0500-eec3-11e9-9629-8497d8c26261.jpg)

"1 라이프" is correct, not "라이프 1".
This is in the same sense that "day 1" and "1 day" are different in meanings.

**Comment by cigumo** [comment]
fixed translation of %d Live and %d Lives to %d 라이프
kr2-desktop-3.2.00
