### ISSUE TITLE
Level 2 mage description in Korean 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#902]
![Screenshot_2019-10-15_111145](https://user-images.githubusercontent.com/43391939/66794613-1a9c3880-ef3d-11e9-95d8-986100b01b8a.jpg)
![Screenshot_2019-10-15_110919](https://user-images.githubusercontent.com/43391939/66794615-1bcd6580-ef3d-11e9-8a2a-adc134734257.jpg)

This is a typo.
Change "와와" to "뼈와" 
See the KR1 screenshot below for reference.
![Screenshot_2019-10-15_114104](https://user-images.githubusercontent.com/43391939/66795865-d874f600-ef40-11e9-9548-49c4a3958f8f.jpg)

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.00
