### ISSUE TITLE
"Great" armor rating in Korean

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#903]
![Screenshot_2019-10-15_020846](https://user-images.githubusercontent.com/43391939/66795356-5506d500-ef3f-11e9-82f8-a8b7586d6377.jpg)
매우 높음 (very high) in the encyclopedia, which is ok.
![Screenshot_2019-10-15_020749](https://user-images.githubusercontent.com/43391939/66795387-6e0f8600-ef3f-11e9-8168-fea85ad1a6dd.jpg)
![Screenshot_2019-10-15_114456](https://user-images.githubusercontent.com/43391939/66796017-4f11f380-ef41-11e9-9f96-d0c03c850035.jpg)

on the status bar, it says "최선". 최선(the best way) is not the right word.

 I guess there isn't enough space to put 매우 높음 there.
If the space is not enough, "최상 (best, highest)" can be used instead. 

Here is the reference for the word 최상. 최상급 means the highest level
![20191015122610_1](https://user-images.githubusercontent.com/43391939/66797896-360c4100-ef47-11e9-9356-82f32a6b900d.jpg)

This applies to all enemies with "Great" rating in armor or magic resistance
Dark Slayer, Raider, Bloodshell, Gerald, Thor, Hacksaw.

**Comment by cigumo** [comment]
fixed in kr2-x-3.2.16
