### ISSUE TITLE
Ashbite and carcass / sunnydaler

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#912]
- carcass does not follow enemy size
- some enemies should not produce a carcass: gunboat, ghosts

![](https://cdn.discordapp.com/attachments/418776085086470144/634482970719289374/phantom.gif)

![](https://cdn.discordapp.com/attachments/418776085086470144/634481960626159639/ghost.gif)

![](https://cdn.discordapp.com/attachments/418776085086470144/634463147146608690/gunboat.gif)

![](https://cdn.discordapp.com/attachments/418776085086470144/634463144294744064/parasyte.gif)

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.00
- gunboat: normal death  (F_EAT ban)
- ghost: normal death
- phantom warrior: normal death
- enemies that cannot explode will show normal death
- size: adjusted fx scale for small enemies to 0.8 and large 1.2

**Comment by sunnydaler** [comment]
Normal (red flesh and bones flying) carcass doesn't fit spiders.
![2019_11_21_02_53_22_156_new - 215](https://user-images.githubusercontent.com/43391939/69264723-37e2b780-0c0b-11ea-9047-cd1c6b1bc80b.jpg)

**Comment by cigumo** [comment]
cocos also shows carcass

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.12
