### ISSUE TITLE
Blood Trickster raises zombies from instakilled or exploded corpses.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#913]
Artillery 
![zombie raise](https://user-images.githubusercontent.com/43391939/67086730-61f42480-f1dc-11e9-9705-bcdc8b881400.gif)
Drilll Core ![drill](https://user-images.githubusercontent.com/43391939/67086748-6caeb980-f1dc-11e9-8e7e-0b74ae503e9a.gif)
Silver Bullet ![silver bullet](https://user-images.githubusercontent.com/43391939/67086767-77694e80-f1dc-11e9-9d7c-c47335e2b707.gif)
Abduction
![abduction](https://user-images.githubusercontent.com/43391939/67098373-0a16e700-f1f7-11e9-88fc-570dcf8edaaf.gif)
Disintegrate
![disintegrate](https://user-images.githubusercontent.com/43391939/67098384-11d68b80-f1f7-11e9-902c-a13bc9fa7063.gif)

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.00
