### ISSUE TITLE
Rename jack'o lantern

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#918]
English: Jack O'Lantern
Deutsch: Kürbis-Jack
Français: Tête de citrouille
Português: Jack da Lanterna
Espanõl: Jinete sin Cabeza 

繁體中文: 南瓜燈傑克
简体中文: 南瓜灯杰克
Korean: 잭 오 랜턴
Japanese: ジャック・オ・ランタン
Russian: Тыквоголовый всадник

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.01
