### ISSUE TITLE
Sfx problems.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#929]
- [x] No sound when a soldier turns to werewolf.  
      halloween_werewolf_transformation.ogg
- [x] Gunboat has no sfx for its death. 
       Gunboat_death.ogg
- [x] Cave opening sound is missing in the Dark Descent. 
       mountain_door.ogg
- [x] Saurian Savant ranged attack sound is missing. 
       savant_attack.ogg
- [x] Grawl's bounder throw sound does not sync with action. 
       hero_grawl_boulder_throw.ogg
- [x] When Mirage's illusion disappears/puffs, it is missing a sound effect.
       hero_mirage_shadowdodge_puff.ogg

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.04

**Comment by sunnydaler** [comment]
- [x] Dwarven Bastion's keg throw sfx doesn't fit. It is that of artillery shooting. (can u replace it with the sound that is used for Captain Blackthorn's keg throw?)

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.05
