### ISSUE TITLE
Mactans cause temporarily freeze for a split-second when she spins webs. / kevin32

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#93]
- On Shrine of Elynie, sometimes Mactans will cause the game to temporarily freeze for a split-second when she spins webs. This only happened a few times. (Windows 8.1. 4 GB RAM and a 512 MB dedicated video)

**Comment by cigumo** [comment]
I can't reproduce this one.

**Comment by sunnydaler** [comment]
never had this problem
