### ISSUE TITLE
Mirage should be invulnerable while she backstabs.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#931]
cocos:
![ios](https://user-images.githubusercontent.com/43391939/67790478-336a2980-fab9-11e9-9ea4-ef574184bc54.gif)

love:
![mirage](https://user-images.githubusercontent.com/43391939/67790388-0ae22f80-fab9-11e9-8251-2d4f764e2e77.gif)

probably also from ranged attacks while backstabbing.

**Comment by sunnydaler** [comment]
Oh, the animation is different. 
In cocos, Death explosion animation is used also when Abominations are instakilled or blown up by artillery.

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.04
- mirage invuln
- abomination now always uses it's death explosion animation

**Comment by sunnydaler** [comment]
an iOS user told me that Mirage was eaten by Snapvine while backstabbing. I guess she is targetable no matter what. this is his pic https://imgur.com/a/7BiK0Jo
