### ISSUE TITLE
Barrage cd

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#935]
found a difference in Barrage.
not sure if it is ciro's intention.
cd is 5 sec, right?
in cocos, timer starts when the barrage animation ends.
at all barrage levels, it goes like this: Barrage - 10 basic shots (5 sec) - Barrage

in love, timer starts when the barrage animation begins.
so, the number of basic shots between Barrage cycles is different at each level.
8 at lvl 1 , 7 at 2 & 3

**Comment by cigumo** [comment]
changed to cocos cooldown: 10 basic shots between barrages
fixed in kr2-desktop-3.2.04
