### ISSUE TITLE
Human-Lycan

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#942]
Core Drill: It doesn't die and shifts to wolf. 
https://imgur.com/FMiUcmU.mp4

Dante's Silver Bullet Level 3 deals lethal blow: It doesn't die and shifts to wolf. 
https://imgur.com/e7RSrfg.mp4

Mirage's Lethal Strike Level 3 deals final blow: It dies in wolf-form.
https://imgur.com/Y7yMQvB.mp4

Mirage's Lethal Strike instakill procs: It is killed and carcass is displayed.
https://imgur.com/bDXYqJL.mp4

(Look at the gold count!)

**Comment by cigumo** [comment]
- instakill should not let the transformation happen
- do not give wold when transforming

**Comment by cigumo** [comment]
I can't fix the death in wolf form because there is no human form death animation. It will always change and die.

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.06

**Comment by sunnydaler** [comment]
Dante's lvl 3 silver bullet doesnt kill human-lycan which has 320 hp. kr2-desktop-3.2.06
https://i.imgur.com/DTlswcH.mp4

**Comment by cigumo** [comment]
cocos does the same thing, so I think I'll not change it.
