### ISSUE TITLE
human-lycan doesnt have a proper portrait.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#947]
KR1 cocos:
![Screenshot_2019-11-10_192309](https://user-images.githubusercontent.com/43391939/68545249-9e4b2700-040e-11ea-8a5e-fcd26b18ae3d.jpg)

KRF love:
![Screenshot_2019-11-10_192852](https://user-images.githubusercontent.com/43391939/68545259-a6a36200-040e-11ea-93c3-32ca9b17d249.jpg)

same on kr2-desktop-3.2.06

**Comment by cigumo** [comment]
fixed in kr2-phone-3.2.07 o
