### ISSUE TITLE
Disease Nova description in Korean

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#949]
![2019_11_11_00_22_23_913_new - 0](https://user-images.githubusercontent.com/43391939/68546465-c429f900-0419-11ea-9f21-c4b3c1052e8b.jpg)
it is differently translated.

Steam: 본하트가 땅을 폭발시켜 [[150의 피해를 주고, 폭발에 휩쓸린 적들을 감염시킵니다.]]

Mobile: 본하트가 폭발해 [[주변을 감염시키고 150의 범위 피해를 줍니다.]]

I put ok phrases in"[[ ]]". Both descriptions are not good.

Disease Nova is similar to Immolate of Phoenix; both dive into the ground dealing area damage.
![2019_11_11_00_20_46_555_new - 0](https://user-images.githubusercontent.com/43391939/68546553-e2dcbf80-041a-11ea-961a-d69ef82115bc.jpg)

lets change these;

본하트가 땅을 폭발시켜 (Bonehart explodes the ground)
본하트가 폭발해 (Bonehart explodes)

to this; 본하트가 땅으로 급강하해 (Bonehart swoops down to the ground)

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.07
