### ISSUE TITLE
Courage

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#956]
![2019_11_14_17_50_15_48](https://user-images.githubusercontent.com/43391939/68841690-6858bc00-0708-11ea-9bea-d8ec0e47a119.jpg)
This upgrade affects Bonehart's Bone Golems but not Cronan's Boars.
On flash version, it affects boars.

**Comment by cigumo** [comment]
added courage in kr2-desktop-3.2.09 to:
- cronan's boars
- dwarf soldiers in stage 14
