### ISSUE TITLE
Nivus ray

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#958]
it is not pretty: https://streamable.com/1w1qb

cocos version:
he aborts if he loses target. https://i.imgur.com/WiTJXPk.mp4
ray looks normal either when it misses target https://i.imgur.com/bVn1fy6.mp4
or when the target dies before the strike animation isn't yet finished. https://i.imgur.com/YPCBDxE.mp4 

love version: 
https://i.imgur.com/X7XK7MZ.mp4
https://i.imgur.com/OIFWYwS.mp4
https://i.imgur.com/bgZXDA4.mp4
(the dot goes missing when the ray loses target.)

**Comment by cigumo** [comment]
fixed in 3.2.09
- interrupts shoot if target dies or disappears
- always shows the hit ball fx
- hit ball does not disappear when the target explodes while being hit
