### ISSUE TITLE
Plague Carrier, Blazing Breath, Wildfire Barrage and Nightscale

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#959]
Plague Carrier doesn't infect invisible Nightscales. https://i.imgur.com/pGoWefv.mp4
Blazing Breath doesn't burn them. https://streamable.com/j2ne2
Wildfire Barrage doesn't burn them. https://streamable.com/fcno1

---------
on the other hand, Stampede can stun and damage them. https://streamable.com/1s6cn

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.09
- barrage hits them
- breath hits them
- plague carrier and disease mod hits them
