### ISSUE TITLE
prevent Kahz's teleport near exits

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#962]
He teleports an enemy to his place, often bringing it closer to the exit. this can happen way past the defense And then, he bull-rushes forward to charge yet another enemy, leaving the teleported one unattended. 
This overall makes teleport ability a hindrance. 

how about adding a safety node from the exit (20 nodes would suffice?)
so that he wouldn't teleport enemy while he is within the safety distance?

**Comment by cigumo** [comment]
good idea. limited from the defend point (shield in ground)
added in kr2-console-3.2.09
