### ISSUE TITLE
Tower-disabling also makes it unable to tap anything.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#967]
kr2 blacksurge https://streamable.com/goexv
kr2 beresad https://streamable.com/rqki9
kr3 banshee https://streamable.com/lk0jw
kr3 mactans https://streamable.com/0k0zm
kr3 malicia not yet tested
kr3 grootslang: https://streamable.com/gwgij
(What else can disable towers? Ainyl?)
If any tower gets disabled while the tower is selected, i cannot tap anything (spell powers, units, wave icon) until the tower becomes abled again.

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.14
