### ISSUE TITLE
Can Mirage's illusion be killed?

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#969]
Myrmidon's vampiric bite https://i.imgur.com/MUghXnA.mp4
Vampiresa's drain life https://i.imgur.com/hO8eMsr.mp4 
Enemy pirateship's cannon https://i.imgur.com/C6s8ZTG.mp4
(Vasile has deadly bloodsucking skill, too. but her illusion fights him as normal not "dying instantly")

Does her illusion have HP? 
It looks like illusion vanishes even before its attack animation plays, as if it is killed by these attacks. And puff sfx doesn't play when it is "killed" like that. 

Normally, Illusion lasts longer and attack animation plays correctly. and puff sfx plays fine too. (even when it fights Executioner.)
https://i.imgur.com/YDUbng1.mp4
https://i.imgur.com/w9a507I.mp4

**Comment by cigumo** [comment]
yes, it can be killed and the attacks can be interrupted. 
it's like a reinforcement. 
I can see the puf animation and the sound is also playing.
