### ISSUE TITLE
Hero spawn animation

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#971]
On game start,
Kutsao's level up animation is used.
In cocos, his game start animation is the same as his respawn animation.

love kutsao on game start: 
![kutsao start](https://user-images.githubusercontent.com/43391939/69007545-54b88a00-0982-11ea-8dae-05387e95e816.gif)

love kutsao on respawn:
![kutsao respawn](https://user-images.githubusercontent.com/43391939/69007569-b7aa2100-0982-11ea-9137-5de4d30f724b.gif)

Same bug on Nivus and Dierdre.

love nivus on game start: 
![nivus start](https://user-images.githubusercontent.com/43391939/69007358-2cc82700-0980-11ea-994f-e7c27ceb7b1e.gif)
love nivus on respawn: 
![nivus respawn](https://user-images.githubusercontent.com/43391939/69007362-36ea2580-0980-11ea-83ca-ddafdcba20d7.gif)

love dierdre on game start: 
![love dierdre start](https://user-images.githubusercontent.com/43391939/69007459-56ce1900-0981-11ea-8a71-d24f4d1f9288.gif)
love dierdre on respawn:
![love dierdre respawn](https://user-images.githubusercontent.com/43391939/69007475-7c5b2280-0981-11ea-8085-b836ed6d3a55.gif)

**Comment by sunnydaler** [comment]
![kutsao_padmasana](https://user-images.githubusercontent.com/43391939/69005672-c683da00-0968-11ea-8ca3-818876256903.gif)
On map entrance,
Kutsao's level up animation is used.
On cocos, his spawn animation(as the gif above) is  used.

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.09
