### ISSUE TITLE
water interaction

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#974]
- [x] when the missile doesn't have any target and hits the water, it make a splash in cocos, but an explosion in love.

love: https://streamable.com/gfjhy
cocos: https://streamable.com/yxhm7

- [x] when crossbow barrage bolt hits the water, dust doesn't rise in cocos. but does in love.
love:
![20191119_053610](https://user-images.githubusercontent.com/43391939/69136808-dfbe8f00-0afe-11ea-89af-381ab604a9fa.jpg)

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.09

**Comment by sunnydaler** [comment]
![Screenshot_2019-11-20_000526](https://user-images.githubusercontent.com/43391939/69158326-97689680-0b29-11ea-88fb-93351cb530b5.jpg)
![Screenshot_2019-11-20_000541](https://user-images.githubusercontent.com/43391939/69158345-9e8fa480-0b29-11ea-810c-32bf23099c73.jpg)
Akimbo Style also displays the dust when the bullet hits water in love.

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.09
