### ISSUE TITLE
Instakills leave no ghost for Dante /sunnydaler

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#975]
nazeru
https://streamable.com/r04q8

carnivore plant
https://i.imgur.com/dUfRTyB.mp4

**Comment by sunnydaler** [comment]
imo, this doesn't look like a bug. 

Dante's soul comes out of his dead body. 
https://i.imgur.com/Qjjcxmo.mp4
and these instakills do not leave his body behind.

**Comment by cigumo** [comment]
in cocos instakills dont' leave soul behind, so it's the same. 
closing.
