### ISSUE TITLE
Review the offsets of Karkinos's waterball and Grawl's boulder.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#977]
![Screenshot_2019-11-19_230325](https://user-images.githubusercontent.com/43391939/69153058-ebbb4880-0b20-11ea-865d-12cc57b4acd4.jpg)

Waterball falls over the shoulder of Nazeru. 
https://i.imgur.com/3ZpGlaI.mp4

Both are kinda artillery attacks but the offsets are not centered on the ground.
 Thus, they look off when hitting enemies with elevated hit offset cuz they hit where bolt and arrow hit.

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.09: shoots to the ground
- karkino's cannon
- growl's boulder
