### ISSUE TITLE
Dante buff active after being instakilled

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#981]
Even if Dante gets instakilled by Nazeru, Sand Worm, Carnivore Plant,
His buff aura will be still active after that.
![Screenshot_2019-11-20_140956](https://user-images.githubusercontent.com/43391939/69211110-4ba50400-0ba0-11ea-9bb2-48a2dfddf4a6.jpg)
![Screenshot_2019-11-20_162620](https://user-images.githubusercontent.com/43391939/69217773-b8c19500-0bb2-11ea-9f4c-d51ddf239a97.jpg)

**Comment by cigumo** [comment]
fixed in kr2-x-3.2.16
