### ISSUE TITLE
Gunboat's rocket tail

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#984]
![gunboat rocket tail](https://user-images.githubusercontent.com/43391939/69240682-5b443d00-0be0-11ea-867f-4d7e7a47e2b2.jpg)

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.12
<img width="231" alt="Screen Shot 2019-11-28 at 9 05 59 AM" src="https://user-images.githubusercontent.com/934821/69805671-e2d11380-11bf-11ea-8b6a-75377bc0531b.png">
