### ISSUE TITLE
Holy Light condition

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#986]
I think Dierdre should cast Holy Light either when A) there are soldiers to heal or B) when revival chance procs.

https://i.imgur.com/fTt0r1R.mp4 - here, barracks soldiers are eaten and she casts the skill twice in vain.

https://i.imgur.com/ztV37Au.mp4 - here, she casts it just when the reinforcements go away and does it again after a cd.

**Comment by cigumo** [comment]
fixed in kr2-x-3.2.16
