### ISSUE TITLE
Poison offset and dodge

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#988]
![2019_11_21_01_15_49_486_new - 18945](https://user-images.githubusercontent.com/43391939/69258225-9d30ab80-0bff-11ea-9223-a3f9ac7999e0.jpg)
https://i.imgur.com/f68VIZ6.mp4

Kutsao on Crane Style, Assassins on Dodge

**Comment by cigumo** [comment]
fixed Kutsao but won't fix assassins on dodge because it requires big changes. 
kr2-x-3.2.16
