### ISSUE TITLE
Great Defender description 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#991]
![2019_11_21_03_07_39_185](https://user-images.githubusercontent.com/43391939/69265210-277f0c80-0c0c-11ea-96af-b991967042df.jpg)
With the inclusion of Supreme Defender achievement, Great Defender needs to specify in which difficulty the campaigns are required to be done.  
Like "in normal mode"

fyi, in KR3 Steam, it writes "(...) in normal difficulty."

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.12
